//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperianLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperianLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OutputRoot xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Output xmlns=&quot;http://schema.uk.experian.com/experian/cems/msgs/v1.1/ConsumerData&quot;&gt;
        ///    &lt;Applicant xmlns=&quot;&quot;&gt;
        ///      &lt;ApplicantIdentifier&gt;1&lt;/ApplicantIdentifier&gt;
        ///      &lt;Name&gt;
        ///        &lt;Forename&gt;ABDUL&lt;/Forename&gt;
        ///        &lt;Surname&gt;GARTWRIGHT&lt;/Surname&gt;
        ///      &lt;/Name&gt;
        ///      &lt;Gender&gt;M&lt;/Gender&gt;
        ///      &lt;FormattedName&gt; A Gartwright&lt;/FormattedName&gt;
        ///    &lt;/Applic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output007 {
            get {
                return ResourceManager.GetString("output007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OutputRoot xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Output xmlns=&quot;http://schema.uk.experian.com/experian/cems/msgs/v1.1/ConsumerData&quot;&gt;
        ///    &lt;Applicant xmlns=&quot;&quot;&gt;
        ///      &lt;ApplicantIdentifier&gt;1&lt;/ApplicantIdentifier&gt;
        ///      &lt;Name&gt;
        ///        &lt;Forename&gt;ABUL&lt;/Forename&gt;
        ///        &lt;Surname&gt;FAYER&lt;/Surname&gt;
        ///      &lt;/Name&gt;
        ///      &lt;Gender&gt;M&lt;/Gender&gt;
        ///      &lt;FormattedName&gt; A Fayer&lt;/FormattedName&gt;
        ///    &lt;/Applicant&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output020 {
            get {
                return ResourceManager.GetString("output020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OutputRoot xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Output xmlns=&quot;http://schema.uk.experian.com/experian/cems/msgs/v1.1/ConsumerData&quot;&gt;
        ///    &lt;Applicant xmlns=&quot;&quot;&gt;
        ///      &lt;ApplicantIdentifier&gt;1&lt;/ApplicantIdentifier&gt;
        ///      &lt;Name&gt;
        ///        &lt;Forename&gt;ADAM&lt;/Forename&gt;
        ///        &lt;Surname&gt;THURSTON&lt;/Surname&gt;
        ///      &lt;/Name&gt;
        ///      &lt;Gender&gt;M&lt;/Gender&gt;
        ///      &lt;FormattedName&gt; A Thurston&lt;/FormattedName&gt;
        ///    &lt;/Applicant&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output022 {
            get {
                return ResourceManager.GetString("output022", resourceCulture);
            }
        }
    }
}
