// ReSharper disable InconsistentNaming
namespace Reports {
	public enum ReportType {
		RPT_ACCOUNTING_LOAN_BALANCE,
		RPT_ALIBABA_DATA_SHARING,
		RPT_ALIBABA_FUNNEL,
		RPT_CCI,
		RPT_EARNED_INTEREST,
		RPT_EARNED_INTEREST_ALL_CUSTOMERS,
		RPT_FINANCIAL_STATS,
		RPT_GENERIC,
		RPT_IN_WIZARD,
		RPT_LOAN_INTEGRITY,
		RPT_LOAN_STATS,
		RPT_LOANS_GIVEN,
		RPT_MARKETING_CHANNELS_SUMMARY,
		RPT_NEW_CLIENT,
		RPT_STRATEGY_RUNNING_TIME,
		RPT_TRAFFIC_REPORT,
		RPT_UI_EXT_REPORT,
		RPT_UI_REPORT,
	} // enum ReportType
} // namespace Reports
// ReSharper restore InconsistentNaming
