-- Create user 
create USER &&SCHEMA_NAME IDENTIFIED BY &&SCHEMA_NAME
DEFAULT TABLESPACE &&TS_TAB
TEMPORARY TABLESPACE TEMP;
-- Grant/Revoke system privileges 
alter user &&SCHEMA_NAME QUOTA UNLIMITED ON &&TS_TAB;
alter user &&SCHEMA_NAME QUOTA UNLIMITED ON &&TS_INDEX;
grant connect to &&SCHEMA_NAME; 
GRANT RESOURCE, EXECUTE_CATALOG_ROLE, SELECT_CATALOG_ROLE TO &SCHEMA_NAME;
GRANT CREATE SYNONYM TO &&SCHEMA_NAME.;
GRANT CREATE DATABASE LINK TO &&SCHEMA_NAME.;
GRANT CREATE TYPE TO &&SCHEMA_NAME.;
GRANT CREATE TABLE TO &&SCHEMA_NAME.;
GRANT CREATE TRIGGER TO &&SCHEMA_NAME.;
GRANT CREATE SEQUENCE TO &&SCHEMA_NAME.;
GRANT CREATE PROCEDURE TO &&SCHEMA_NAME.;
GRANT CREATE view to &&SCHEMA_NAME;
GRANT CREATE session to &&SCHEMA_NAME.;
GRANT CREATE cluster to &&SCHEMA_NAME.;
GRANT alter  session to &&SCHEMA_NAME.;

/*
-- Create user 
create USER &&SCHEMA_NAME IDENTIFIED BY &&SCHEMA_NAME
DEFAULT TABLESPACE &&TS_TAB
TEMPORARY TABLESPACE TEMP;

-- Grant/Revoke system privileges 
alter user &&SCHEMA_NAME QUOTA UNLIMITED ON &&TS_TAB;

alter user &&SCHEMA_NAME QUOTA UNLIMITED ON &&TS_INDEX;

grant connect to &&SCHEMA_NAME  with admin option;

GRANT RESOURCE, EXECUTE_CATALOG_ROLE, SELECT_CATALOG_ROLE TO &SCHEMA_NAME;

GRANT ALTER USER TO &&SCHEMA_NAME.;

GRANT CREATE USER TO &&SCHEMA_NAME.;

GRANT INSERT ANY TABLE TO &&SCHEMA_NAME.;

GRANT SELECT ANY TABLE TO &&SCHEMA_NAME.;

GRANT UPDATE ANY TABLE TO &&SCHEMA_NAME.;

GRANT ALTER ANY SEQUENCE TO &&SCHEMA_NAME.;

GRANT DROP PUBLIC SYNONYM TO &&SCHEMA_NAME.;

GRANT SELECT ANY SEQUENCE TO &&SCHEMA_NAME.;

GRANT UNLIMITED TABLESPACE TO &&SCHEMA_NAME.;

GRANT CREATE PUBLIC SYNONYM TO &&SCHEMA_NAME.;

GRANT EXECUTE ANY PROCEDURE TO &&SCHEMA_NAME.;

GRANT DROP PUBLIC DATABASE LINK TO &&SCHEMA_NAME.;

GRANT CREATE PUBLIC DATABASE LINK TO &&SCHEMA_NAME.;


GRANT SELECT ANY SEQUENCE to &&SCHEMA_NAME. with admin option;

GRANT SELECT ANY table to &&SCHEMA_NAME. with admin option;

GRANT CREATE ANY table to &&SCHEMA_NAME. with admin option;

GRANT DROP ANY table to &&SCHEMA_NAME. with admin option;

GRANT CREATE PUBLIC DATABASE LINK to &&SCHEMA_NAME. with admin option;

GRANT drop PUBLIC DATABASE LINK to &&SCHEMA_NAME. with admin option;


grant select on sys.all_users to &&SCHEMA_NAME  with grant option
/

grant select on sys.ALL_OBJECTS to &&SCHEMA_NAME  with grant option
/
grant select on sys.v_$mystat to &&SCHEMA_NAME  
/

GRANT CREATE TYPE TO &&SCHEMA_NAME.;
GRANT CREATE TABLE TO &&SCHEMA_NAME.;
GRANT CREATE TRIGGER TO &&SCHEMA_NAME.;
GRANT CREATE SEQUENCE TO &&SCHEMA_NAME.;
GRANT CREATE PROCEDURE TO &&SCHEMA_NAME.;




*/