//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace PayPal.Services.Private.Permissions {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PermissionsSOAP11Binding", Namespace="http://svcs.paypal.com/services")]
    public partial class Permissions : System.Web.Services.Protocols.SoapHttpClientProtocol {

        private System.Threading.SendOrPostCallback RequestPermissionsOperationCompleted;

        private System.Threading.SendOrPostCallback GetAccessTokenOperationCompleted;

        private System.Threading.SendOrPostCallback GetPermissionsOperationCompleted;

        private System.Threading.SendOrPostCallback CancelPermissionsOperationCompleted;

        private System.Threading.SendOrPostCallback GetBasicPersonalDataOperationCompleted;

        private System.Threading.SendOrPostCallback GetAdvancedPersonalDataOperationCompleted;

        /// <remarks/>
        public Permissions() {
            this.Url = "https://svcs.paypal.com/Permissions";
        }

        /// <remarks/>
        public event RequestPermissionsCompletedEventHandler RequestPermissionsCompleted;

        /// <remarks/>
        public event GetAccessTokenCompletedEventHandler GetAccessTokenCompleted;

        /// <remarks/>
        public event GetPermissionsCompletedEventHandler GetPermissionsCompleted;

        /// <remarks/>
        public event CancelPermissionsCompletedEventHandler CancelPermissionsCompleted;

        /// <remarks/>
        public event GetBasicPersonalDataCompletedEventHandler GetBasicPersonalDataCompleted;

        /// <remarks/>
        public event GetAdvancedPersonalDataCompletedEventHandler GetAdvancedPersonalDataCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:RequestPermissions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RequestPermissionsResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public RequestPermissionsResponse RequestPermissions([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] RequestPermissionsRequest RequestPermissionsRequest) {
            object[] results = this.Invoke("RequestPermissions", new object[] {
                        RequestPermissionsRequest});
            return ((RequestPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginRequestPermissions(RequestPermissionsRequest RequestPermissionsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RequestPermissions", new object[] {
                        RequestPermissionsRequest}, callback, asyncState);
        }

        /// <remarks/>
        public RequestPermissionsResponse EndRequestPermissions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RequestPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public void RequestPermissionsAsync(RequestPermissionsRequest RequestPermissionsRequest) {
            this.RequestPermissionsAsync(RequestPermissionsRequest, null);
        }

        /// <remarks/>
        public void RequestPermissionsAsync(RequestPermissionsRequest RequestPermissionsRequest, object userState) {
            if ((this.RequestPermissionsOperationCompleted == null)) {
                this.RequestPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestPermissionsOperationCompleted);
            }
            this.InvokeAsync("RequestPermissions", new object[] {
                        RequestPermissionsRequest}, this.RequestPermissionsOperationCompleted, userState);
        }

        private void OnRequestPermissionsOperationCompleted(object arg) {
            if ((this.RequestPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestPermissionsCompleted(this, new RequestPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetAccessToken", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAccessTokenResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public GetAccessTokenResponse GetAccessToken([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] GetAccessTokenRequest GetAccessTokenRequest) {
            object[] results = this.Invoke("GetAccessToken", new object[] {
                        GetAccessTokenRequest});
            return ((GetAccessTokenResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAccessToken(GetAccessTokenRequest GetAccessTokenRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAccessToken", new object[] {
                        GetAccessTokenRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetAccessTokenResponse EndGetAccessToken(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetAccessTokenResponse)(results[0]));
        }

        /// <remarks/>
        public void GetAccessTokenAsync(GetAccessTokenRequest GetAccessTokenRequest) {
            this.GetAccessTokenAsync(GetAccessTokenRequest, null);
        }

        /// <remarks/>
        public void GetAccessTokenAsync(GetAccessTokenRequest GetAccessTokenRequest, object userState) {
            if ((this.GetAccessTokenOperationCompleted == null)) {
                this.GetAccessTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessTokenOperationCompleted);
            }
            this.InvokeAsync("GetAccessToken", new object[] {
                        GetAccessTokenRequest}, this.GetAccessTokenOperationCompleted, userState);
        }

        private void OnGetAccessTokenOperationCompleted(object arg) {
            if ((this.GetAccessTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessTokenCompleted(this, new GetAccessTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetPermissions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetPermissionsResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public GetPermissionsResponse GetPermissions([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] GetPermissionsRequest GetPermissionsRequest) {
            object[] results = this.Invoke("GetPermissions", new object[] {
                        GetPermissionsRequest});
            return ((GetPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPermissions(GetPermissionsRequest GetPermissionsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPermissions", new object[] {
                        GetPermissionsRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetPermissionsResponse EndGetPermissions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public void GetPermissionsAsync(GetPermissionsRequest GetPermissionsRequest) {
            this.GetPermissionsAsync(GetPermissionsRequest, null);
        }

        /// <remarks/>
        public void GetPermissionsAsync(GetPermissionsRequest GetPermissionsRequest, object userState) {
            if ((this.GetPermissionsOperationCompleted == null)) {
                this.GetPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionsOperationCompleted);
            }
            this.InvokeAsync("GetPermissions", new object[] {
                        GetPermissionsRequest}, this.GetPermissionsOperationCompleted, userState);
        }

        private void OnGetPermissionsOperationCompleted(object arg) {
            if ((this.GetPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionsCompleted(this, new GetPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:CancelPermissions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelPermissionsResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public CancelPermissionsResponse CancelPermissions([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] CancelPermissionsRequest CancelPermissionsRequest) {
            object[] results = this.Invoke("CancelPermissions", new object[] {
                        CancelPermissionsRequest});
            return ((CancelPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCancelPermissions(CancelPermissionsRequest CancelPermissionsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelPermissions", new object[] {
                        CancelPermissionsRequest}, callback, asyncState);
        }

        /// <remarks/>
        public CancelPermissionsResponse EndCancelPermissions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CancelPermissionsResponse)(results[0]));
        }

        /// <remarks/>
        public void CancelPermissionsAsync(CancelPermissionsRequest CancelPermissionsRequest) {
            this.CancelPermissionsAsync(CancelPermissionsRequest, null);
        }

        /// <remarks/>
        public void CancelPermissionsAsync(CancelPermissionsRequest CancelPermissionsRequest, object userState) {
            if ((this.CancelPermissionsOperationCompleted == null)) {
                this.CancelPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelPermissionsOperationCompleted);
            }
            this.InvokeAsync("CancelPermissions", new object[] {
                        CancelPermissionsRequest}, this.CancelPermissionsOperationCompleted, userState);
        }

        private void OnCancelPermissionsOperationCompleted(object arg) {
            if ((this.CancelPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelPermissionsCompleted(this, new CancelPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetBasicPersonalData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetBasicPersonalDataResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public GetBasicPersonalDataResponse GetBasicPersonalData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] GetBasicPersonalDataRequest GetBasicPersonalDataRequest) {
            object[] results = this.Invoke("GetBasicPersonalData", new object[] {
                        GetBasicPersonalDataRequest});
            return ((GetBasicPersonalDataResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetBasicPersonalData(GetBasicPersonalDataRequest GetBasicPersonalDataRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBasicPersonalData", new object[] {
                        GetBasicPersonalDataRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetBasicPersonalDataResponse EndGetBasicPersonalData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetBasicPersonalDataResponse)(results[0]));
        }

        /// <remarks/>
        public void GetBasicPersonalDataAsync(GetBasicPersonalDataRequest GetBasicPersonalDataRequest) {
            this.GetBasicPersonalDataAsync(GetBasicPersonalDataRequest, null);
        }

        /// <remarks/>
        public void GetBasicPersonalDataAsync(GetBasicPersonalDataRequest GetBasicPersonalDataRequest, object userState) {
            if ((this.GetBasicPersonalDataOperationCompleted == null)) {
                this.GetBasicPersonalDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBasicPersonalDataOperationCompleted);
            }
            this.InvokeAsync("GetBasicPersonalData", new object[] {
                        GetBasicPersonalDataRequest}, this.GetBasicPersonalDataOperationCompleted, userState);
        }

        private void OnGetBasicPersonalDataOperationCompleted(object arg) {
            if ((this.GetBasicPersonalDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBasicPersonalDataCompleted(this, new GetBasicPersonalDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetBasicPersonalData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAdvancedPersonalDataResponse", Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)]
        public GetAdvancedPersonalDataResponse GetAdvancedPersonalData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://svcs.paypal.com/types/perm", IsNullable=true)] GetAdvancedPersonalDataRequest GetAdvancedPersonalDataRequest) {
            object[] results = this.Invoke("GetAdvancedPersonalData", new object[] {
                        GetAdvancedPersonalDataRequest});
            return ((GetAdvancedPersonalDataResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAdvancedPersonalData(GetAdvancedPersonalDataRequest GetAdvancedPersonalDataRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAdvancedPersonalData", new object[] {
                        GetAdvancedPersonalDataRequest}, callback, asyncState);
        }

        /// <remarks/>
        public GetAdvancedPersonalDataResponse EndGetAdvancedPersonalData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetAdvancedPersonalDataResponse)(results[0]));
        }

        /// <remarks/>
        public void GetAdvancedPersonalDataAsync(GetAdvancedPersonalDataRequest GetAdvancedPersonalDataRequest) {
            this.GetAdvancedPersonalDataAsync(GetAdvancedPersonalDataRequest, null);
        }

        /// <remarks/>
        public void GetAdvancedPersonalDataAsync(GetAdvancedPersonalDataRequest GetAdvancedPersonalDataRequest, object userState) {
            if ((this.GetAdvancedPersonalDataOperationCompleted == null)) {
                this.GetAdvancedPersonalDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdvancedPersonalDataOperationCompleted);
            }
            this.InvokeAsync("GetAdvancedPersonalData", new object[] {
                        GetAdvancedPersonalDataRequest}, this.GetAdvancedPersonalDataOperationCompleted, userState);
        }

        private void OnGetAdvancedPersonalDataOperationCompleted(object arg) {
            if ((this.GetAdvancedPersonalDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdvancedPersonalDataCompleted(this, new GetAdvancedPersonalDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class RequestPermissionsRequest {

        private RequestEnvelope requestEnvelopeField;

        private string[] scopeField;

        private string callbackField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scope", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                this.callbackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/common")]
    public partial class RequestEnvelope {

        private string errorLanguageField;

        private System.Xml.XmlElement[] anyField;

        public RequestEnvelope() {
            this.errorLanguageField = "en_US";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorLanguage {
            get {
                return this.errorLanguageField;
            }
            set {
                this.errorLanguageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetAdvancedPersonalDataResponse {

        private ResponseEnvelope responseEnvelopeField;

        private PersonalData[] responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("personalData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersonalData[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/common")]
    public partial class ResponseEnvelope {

        private System.DateTime timestampField;

        private AckCode ackField;

        private bool ackFieldSpecified;

        private string correlationIdField;

        private string buildField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AckCode ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ackSpecified {
            get {
                return this.ackFieldSpecified;
            }
            set {
                this.ackFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/common")]
    public enum AckCode {

        /// <remarks/>
        Success,

        /// <remarks/>
        Failure,

        /// <remarks/>
        Warning,

        /// <remarks/>
        SuccessWithWarning,

        /// <remarks/>
        FailureWithWarning,

        /// <remarks/>
        CustomCode,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class PersonalData {

        private PersonalAttribute personalDataKeyField;

        private string personalDataValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PersonalAttribute personalDataKey {
            get {
                return this.personalDataKeyField;
            }
            set {
                this.personalDataKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string personalDataValue {
            get {
                return this.personalDataValueField;
            }
            set {
                this.personalDataValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public enum PersonalAttribute {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/namePerson/first")]
        httpaxschemaorgnamePersonfirst,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/namePerson/last")]
        httpaxschemaorgnamePersonlast,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/email")]
        httpaxschemaorgcontactemail,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schema.openid.net/contact/fullname")]
        httpschemaopenidnetcontactfullname,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/company/name")]
        httpaxschemaorgcompanyname,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/country/home")]
        httpaxschemaorgcontactcountryhome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/birthDate")]
        httpaxschemaorgbirthDate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/postalCode/home")]
        httpaxschemaorgcontactpostalCodehome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schema.openid.net/contact/street1")]
        httpschemaopenidnetcontactstreet1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schema.openid.net/contact/street2")]
        httpschemaopenidnetcontactstreet2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/city/home")]
        httpaxschemaorgcontactcityhome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/state/home")]
        httpaxschemaorgcontactstatehome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://axschema.org/contact/phone/default")]
        httpaxschemaorgcontactphonedefault,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("https://www.paypal.com/webapps/auth/schema/payerID")]
        httpswwwpaypalcomwebappsauthschemapayerID,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetAdvancedPersonalDataRequest {

        private RequestEnvelope requestEnvelopeField;

        private PersonalAttribute[] attributeListField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersonalAttribute[] attributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetBasicPersonalDataResponse {

        private ResponseEnvelope responseEnvelopeField;

        private PersonalData[] responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("personalData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersonalData[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetBasicPersonalDataRequest {

        private RequestEnvelope requestEnvelopeField;

        private PersonalAttribute[] attributeListField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersonalAttribute[] attributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class CancelPermissionsResponse {

        private ResponseEnvelope responseEnvelopeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class CancelPermissionsRequest {

        private RequestEnvelope requestEnvelopeField;

        private string tokenField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetPermissionsResponse {

        private ResponseEnvelope responseEnvelopeField;

        private string[] scopeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scope", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetPermissionsRequest {

        private RequestEnvelope requestEnvelopeField;

        private string tokenField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetAccessTokenResponse {

        private ResponseEnvelope responseEnvelopeField;

        private string[] scopeField;

        private string tokenField;

        private string tokenSecretField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scope", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenSecret {
            get {
                return this.tokenSecretField;
            }
            set {
                this.tokenSecretField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class GetAccessTokenRequest {

        private RequestEnvelope requestEnvelopeField;

        private string tokenField;

        private string verifierField;

        private string subjectAliasField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RequestEnvelope requestEnvelope {
            get {
                return this.requestEnvelopeField;
            }
            set {
                this.requestEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string verifier {
            get {
                return this.verifierField;
            }
            set {
                this.verifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subjectAlias {
            get {
                return this.subjectAliasField;
            }
            set {
                this.subjectAliasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://svcs.paypal.com/types/perm")]
    public partial class RequestPermissionsResponse {

        private ResponseEnvelope responseEnvelopeField;

        private string tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResponseEnvelope responseEnvelope {
            get {
                return this.responseEnvelopeField;
            }
            set {
                this.responseEnvelopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void RequestPermissionsCompletedEventHandler(object sender, RequestPermissionsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal RequestPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public RequestPermissionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestPermissionsResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAccessTokenCompletedEventHandler(object sender, GetAccessTokenCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal GetAccessTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public GetAccessTokenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAccessTokenResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetPermissionsCompletedEventHandler(object sender, GetPermissionsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal GetPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public GetPermissionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPermissionsResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CancelPermissionsCompletedEventHandler(object sender, CancelPermissionsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal CancelPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public CancelPermissionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelPermissionsResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetBasicPersonalDataCompletedEventHandler(object sender, GetBasicPersonalDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBasicPersonalDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal GetBasicPersonalDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public GetBasicPersonalDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetBasicPersonalDataResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAdvancedPersonalDataCompletedEventHandler(object sender, GetAdvancedPersonalDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdvancedPersonalDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal GetAdvancedPersonalDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public GetAdvancedPersonalDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAdvancedPersonalDataResponse)(this.results[0]));
            }
        }
    }
}
