IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ExternalNodesToBeResetList]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ExternalNodesToBeResetList]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].ExternalNodesToBeResetList
      @pEntityType [nvarchar](100)
AS

BEGIN

SELECT
    STRATEGYENGINE_EXECUTIONSTATE.ID,
    STRATEGYENGINE_EXECUTIONSTATE.CURRENTNODEID NODEID,
    STRATEGYENGINE_EXECUTIONSTATE.APPLICATIONID,
    APPLICATION_APPLICATION.CREATORUSERID,
    APPLICATION_APPLICATION.VERSION
FROM
    STRATEGYENGINE_EXECUTIONSTATE
    INNER JOIN APPLICATION_APPLICATION
        ON STRATEGYENGINE_EXECUTIONSTATE.APPLICATIONID = APPLICATION_APPLICATION.APPLICATIONID
    INNER JOIN EntityLink
        ON APPLICATION_APPLICATION.StrategyId = EntityLink.EntityId 
WHERE  EntityLink.EntityType = @pEntityType
  AND (EntityLink.IsDeleted = 0 OR EntityLink.IsDeleted is null) 
  AND (EntityLink.IsApproved = 1);
END
GO
