IF OBJECT_ID('EzTvIsChanged') IS NULL
	EXECUTE('CREATE PROCEDURE EzTvIsChanged AS SELECT 1')
GO

IF(SELECT Value FROM ConfigurationVariables WHERE Name='Environment')='Prod'
BEGIN
	SELECT   OBJECT_NAME(OBJECT_ID) AS 'Table', 
	         LAST_VALUE AS 'Val'
	FROM     SYS.IDENTITY_COLUMNS 
	WHERE OBJECT_ID IN (93959411,1618104805,1845581613)
END
ELSE
BEGIN
	SELECT   OBJECT_NAME(OBJECT_ID) AS 'Table', 
	         LAST_VALUE AS 'Val'
	FROM     SYS.IDENTITY_COLUMNS 
	WHERE OBJECT_NAME(OBJECT_ID) IN ('Loan', 'Security_User', 'CashRequests')
END
GO
