SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('NL_Exists') IS NULL
	EXECUTE('CREATE PROCEDURE NL_Exists AS SELECT 0')
GO

ALTER PROCEDURE NL_Exists
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NlExists = CONVERT(BIT, CASE WHEN OBJECT_ID('NL_CashRequests') IS NULL THEN 0 ELSE 1 END)
END
GO
