SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('SaveCallCreditData') IS NOT NULL
	DROP PROCEDURE SaveCallCreditData
GO

IF TYPE_ID('CallCreditDataList') IS NOT NULL
	DROP TYPE CallCreditDataList
GO

CREATE TYPE CallCreditDataList AS TABLE (
	[CallCreditID] BIGINT NULL,
	[OiaID] INT NULL,
	[ReportType] NVARCHAR(1) NULL,
	[TpOptOut] BIT NULL,
	[AutoSearchMaxExceeded] BIT NULL,
	[AgeFlag] INT NULL,
	[ReporTitle] NVARCHAR(500) NULL,
	[CurrentInsolvment] BIT NULL,
	[Restricted] BIT NULL,
	[TotalDischarged] INT NULL,
	[TotalMinPayments12Month] INT NULL,
	[TotalMinPayments36Month] INT NULL,
	[TotalValueCashAdvances12Month] INT NULL,
	[TotalValueCashAdvances36Month] INT NULL,
	[TotalCifas] INT NULL,
	[ImpairedCredit] BIT NULL,
	[Secured] BIT NULL,
	[Unsecured] BIT NULL,
	[Judgment] BIT NULL,
	[Iva] BIT NULL,
	[Boss] BIT NULL,
	[BalanceLimitRatioVolve] BIGINT NOT NULL,
	[TotalBalancesActive] BIGINT NOT NULL,
	[TotalBalancesLoans] BIGINT NOT NULL,
	[TotalBalancesMortgage] BIGINT NOT NULL,
	[TotalBalancesRevolve] BIGINT NOT NULL,
	[TotalLimitsRevolve] BIGINT NOT NULL,
	[Total] INT NULL,
	[TotalActive] INT NULL,
	[Total36m] INT NULL,
	[TotalSatisfied] INT NULL,
	[TotalActiveAmount] INT NULL,
	[TotalSatisfiedAmount] INT NULL,
	[TotalUndecAddresses] INT NULL,
	[TotalUndecAddressesSearched] INT NULL,
	[TotalUndecAddressesUnsearched] INT NULL,
	[TotalUndecAliases] INT NULL,
	[TotalUndecAssociates] INT NULL,
	[HasUpdates] BIT NULL,
	[TotalHomeCreditSearches3Months] INT NULL,
	[TotalSearches3Months] INT NULL,
	[TotalSearches12Months] INT NULL,
	[TotalAccounts] INT NULL,
	[TotalActiveAccs] INT NULL,
	[TotalSettledAccs] INT NULL,
	[TotalOpened6Month] INT NULL,
	[WorstPayStatus12Month] NVARCHAR(10) NULL,
	[WorstPayStatus36Month] NVARCHAR(10) NULL,
	[TotalDelinqs12Month] INT NULL,
	[TotalDefaults12Month] INT NULL,
	[TotalDefaults36Month] INT NULL,
	[MessageCode] INT NULL,
	[PafValid] BIT NULL,
	[RollingRoll] BIT NULL,
	[AlertDecision] INT NULL,
	[AlertReview] INT NULL,
	[Hho] INT NULL,
	[NocFlag] BIT NULL,
	[TotalDisputes] INT NULL,
	[PersonName] NVARCHAR(164) NULL,
	[Dob] DATETIME NULL,
	[CurrentAddressP] BIT NULL,
	[UnDeclaredAddressTypeP] INT NULL,
	[AddressValueP] NVARCHAR(440) NULL,
	[number] NVARCHAR(8) NULL,
	[CompanyName] NVARCHAR(70) NULL,
	[CurrentAddressC] BIT NULL,
	[UnDeclaredAddressTypeC] INT NULL,
	[ValueC] NVARCHAR(440) NULL,
	[MemberNumber] INT NULL,
	[CaseReferenceNo] NVARCHAR(6) NULL,
	[NameDetails] NVARCHAR(100) NULL,
	[ProductCode] NVARCHAR(10) NULL,
	[FraudCategory] NVARCHAR(10) NULL,
	[ProductDesc] NVARCHAR(150) NULL,
	[FraudDesc] NVARCHAR(50) NULL,
	[InputDate] DATETIME NULL,
	[ExpiryDate] DATETIME NULL,
	[TransactionType] NVARCHAR(10) NULL,
	[CameoUk] NVARCHAR(2) NULL,
	[CameoInvestor] NVARCHAR(2) NULL,
	[CameoIncome] NVARCHAR(2) NULL,
	[CameoUnemployment] NVARCHAR(2) NULL,
	[CameoProperty] NVARCHAR(2) NULL,
	[CameoFinance] NVARCHAR(2) NULL,
	[CameoUkFam] NVARCHAR(2) NULL,
	[Ind_adult1] INT NULL,
	[Adult_1] INT NULL,
	[Adults_2] INT NULL,
	[Adult_3pl] INT NULL,
	[Age0_17] INT NULL,
	[Age18_24] INT NULL,
	[Age25_34] INT NULL,
	[Age35_44] INT NULL,
	[Age45_54] INT NULL,
	[Age55_64] INT NULL,
	[Age65_74] INT NULL,
	[Age75pl] INT NULL,
	[Unem_prob] FLOAT NULL,
	[Unem_index] INT NULL,
	[Wk_fem_ind] INT NULL,
	[Stu_ind] INT NULL,
	[Sick_ind] INT NULL,
	[Degree_ind] INT NULL,
	[Ab_ind] INT NULL,
	[C1_ind] INT NULL,
	[C2_ind] INT NULL,
	[De_ind] INT NULL,
	[Cameoukhsg] NVARCHAR(2) NULL,
	[Cameoukten] NVARCHAR(2) NULL,
	[Natprice] INT NULL,
	[Regprice] INT NULL,
	[D_index] INT NULL,
	[D_r_index] INT NULL,
	[S_index] INT NULL,
	[S_r_index] INT NULL,
	[T_index] INT NULL,
	[T_r_index] INT NULL,
	[F_index] INT NULL,
	[F_r_index] INT NULL,
	[L_of_res] FLOAT NULL,
	[Move_rate] INT NULL,
	[CameoUk06] NVARCHAR(3) NULL,
	[CameoUkg06] NVARCHAR(2) NULL,
	[CameoIncome06] NVARCHAR(2) NULL,
	[CameoIncg06] NVARCHAR(1) NULL,
	[CameoInvestor06] NVARCHAR(2) NULL,
	[CameoInvg06] NVARCHAR(1) NULL,
	[CameoProperty06] NVARCHAR(2) NULL,
	[CameoFinance06] NVARCHAR(2) NULL,
	[CameoFing06] NVARCHAR(1) NULL,
	[CameoUnemploy06] NVARCHAR(2) NULL,
	[AgeScore] FLOAT NULL,
	[AgeBand] INT NULL,
	[TenureScore] FLOAT NULL,
	[TenureBand] INT NULL,
	[CompScore] FLOAT NULL,
	[CompBand] INT NULL,
	[EconScore] FLOAT NULL,
	[EconBand] INT NULL,
	[LifeScore] FLOAT NULL,
	[LifeBand] INT NULL,
	[Millhhld] FLOAT NULL,
	[Dirhhld] FLOAT NULL,
	[SocScore] FLOAT NULL,
	[SocBand] INT NULL,
	[OccScore] FLOAT NULL,
	[OccBand] INT NULL,
	[MortScore] FLOAT NULL,
	[MortBand] INT NULL,
	[HhldShare] FLOAT NULL,
	[AvNumHold] FLOAT NULL,
	[AvNumShares] FLOAT NULL,
	[AvNumComps] FLOAT NULL,
	[AvValShares] FLOAT NULL,
	[UnemMalelt] FLOAT NULL,
	[Unem1824] FLOAT NULL,
	[Unem2539] FLOAT NULL,
	[Unem40pl] FLOAT NULL,
	[UnemScore] FLOAT NULL,
	[UnemBal] INT NULL,
	[UnemRate] FLOAT NULL,
	[UnemDiff] FLOAT NULL,
	[UnemInd] INT NULL,
	[Unemall] FLOAT NULL,
	[UnemallIndex] INT NULL,
	[HousAge] NVARCHAR(5) NULL,
	[HhldDensity] FLOAT NULL,
	[CtaxBand] NVARCHAR(1) NULL,
	[LocationType] INT NULL,
	[NatAvgHouse] INT NULL,
	[HouseScore] FLOAT NULL,
	[HouseBand] INT NULL,
	[PriceDiff] BIGINT NOT NULL,
	[PriceIndex] INT NULL,
	[Activity] INT NULL,
	[RegionalBand] INT NULL,
	[AvgDetVal] INT NULL,
	[AvgDetIndex] INT NULL,
	[AvgSemiVal] INT NULL,
	[AvgSemiIndex] INT NULL,
	[AvgTerrVal] INT NULL,
	[AvgTerrIndex] INT NULL,
	[AvgFlatVal] INT NULL,
	[AvgFlatIndex] INT NULL,
	[RegionCode] INT NULL,
	[CameoIntl] NVARCHAR(2) NULL
)
GO

CREATE PROCEDURE SaveCallCreditData
@Tbl CallCreditDataList READONLY
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CallCreditDataId BIGINT
	DECLARE @c INT

	SELECT @c = COUNT(*) FROM @Tbl

	IF @c = 0
		RAISERROR('Invalid argument: no/too much data to insert into SaveCallCreditData table.', 11, 1)

	INSERT INTO CallCreditData (
		[CallCreditID],
		[OiaID],
		[ReportType],
		[TpOptOut],
		[AutoSearchMaxExceeded],
		[AgeFlag],
		[ReporTitle],
		[CurrentInsolvment],
		[Restricted],
		[TotalDischarged],
		[TotalMinPayments12Month],
		[TotalMinPayments36Month],
		[TotalValueCashAdvances12Month],
		[TotalValueCashAdvances36Month],
		[TotalCifas],
		[ImpairedCredit],
		[Secured],
		[Unsecured],
		[Judgment],
		[Iva],
		[Boss],
		[BalanceLimitRatioVolve],
		[TotalBalancesActive],
		[TotalBalancesLoans],
		[TotalBalancesMortgage],
		[TotalBalancesRevolve],
		[TotalLimitsRevolve],
		[Total],
		[TotalActive],
		[Total36m],
		[TotalSatisfied],
		[TotalActiveAmount],
		[TotalSatisfiedAmount],
		[TotalUndecAddresses],
		[TotalUndecAddressesSearched],
		[TotalUndecAddressesUnsearched],
		[TotalUndecAliases],
		[TotalUndecAssociates],
		[HasUpdates],
		[TotalHomeCreditSearches3Months],
		[TotalSearches3Months],
		[TotalSearches12Months],
		[TotalAccounts],
		[TotalActiveAccs],
		[TotalSettledAccs],
		[TotalOpened6Month],
		[WorstPayStatus12Month],
		[WorstPayStatus36Month],
		[TotalDelinqs12Month],
		[TotalDefaults12Month],
		[TotalDefaults36Month],
		[MessageCode],
		[PafValid],
		[RollingRoll],
		[AlertDecision],
		[AlertReview],
		[Hho],
		[NocFlag],
		[TotalDisputes],
		[PersonName],
		[Dob],
		[CurrentAddressP],
		[UnDeclaredAddressTypeP],
		[AddressValueP],
		[number],
		[CompanyName],
		[CurrentAddressC],
		[UnDeclaredAddressTypeC],
		[ValueC],
		[MemberNumber],
		[CaseReferenceNo],
		[NameDetails],
		[ProductCode],
		[FraudCategory],
		[ProductDesc],
		[FraudDesc],
		[InputDate],
		[ExpiryDate],
		[TransactionType],
		[CameoUk],
		[CameoInvestor],
		[CameoIncome],
		[CameoUnemployment],
		[CameoProperty],
		[CameoFinance],
		[CameoUkFam],
		[Ind_adult1],
		[Adult_1],
		[Adults_2],
		[Adult_3pl],
		[Age0_17],
		[Age18_24],
		[Age25_34],
		[Age35_44],
		[Age45_54],
		[Age55_64],
		[Age65_74],
		[Age75pl],
		[Unem_prob],
		[Unem_index],
		[Wk_fem_ind],
		[Stu_ind],
		[Sick_ind],
		[Degree_ind],
		[Ab_ind],
		[C1_ind],
		[C2_ind],
		[De_ind],
		[Cameoukhsg],
		[Cameoukten],
		[Natprice],
		[Regprice],
		[D_index],
		[D_r_index],
		[S_index],
		[S_r_index],
		[T_index],
		[T_r_index],
		[F_index],
		[F_r_index],
		[L_of_res],
		[Move_rate],
		[CameoUk06],
		[CameoUkg06],
		[CameoIncome06],
		[CameoIncg06],
		[CameoInvestor06],
		[CameoInvg06],
		[CameoProperty06],
		[CameoFinance06],
		[CameoFing06],
		[CameoUnemploy06],
		[AgeScore],
		[AgeBand],
		[TenureScore],
		[TenureBand],
		[CompScore],
		[CompBand],
		[EconScore],
		[EconBand],
		[LifeScore],
		[LifeBand],
		[Millhhld],
		[Dirhhld],
		[SocScore],
		[SocBand],
		[OccScore],
		[OccBand],
		[MortScore],
		[MortBand],
		[HhldShare],
		[AvNumHold],
		[AvNumShares],
		[AvNumComps],
		[AvValShares],
		[UnemMalelt],
		[Unem1824],
		[Unem2539],
		[Unem40pl],
		[UnemScore],
		[UnemBal],
		[UnemRate],
		[UnemDiff],
		[UnemInd],
		[Unemall],
		[UnemallIndex],
		[HousAge],
		[HhldDensity],
		[CtaxBand],
		[LocationType],
		[NatAvgHouse],
		[HouseScore],
		[HouseBand],
		[PriceDiff],
		[PriceIndex],
		[Activity],
		[RegionalBand],
		[AvgDetVal],
		[AvgDetIndex],
		[AvgSemiVal],
		[AvgSemiIndex],
		[AvgTerrVal],
		[AvgTerrIndex],
		[AvgFlatVal],
		[AvgFlatIndex],
		[RegionCode],
		[CameoIntl]
	) SELECT
		[CallCreditID],
		[OiaID],
		[ReportType],
		[TpOptOut],
		[AutoSearchMaxExceeded],
		[AgeFlag],
		[ReporTitle],
		[CurrentInsolvment],
		[Restricted],
		[TotalDischarged],
		[TotalMinPayments12Month],
		[TotalMinPayments36Month],
		[TotalValueCashAdvances12Month],
		[TotalValueCashAdvances36Month],
		[TotalCifas],
		[ImpairedCredit],
		[Secured],
		[Unsecured],
		[Judgment],
		[Iva],
		[Boss],
		[BalanceLimitRatioVolve],
		[TotalBalancesActive],
		[TotalBalancesLoans],
		[TotalBalancesMortgage],
		[TotalBalancesRevolve],
		[TotalLimitsRevolve],
		[Total],
		[TotalActive],
		[Total36m],
		[TotalSatisfied],
		[TotalActiveAmount],
		[TotalSatisfiedAmount],
		[TotalUndecAddresses],
		[TotalUndecAddressesSearched],
		[TotalUndecAddressesUnsearched],
		[TotalUndecAliases],
		[TotalUndecAssociates],
		[HasUpdates],
		[TotalHomeCreditSearches3Months],
		[TotalSearches3Months],
		[TotalSearches12Months],
		[TotalAccounts],
		[TotalActiveAccs],
		[TotalSettledAccs],
		[TotalOpened6Month],
		[WorstPayStatus12Month],
		[WorstPayStatus36Month],
		[TotalDelinqs12Month],
		[TotalDefaults12Month],
		[TotalDefaults36Month],
		[MessageCode],
		[PafValid],
		[RollingRoll],
		[AlertDecision],
		[AlertReview],
		[Hho],
		[NocFlag],
		[TotalDisputes],
		[PersonName],
		[Dob],
		[CurrentAddressP],
		[UnDeclaredAddressTypeP],
		[AddressValueP],
		[number],
		[CompanyName],
		[CurrentAddressC],
		[UnDeclaredAddressTypeC],
		[ValueC],
		[MemberNumber],
		[CaseReferenceNo],
		[NameDetails],
		[ProductCode],
		[FraudCategory],
		[ProductDesc],
		[FraudDesc],
		[InputDate],
		[ExpiryDate],
		[TransactionType],
		[CameoUk],
		[CameoInvestor],
		[CameoIncome],
		[CameoUnemployment],
		[CameoProperty],
		[CameoFinance],
		[CameoUkFam],
		[Ind_adult1],
		[Adult_1],
		[Adults_2],
		[Adult_3pl],
		[Age0_17],
		[Age18_24],
		[Age25_34],
		[Age35_44],
		[Age45_54],
		[Age55_64],
		[Age65_74],
		[Age75pl],
		[Unem_prob],
		[Unem_index],
		[Wk_fem_ind],
		[Stu_ind],
		[Sick_ind],
		[Degree_ind],
		[Ab_ind],
		[C1_ind],
		[C2_ind],
		[De_ind],
		[Cameoukhsg],
		[Cameoukten],
		[Natprice],
		[Regprice],
		[D_index],
		[D_r_index],
		[S_index],
		[S_r_index],
		[T_index],
		[T_r_index],
		[F_index],
		[F_r_index],
		[L_of_res],
		[Move_rate],
		[CameoUk06],
		[CameoUkg06],
		[CameoIncome06],
		[CameoIncg06],
		[CameoInvestor06],
		[CameoInvg06],
		[CameoProperty06],
		[CameoFinance06],
		[CameoFing06],
		[CameoUnemploy06],
		[AgeScore],
		[AgeBand],
		[TenureScore],
		[TenureBand],
		[CompScore],
		[CompBand],
		[EconScore],
		[EconBand],
		[LifeScore],
		[LifeBand],
		[Millhhld],
		[Dirhhld],
		[SocScore],
		[SocBand],
		[OccScore],
		[OccBand],
		[MortScore],
		[MortBand],
		[HhldShare],
		[AvNumHold],
		[AvNumShares],
		[AvNumComps],
		[AvValShares],
		[UnemMalelt],
		[Unem1824],
		[Unem2539],
		[Unem40pl],
		[UnemScore],
		[UnemBal],
		[UnemRate],
		[UnemDiff],
		[UnemInd],
		[Unemall],
		[UnemallIndex],
		[HousAge],
		[HhldDensity],
		[CtaxBand],
		[LocationType],
		[NatAvgHouse],
		[HouseScore],
		[HouseBand],
		[PriceDiff],
		[PriceIndex],
		[Activity],
		[RegionalBand],
		[AvgDetVal],
		[AvgDetIndex],
		[AvgSemiVal],
		[AvgSemiIndex],
		[AvgTerrVal],
		[AvgTerrIndex],
		[AvgFlatVal],
		[AvgFlatIndex],
		[RegionCode],
		[CameoIntl]
	FROM @Tbl

	SET @CallCreditDataId = SCOPE_IDENTITY()

	SELECT @CallCreditDataId AS CallCreditDataId
END
GO


