SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('SaveCallCredit') IS NOT NULL
	DROP PROCEDURE SaveCallCredit
GO

IF TYPE_ID('CallCreditList') IS NOT NULL
	DROP TYPE CallCreditList
GO

CREATE TYPE CallCreditList AS TABLE (
	[MP_ServiceLogId] BIGINT NULL,
	[InsertDate] DATETIME NOT NULL,
	[CustomerId] INT NULL,
	[DirectorId] INT NULL,
	[Error] NVARCHAR(4000) NULL,
	[HasParsingError] BIT NOT NULL,
	[HasCallCreditError] BIT NOT NULL,
	[LinkType] INT NULL,
	[ReportSearchID] NVARCHAR(38) NULL,
	[PayLoadData] NVARCHAR(4000) NULL,
	[YourReference] NVARCHAR(50) NULL,
	[Token] NVARCHAR(64) NULL,
	[SchemaVersionCR] NVARCHAR(5) NULL,
	[DataSetsCR] INT NULL,
	[Score] BIT NULL,
	[Purpose] NVARCHAR(10) NULL,
	[CreditType] NVARCHAR(10) NULL,
	[BalorLim] INT NULL,
	[Term] NVARCHAR(10) NULL,
	[Transient] BIT NULL,
	[AutoSearch] BIT NULL,
	[AutoSearchMaximum] INT NULL,
	[UniqueSearchID] NVARCHAR(38) NULL,
	[CastInfo] NVARCHAR(1000) NULL,
	[PSTV] INT NULL,
	[LS] INT NULL,
	[SearchDate] DATETIME NULL,
	[SchemaVersionLR] NVARCHAR(5) NULL,
	[DataSetsLR] INT NULL,
	[OrigSrchLRID] NVARCHAR(38) NULL,
	[NavLinkID] NVARCHAR(38) NULL,
	[SchemaVersionSR] NVARCHAR(5) NULL,
	[DataSetsSR] INT NULL,
	[OrigSrchSRID] NVARCHAR(38) NULL,
	[Dob] DATETIME NULL,
	[Hho] BIT NULL,
	[TpOptOut] BIT NULL,
	[CustomerStatus] NVARCHAR(10) NULL,
	[MaritalStatus] NVARCHAR(10) NULL,
	[TotalDependents] INT NULL,
	[LanguageVerbal] NVARCHAR(10) NULL,
	[Type1] NVARCHAR(10) NULL,
	[Type2] NVARCHAR(10) NULL,
	[Type3] NVARCHAR(10) NULL,
	[Type4] NVARCHAR(10) NULL,
	[AccommodationType] NVARCHAR(10) NULL,
	[PropertyValue] INT NULL,
	[MortgageBalance] INT NULL,
	[MonthlyRental] INT NULL,
	[ResidentialStatus] NVARCHAR(10) NULL,
	[Occupation] NVARCHAR(10) NULL,
	[EmploymentStatus] NVARCHAR(10) NULL,
	[ExpiryDate] DATETIME NULL,
	[EmploymentRecency] NVARCHAR(10) NULL,
	[EmployerCategory] NVARCHAR(10) NULL,
	[TimeAtCurrentEmployer] NVARCHAR(15) NULL,
	[SortCode] NVARCHAR(6) NULL,
	[AccountNumber] NVARCHAR(20) NULL,
	[TimeAtBank] NVARCHAR(15) NULL,
	[PaymentMethod] NVARCHAR(10) NULL,
	[FinanceType] NVARCHAR(10) NULL,
	[TotalDebitCards] INT NULL,
	[TotalCreditCards] INT NULL,
	[MonthlyUnsecuredAmount] INT NULL,
	[AmountPr] INT NULL,
	[TypePr] NVARCHAR(10) NULL,
	[PaymentMethodPr] NVARCHAR(10) NULL,
	[FrequencyPr] NVARCHAR(10) NULL,
	[AmountAd] INT NULL,
	[TypeAd] NVARCHAR(10) NULL,
	[PaymentMethodAd] NVARCHAR(10) NULL,
	[FrequencyAd] NVARCHAR(10) NULL
)
GO

CREATE PROCEDURE SaveCallCredit
@Tbl CallCreditList READONLY
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO CallCredit (
		[MP_ServiceLogId],
		[InsertDate],
		[CustomerId],
		[DirectorId],
		[Error],
		[HasParsingError],
		[HasCallCreditError],
		[LinkType],
		[ReportSearchID],
		[PayLoadData],
		[YourReference],
		[Token],
		[SchemaVersionCR],
		[DataSetsCR],
		[Score],
		[Purpose],
		[CreditType],
		[BalorLim],
		[Term],
		[Transient],
		[AutoSearch],
		[AutoSearchMaximum],
		[UniqueSearchID],
		[CastInfo],
		[PSTV],
		[LS],
		[SearchDate],
		[SchemaVersionLR],
		[DataSetsLR],
		[OrigSrchLRID],
		[NavLinkID],
		[SchemaVersionSR],
		[DataSetsSR],
		[OrigSrchSRID],
		[Dob],
		[Hho],
		[TpOptOut],
		[CustomerStatus],
		[MaritalStatus],
		[TotalDependents],
		[LanguageVerbal],
		[Type1],
		[Type2],
		[Type3],
		[Type4],
		[AccommodationType],
		[PropertyValue],
		[MortgageBalance],
		[MonthlyRental],
		[ResidentialStatus],
		[Occupation],
		[EmploymentStatus],
		[ExpiryDate],
		[EmploymentRecency],
		[EmployerCategory],
		[TimeAtCurrentEmployer],
		[SortCode],
		[AccountNumber],
		[TimeAtBank],
		[PaymentMethod],
		[FinanceType],
		[TotalDebitCards],
		[TotalCreditCards],
		[MonthlyUnsecuredAmount],
		[AmountPr],
		[TypePr],
		[PaymentMethodPr],
		[FrequencyPr],
		[AmountAd],
		[TypeAd],
		[PaymentMethodAd],
		[FrequencyAd]
	) SELECT
		[MP_ServiceLogId],
		[InsertDate],
		[CustomerId],
		[DirectorId],
		[Error],
		[HasParsingError],
		[HasCallCreditError],
		[LinkType],
		[ReportSearchID],
		[PayLoadData],
		[YourReference],
		[Token],
		[SchemaVersionCR],
		[DataSetsCR],
		[Score],
		[Purpose],
		[CreditType],
		[BalorLim],
		[Term],
		[Transient],
		[AutoSearch],
		[AutoSearchMaximum],
		[UniqueSearchID],
		[CastInfo],
		[PSTV],
		[LS],
		[SearchDate],
		[SchemaVersionLR],
		[DataSetsLR],
		[OrigSrchLRID],
		[NavLinkID],
		[SchemaVersionSR],
		[DataSetsSR],
		[OrigSrchSRID],
		[Dob],
		[Hho],
		[TpOptOut],
		[CustomerStatus],
		[MaritalStatus],
		[TotalDependents],
		[LanguageVerbal],
		[Type1],
		[Type2],
		[Type3],
		[Type4],
		[AccommodationType],
		[PropertyValue],
		[MortgageBalance],
		[MonthlyRental],
		[ResidentialStatus],
		[Occupation],
		[EmploymentStatus],
		[ExpiryDate],
		[EmploymentRecency],
		[EmployerCategory],
		[TimeAtCurrentEmployer],
		[SortCode],
		[AccountNumber],
		[TimeAtBank],
		[PaymentMethod],
		[FinanceType],
		[TotalDebitCards],
		[TotalCreditCards],
		[MonthlyUnsecuredAmount],
		[AmountPr],
		[TypePr],
		[PaymentMethodPr],
		[FrequencyPr],
		[AmountAd],
		[TypeAd],
		[PaymentMethodAd],
		[FrequencyAd]
	FROM @Tbl
END
GO


