IF OBJECT_ID('TestIntListType') IS NULL
	EXECUTE('CREATE PROCEDURE TestIntListType AS SELECT 1')
GO

ALTER PROCEDURE TestIntListType
@TheList IntList READONLY
AS
BEGIN
	SET NOCOUNT ON;

	SELECT Value FROM @TheList
END
GO
