IF OBJECT_ID('dbo.udfMaxDate') IS NULL
	EXECUTE('CREATE FUNCTION dbo.udfMaxDate(@a DATETIME, @b DATETIME) RETURNS DATETIME AS BEGIN RETURN NULL END')
GO

ALTER FUNCTION dbo.udfMaxDate(@a DATETIME, @b DATETIME)
RETURNS DATETIME
AS
BEGIN
	IF @a IS NULL AND @b IS NULL
		RETURN NULL

	IF @a IS NOT NULL AND @b IS NULL
		RETURN @a

	IF @a IS NULL AND @b IS NOT NULL
		RETURN @b

	IF @a > @b
		RETURN @a

	RETURN @b
END
GO
