IF OBJECT_ID('dbo.udfMaxInt') IS NULL
	EXECUTE('CREATE FUNCTION dbo.udfMaxInt(@a INT, @b INT) RETURNS INT AS BEGIN RETURN NULL END')
GO

ALTER FUNCTION dbo.udfMaxInt(@a INT, @b INT)
RETURNS INT
AS
BEGIN
	IF @a IS NULL AND @b IS NULL
		RETURN NULL

	IF @a IS NOT NULL AND @b IS NULL
		RETURN @a

	IF @a IS NULL AND @b IS NOT NULL
		RETURN @b

	IF @a > @b
		RETURN @a

	RETURN @b
END
GO
