using System;
using System.Collections.Generic;
using System.Text;

namespace com.yodlee.sampleapps.datatypes
{
    class GathererErrors
    {
        public const int STATUS_OK = 0;
        public const int STATUS_INVALID_GATHERER_REQUEST = 400;
        public const int STATUS_NO_CONNECTION = 401;
        public const int STATUS_LOGIN_FAILED = 402;
        public const int STATUS_INTERNAL_ERROR = 403;
        public const int STATUS_LOST_REQUEST = 404;
        public const int STATUS_ABORT_REQUEST = 405;
        public const int STATUS_PASSWORD_EXPIRED = 406;
        public const int STATUS_ACCOUNT_LOCKED = 407;
        public const int STATUS_DATA_EXPECTED = 408;
        public const int STATUS_SITE_UNAVILABLE = 409;
        public const int STATUS_POP3_SERVER_FAILED = 410;
        public const int STATUS_SITE_OUT_OF_BUSINESS = 411;
        public const int STATUS_SITE_APPLICATION_ERROR = 412;
        public const int STATUS_REQUIRED_FIELD_UNAVAILABLE = 413;
        public const int STATUS_NO_ACCOUNT_FOUND = 414;
        public const int STATUS_SITE_TERMINATED_SESSION = 415;
        public const int STATUS_SITE_SESSION_ALREADY_ESTABLISHED = 416;
        public const int STATUS_DATA_MODEL_NO_SUPPORT = 417;
        public const int STATUS_HTTP_DNS_ERROR = 418;
        public const int STATUS_LOGIN_NOT_COMPLETED = 419;
        public const int STATUS_SITE_MERGED_ERROR = 420;
        public const int STATUS_UNSUPPORTED_LANGUAGE_ERROR = 421;
        public const int STATUS_ACCOUNT_CANCELLED = 422;
        public const int STATUS_ACCT_INFO_UNAVAILABLE = 423;
        public const int STATUS_SITE_DOWN_FOR_MAINTENANCE = 424;
        public const int STATUS_SITE_CERTIFICATE_ERROR = 425;
        public const int STATUS_SITE_BLOCKING_ERROR = 426;
        public const int STATUS_NEW_SPLASH_PAGE = 427;
        public const int STATUS_NEW_TERMS_AND_CONDITIONS = 428;
        public const int STATUS_UPDATE_INFORMATION_ERROR = 429;
        public const int STATUS_SITE_NOT_SUPPORTED = 430;
        public const int STATUS_HTTP_FILE_NOT_FOUND_ERROR = 431;
        public const int STATUS_HTTP_INTERNAL_SERVER_ERROR = 432;
        public const int STATUS_REGISTRATION_PARTIAL_SUCCESS = 433;
        public const int STATUS_REGISTRATION_FAILED_ERROR = 434;
        public const int STATUS_REGISTRATION_INVALID_DATA = 435;
        public const int STATUS_REGISTRATION_ACCOUNT_ALREADY_REGISTERED = 436;
        public const int STATUS_REGISTRATION_TIMEOUT = 404;
        public const int UNIQUEID_FROM_DATA_SOURCE_ERROR = 475;
        public const int ACCOUNT_REQUIRED_FIELDS_NOT_SET = 476;
        public const int BILL_REQUIRED_FIELDS_NOT_SET = 477;
        public const int STATUS_DUPLICATE_BILL = 478;
        public const int STATUS_COULD_NOT_GENERATE_AUTOREGISTER_CREDENTIALS = 479;
        public const int STATUS_MAX_REGISTRATION_ATTEMPTS_EXCEEDED = 481;
        public const int STATUS_ACCOUNT_REGISTERED_ELSE_WHERE = 484;
        public const int STATUS_REGISTRATION_BOT_SUPPORTED_FOR_REGION = 485;
        public const int STATUS_REGISTRATION_NOT_SUPPORTED_FOR_REGION = 485;
        public const int STATUS_UNSUPPORTED_REGISTRATION_ACCOUNT_TYPE = 486;
        public const int REWARDS_PROGRAM_REQUIRED_FIELDS_NOT_SET = 491;
        public const int REWARDS_ACTIVITY_REQUIRED_FIELDS_NOT_SET = 492;
        public const int TAX_LOT_REQUIRED_FIELDS_NOT_SET = 493;
        public const int INVESTMENT_TRANSACTION_REQUIRED_FIELDS_NOT_SET = 494;
        public const int LOAN_TRANSACTION_REQUIRED_FIELDS_NOT_SET = 495;
        public const int CARD_TRANSACTION_REQUIRED_FIELDS_NOT_SET = 496;
        public const int BANK_TRANSACTION_REQUIRED_FIELDS_NOT_SET = 497;
        public const int HOLDING_REQUIRED_FIELDS_NOT_SET = 498;
        public const int SITE_CURRENTLY_NOT_SUPPORTED = 505;
        public const int NEW_LOGIN_INFO_REQUIRED_FOR_SITE = 506;
        public const int BETA_SITE_WORK_IN_PROGRESS = 507;
        public const int STATUS_INSTANT_REQUEST_TIMEDOUT = 508;
        public const int TOKEN_ID_INVALID = 509;
        public const int PROPERTY_RECORD_NOT_FOUND = 510;
        public const int HOME_VALUE_NOT_FOUND = 511;
        public const int NO_PAYEE_FOUND = 512;
        public const int NO_PAYEE_RETRIEVED = 513;
        public const int SOME_PAYEE_NOT_RETRIEVED = 514;
        public const int NO_PAYMENT_ACCOUNT_FOUND = 515;
        public const int NO_PAYMENT_ACCOUNT_SELECTED = 516;
        public const int GENERAL_EXCEPTION_WHILE_GATHERING_MFA_DATA = 517;
        public const int NEW_MFA_INFO_REQUIRED_FOR_AGENTS = 518;
        public const int MFA_INFO_NOT_PROVIDED_TO_YODLEE_BY_USER_FOR_AGENTS = 519;
        public const int MFA_INFO_MISMATCH_FOR_AGENTS = 520;
        public const int ENROLL_IN_MFA_AT_SITE = 521;
        public const int MFA_INFO_NOT_PROVIDED_IN_REAL_TIME_BY_USER_VIA_APP = 522;
        public const int INVALID_MFA_INFO_IN_REAL_TIME_BY_USER_VIA_APP = 523;
        public const int USER_PROVIDED_REAL_TIME_MFA_DATA_EXPIRED = 524;
        public const int MFA_INFO_NOT_PROVIDED_IN_REAL_TIME_BY_GATHERER = 525;
        public const int INVALID_MFA_INFO_OR_CREDENTIALS = 526;
        public const int STATUS_DBFILER_SUMMARY_SAVE_ERROR = 601;
        public const int STATUS_REQUEST_GENERATION_ERROR = 602;
        public const int STATUS_REQUEST_DISPATCH_ERROR = 603;
        public const int STATUS_REQUEST_GENERATION_ERROR_LOGIN_FAILURE = 604;
        public const int STATUS_REQUEST_GENERATION_ERROR_DELETED_ITEM = 605;
        public const int INPUT_INVALID_DATA = 701;
        public const int INPUT_LENGTH_ERROR = 702;
        public const int INPUT_FORMAT_ERROR = 703;
        public const int INPUT_USERNAME_ALREADY_TAKEN_ERROR = 704;
        public const int INPUT_VALUE_TOO_SMALL = 705;
        public const int INPUT_VALUE_TOO_LARGE = 706;
        public const int REFRESH_NEVER_DONE = 801;
    }
}
