-- Create table
create table DATASOURCES
(
  ID		NUMBER not null,
  NAME		VARCHAR2(255),
  DESCRIPTION	VARCHAR2(1024),
  CREATIONDATE	DATE,
  USERID	NUMBER,
  REF_CUSTYPEID	NUMBER,
  REF_ACCTYPEID	NUMBER,
  BASETABLE	VARCHAR2(30),
  IDENTITYFIELD	VARCHAR2(30),
  REFERENCEFIELD VARCHAR2(30),
  CONN_STRING	VARCHAR2(1024),
  QUERY_TEXT	VARCHAR2(1024),
  WHERECLAUSE	VARCHAR2(1024),
  ISDELETED	NUMBER,
  HISTORICALFACTTABLEIDFIELD	VARCHAR2(30)
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table DATASOURCES
  add constraint PK_DATASOURCES primary key (ID);
  
alter table DATASOURCES
  add constraint IX_DATASOURCES unique (NAME, ISDELETED);
  

