CREATE NONCLUSTERED INDEX [IX_AMO2_MarketPlaceID] ON [dbo].[MP_AmazonOrderItem2] 
(
	[MarketplaceId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_AMO2_MarketPlaceId_OS] ON [dbo].[MP_AmazonOrderItem2] 
(
	[OrderStatus] ASC,
	[MarketplaceId] ASC
)
INCLUDE ( [Id],
[AmazonOrderId],
[PurchaseDate]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_AMO2_MarketPlaceId_PD] ON [dbo].[MP_AmazonOrderItem2] 
(
	[MarketplaceId] ASC
)
INCLUDE ( [AmazonOrderId],
[PurchaseDate]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_AMO2_MarketPlaceId_PD2] ON [dbo].[MP_AmazonOrderItem2] 
(
	[AmazonOrderId] ASC,
	[MarketplaceId] ASC
)
INCLUDE ( [PurchaseDate]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
