ALTER TABLE dbo.Loan ADD
	AgreementModel nvarchar(MAX) NULL
GO

CREATE TABLE dbo.LoanAgreement
	(
	Id int NOT NULL,
	Name nvarchar(200) NOT NULL,
	Template nvarchar(MAX) NOT NULL,
	LoanId int NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.LoanAgreement ADD CONSTRAINT
	PK_LoanAgreement PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX IX_LoanAgreement_Loan ON dbo.LoanAgreement
	(
	LoanId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO