
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LOAN_CustId') 
BEGIN
	DROP INDEX Loan.IX_LOAN_CustId
END
GO

DECLARE @NumericScale INT
SELECT @NumericScale = NUMERIC_SCALE FROM INFORMATION_SCHEMA.COLUMNS IC WHERE TABLE_NAME = 'Loan' AND COLUMN_NAME = 'Balance'
IF @NumericScale = 0
BEGIN
	ALTER TABLE Loan ALTER COLUMN Balance NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Repayments NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Late30 NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Late60 NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Late90 NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN PastDues NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN NextRepayment NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Interest NUMERIC(18,2)
	ALTER TABLE Loan ALTER COLUMN Late90Plus NUMERIC(18,2)
END
GO

CREATE INDEX IX_LOAN_CustId
	ON dbo.Loan (CustomerId, Balance)
GO
