DECLARE @NumericScale INT
SELECT @NumericScale = NUMERIC_SCALE FROM INFORMATION_SCHEMA.COLUMNS IC WHERE TABLE_NAME = 'LoanSchedule' AND COLUMN_NAME = 'InterestRate'

IF @NumericScale = 4
BEGIN
	ALTER TABLE LoanSchedule ALTER COLUMN InterestRate NUMERIC(18,7)
END
GO

