CREATE TABLE dbo.MP_EKMAccount
    (
    Id int NOT NULL,
    CustomerId int NOT NULL,
    Login nvarchar(250) NULL,
    Password nvarchar(250) NULL
    )  ON [PRIMARY]
GO
ALTER TABLE dbo.MP_EKMAccount ADD CONSTRAINT
    PK_MP_EKMAccount PRIMARY KEY CLUSTERED 
    (
    Id
    ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.MP_EKMAccount SET (LOCK_ESCALATION = TABLE)
GO