INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('HSBC Bank (UK)', 4567)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('HSBC Business Bank (UK)', 17583)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('HSBC Private Bank (UK)', 12279)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Barclays (Pin Sentry Users) (UK)', 4721)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Barclays (Basic Access) (UK)', 18539)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Barclays Business Bank (UK)', 19302)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Lloyds TSB Business Banking (UK)', 16284)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Lloyds TSB (UK)', 4495)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Royal Bank of Scotland Offshore Digital Banking (UK)', 19505)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Royal Bank of Scotland (UK)', 13203)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Santander (UK)', 4416)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('Santander Business Banking (UK)', 20344)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('NatWest Bank Business Bankline (UK)', 19008)
INSERT INTO YodleeBanks (Name, ContentServiceId) VALUES ('NatWest Bank (UK)', 10249)
GO
