IF NOT EXISTS (SELECT * FROM syscolumns WHERE id = OBJECT_ID('Director') AND name = 'Email')
BEGIN
	ALTER TABLE Director ADD Email NVARCHAR(128) NOT NULL CONSTRAINT DF_Director_Email DEFAULT('')
	ALTER TABLE Director ADD Phone NVARCHAR(50) NOT NULL CONSTRAINT DF_Director_Phone DEFAULT('')
END
GO
