ALTER TABLE YodleeBanks
ADD [Image] BIT NOT NULL 
CONSTRAINT DF_YodleeBanks_Image DEFAULT 1

GO

INSERT INTO YodleeBanks Values('AA (UK) - Savings',19538,'',1,0)
INSERT INTO YodleeBanks Values('Adam & Company (UK)',15821,'',1,0)
INSERT INTO YodleeBanks Values('Alliance & Leicester (UK) - MyBankOffshore',19507,'',1,0)
INSERT INTO YodleeBanks Values('Allied Irish Bank (Ireland)',9990,'',1,0)
INSERT INTO YodleeBanks Values('Allied Irish Bank (UK) - Business',19317,'',1,0)
INSERT INTO YodleeBanks Values('Bank of Ireland (Ireland)',18217,'',1,0)
INSERT INTO YodleeBanks Values('Bank of Ireland (UK)',11916,'',1,0)
INSERT INTO YodleeBanks Values('Bank of Scotland (UK) Internet - Business',19346,'',1,0)
INSERT INTO YodleeBanks Values('BM Savings (UK)',18283,'',1,0)
INSERT INTO YodleeBanks Values('Bradford & Bingley (UK)',19550,'',1,0)
INSERT INTO YodleeBanks Values('Cahoot (UK)',4459,'',1,0)
INSERT INTO YodleeBanks Values('Cater Allen (UK) - Banking',19456,'',1,0)
INSERT INTO YodleeBanks Values('Cater Allen (UK) - Business',19457,'',1,0)
INSERT INTO YodleeBanks Values('Citibank Internet Banking (UK)',4665,'',1,0)
INSERT INTO YodleeBanks Values('Clydesdale Bank (UK)',11918,'',1,0)
INSERT INTO YodleeBanks Values('Coutts (UK) - Online Banking',16275,'',1,0)
INSERT INTO YodleeBanks Values('Coventry Building Society (UK)',18286,'',1,0)
INSERT INTO YodleeBanks Values('Derbyshire Building Society (UK)',19533,'',1,0)
INSERT INTO YodleeBanks Values('FairFX (UK)',19554,'',1,0)
INSERT INTO YodleeBanks Values('First Direct (UK)',4848,'',1,0)
INSERT INTO YodleeBanks Values('First Trust Bank (UK)',11905,'',1,0)
INSERT INTO YodleeBanks Values('First Trust Bank (UK) - iBusiness',19410,'',1,0)
INSERT INTO YodleeBanks Values('ICICI Bank (UK)',13668,'',1,0)
INSERT INTO YodleeBanks Values('ICICI Bank (UK) - Business',19354,'',1,0)
INSERT INTO YodleeBanks Values('Barclays Direct( formerly ING Direct) (UK))',16265,'Barclays',1,1)
INSERT INTO YodleeBanks Values('Intelligent Finance (UK)',11890,'',1,0)
INSERT INTO YodleeBanks Values('Investec.com (UK)',19357,'',1,0)
INSERT INTO YodleeBanks Values('Leeds Building Society (UK)',16514,'',1,0)
INSERT INTO YodleeBanks Values('Lloyds TSB Offshore (UK) International',16445,'Lloyds',1,1)
INSERT INTO YodleeBanks Values('Merrill Lynch HSBC (UK) - Banking',9856,'',1,0)
INSERT INTO YodleeBanks Values('Metro Bank (UK)',19540,'',1,0)
INSERT INTO YodleeBanks Values('Newcastle Building Society (UK)',19262,'',1,0)
INSERT INTO YodleeBanks Values('Virgin Money (Northern Rock) (UK)',11989,'',1,0)
INSERT INTO YodleeBanks Values('Norwich and Peterborough BS (UK)',19290,'',1,0)
INSERT INTO YodleeBanks Values('NS&I (UK)',19529,'',1,0)
INSERT INTO YodleeBanks Values('Post Office (UK) - Savings ( Post Office (UK))',19343,'',1,0)
INSERT INTO YodleeBanks Values('Principality Building Society (UK)',19377,'',1,0)
INSERT INTO YodleeBanks Values('Royal Bank of Scotland (UK) - Business Bankline',18920,'',1,0)
INSERT INTO YodleeBanks Values('Royal Bank of Scotland (UK) - Business Digital',18925,'',1,0)
INSERT INTO YodleeBanks Values('Saffron Building Society (UK)',19536,'',1,0)
INSERT INTO YodleeBanks Values('Santander A&L Business Banking (UK)',19345,'Santander',1,1)
INSERT INTO YodleeBanks Values('Scottish Widows Bank (UK)',20003,'',1,0)
INSERT INTO YodleeBanks Values('Smile (UK)',5647,'',1,0)
INSERT INTO YodleeBanks Values('St James''s Place Bank (UK)',16517,'',1,0)
INSERT INTO YodleeBanks Values('Standard Life (UK)',10787,'',1,0)
INSERT INTO YodleeBanks Values('Tesco (UK) - Savings',18282,'',1,0)
INSERT INTO YodleeBanks Values('The Co-operative Bank (UK)',10781,'',1,0)
INSERT INTO YodleeBanks Values('The National Lottery (UK)',16520,'',1,0)
INSERT INTO YodleeBanks Values('The One Account (UK) - Banking',20230,'',1,0)
INSERT INTO YodleeBanks Values('The Woolwich (UK)',10773,'',1,0)
INSERT INTO YodleeBanks Values('Ulster Bank (UK)',11892,'',1,0)
INSERT INTO YodleeBanks Values('Yorkshire Bank (UK)',11849,'',1,0)
INSERT INTO YodleeBanks Values('Yorkshire Bank (UK) Offshore - Business',19405,'',1,0)
INSERT INTO YodleeBanks Values('Yorkshire Building Society (UK)',19058,'',1,0)

GO


