//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IovationLib.IovationAddAccountEvidenceNS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence")]
    public partial class AddAccountEvidenceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string moduleField;
        
        private string requestidField;
        
        private string subscriberrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("module");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
                this.RaisePropertyChanged("requestid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subscriberref {
            get {
                return this.subscriberrefField;
            }
            set {
                this.subscriberrefField = value;
                this.RaisePropertyChanged("subscriberref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence", ConfigurationName="IovationAddAccountEvidenceNS.PortType")]
    public interface PortType {
        
        // CODEGEN: Generating message contract since the operation AddAccountEvidence is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ieservice.com/dra/api/AddAccountEvidence#AddAccountEvidence", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceFault), Action="http://www.ieservice.com/dra/api/AddAccountEvidence#AddAccountEvidence", Name="AddAccountEvidenceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1 AddAccountEvidence(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ieservice.com/dra/api/AddAccountEvidence#AddAccountEvidence", ReplyAction="*")]
        System.Threading.Tasks.Task<IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1> AddAccountEvidenceAsync(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence")]
    public partial class AddAccountEvidence : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberidField;
        
        private string adminaccountnameField;
        
        private string adminpasswordField;
        
        private string accountcodeField;
        
        private string evidencetypeField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string subscriberid {
            get {
                return this.subscriberidField;
            }
            set {
                this.subscriberidField = value;
                this.RaisePropertyChanged("subscriberid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string adminaccountname {
            get {
                return this.adminaccountnameField;
            }
            set {
                this.adminaccountnameField = value;
                this.RaisePropertyChanged("adminaccountname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string adminpassword {
            get {
                return this.adminpasswordField;
            }
            set {
                this.adminpasswordField = value;
                this.RaisePropertyChanged("adminpassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string accountcode {
            get {
                return this.accountcodeField;
            }
            set {
                this.accountcodeField = value;
                this.RaisePropertyChanged("accountcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string evidencetype {
            get {
                return this.evidencetypeField;
            }
            set {
                this.evidencetypeField = value;
                this.RaisePropertyChanged("evidencetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence")]
    public partial class AddAccountEvidenceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountEvidenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence", Order=0)]
        public IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidence AddAccountEvidence;
        
        public AddAccountEvidenceRequest() {
        }
        
        public AddAccountEvidenceRequest(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidence AddAccountEvidence) {
            this.AddAccountEvidence = AddAccountEvidence;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountEvidenceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iesnare.com/dra/api/AddAccountEvidence", Order=0)]
        public IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse AddAccountEvidenceResponse;
        
        public AddAccountEvidenceResponse1() {
        }
        
        public AddAccountEvidenceResponse1(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse AddAccountEvidenceResponse) {
            this.AddAccountEvidenceResponse = AddAccountEvidenceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortTypeChannel : IovationLib.IovationAddAccountEvidenceNS.PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortTypeClient : System.ServiceModel.ClientBase<IovationLib.IovationAddAccountEvidenceNS.PortType>, IovationLib.IovationAddAccountEvidenceNS.PortType {
        
        public PortTypeClient() {
        }
        
        public PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1 IovationLib.IovationAddAccountEvidenceNS.PortType.AddAccountEvidence(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest request) {
            return base.Channel.AddAccountEvidence(request);
        }
        
        public IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse AddAccountEvidence(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidence AddAccountEvidence1) {
            IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest inValue = new IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest();
            inValue.AddAccountEvidence = AddAccountEvidence1;
            IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1 retVal = ((IovationLib.IovationAddAccountEvidenceNS.PortType)(this)).AddAccountEvidence(inValue);
            return retVal.AddAccountEvidenceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1> IovationLib.IovationAddAccountEvidenceNS.PortType.AddAccountEvidenceAsync(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest request) {
            return base.Channel.AddAccountEvidenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceResponse1> AddAccountEvidenceAsync(IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidence AddAccountEvidence) {
            IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest inValue = new IovationLib.IovationAddAccountEvidenceNS.AddAccountEvidenceRequest();
            inValue.AddAccountEvidence = AddAccountEvidence;
            return ((IovationLib.IovationAddAccountEvidenceNS.PortType)(this)).AddAccountEvidenceAsync(inValue);
        }
    }
}
