//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzBob3dPartiesTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzBob3dPartiesTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Current position&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/ck/hm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountPayerOrg1 {
            get {
                return ResourceManager.GetString("AccountPayerOrg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Current position&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/ck/hm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountPayerOrg2 {
            get {
                return ResourceManager.GetString("AccountPayerOrg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Login&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/ck/hmrc.css&quot; typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HmrcLoginHtml {
            get {
                return ResourceManager.GetString("HmrcLoginHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Security message&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/ck/hm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HmrcLoginResponse1 {
            get {
                return ResourceManager.GetString("HmrcLoginResponse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Security message&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/ck/hm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HmrcLoginResponse2 {
            get {
                return ResourceManager.GetString("HmrcLoginResponse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Services you can use&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeServices1 {
            get {
                return ResourceManager.GetString("HomeServices1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: Services you can use&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeServices2 {
            get {
                return ResourceManager.GetString("HomeServices2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;VatReturnInfos&quot;:null,&quot;TaxOfficeNumber&quot;:&quot;120/FA63318&quot;,&quot;RtiTaxYearInfo&quot;:{&quot;Months&quot;:[{&quot;DateStart&quot;:&quot;2015-04-06T00:00:00&quot;,&quot;DateEnd&quot;:&quot;2015-05-05T00:00:00&quot;,&quot;AmountPaid&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;},&quot;AmountDue&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;}},{&quot;DateStart&quot;:&quot;2015-05-06T00:00:00&quot;,&quot;DateEnd&quot;:&quot;2015-06-05T00:00:00&quot;,&quot;AmountPaid&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;},&quot;AmountDue&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;}},{&quot;DateStart&quot;:&quot;2015-06-06T00:00:00&quot;,&quot;DateEnd&quot;:&quot;2015-07-05T00:00:00&quot;,&quot;AmountPaid&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;},&quot;AmountDue&quot;:{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Result1 {
            get {
                return ResourceManager.GetString("Result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;VatReturnInfos&quot;:[{&quot;FromDate&quot;:&quot;2013-08-01T00:00:00&quot;,&quot;ToDate&quot;:&quot;2014-07-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2014-09-07T00:00:00&quot;,&quot;Period&quot;:&quot;07 14&quot;,&quot;RegistrationNumber&quot;:0,&quot;BusinessName&quot;:null,&quot;BusinessAddress&quot;:null,&quot;ReturnDetails&quot;:{&quot;VAT due in this period on sales and other outputs (Box 1)&quot;:{&quot;amount&quot;:5347.30,&quot;region&quot;:&quot;GB&quot;},&quot;VAT due in this period on acquisitions from other EC Member States (Box 2)&quot;:{&quot;amount&quot;:0.00,&quot;region&quot;:&quot;GB&quot;},&quot;Total VAT due (the sum of boxes 1 and 2) (Box 3)&quot;:{&quot;amount&quot;:5347.30,&quot;region&quot;:&quot;GB&quot;},&quot;VAT reclaim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Result2 {
            get {
                return ResourceManager.GetString("Result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Return1 {
            get {
                return ResourceManager.GetString("Return1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Return2 {
            get {
                return ResourceManager.GetString("Return2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Return3 {
            get {
                return ResourceManager.GetString("Return3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Return4 {
            get {
                return ResourceManager.GetString("Return4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Return5 {
            get {
                return ResourceManager.GetString("Return5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VatFileTraderPeriods1 {
            get {
                return ResourceManager.GetString("VatFileTraderPeriods1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;HMRC: View submitted returns&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=ISO-8859-1&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot;&gt;
        ///					&lt;meta http-equiv=&quot;Content-Script-Type&quot; content=&quot;text/javascript&quot;&gt;
        ///					&lt;script type=&quot;text/javascript&quot; src=&quot;/js/frameworkFunctions.js&quot;&gt;&lt;/script&gt;
        ///    
        ///    
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VatFileTraderPeriods2 {
            get {
                return ResourceManager.GetString("VatFileTraderPeriods2", resourceCulture);
            }
        }
    }
}
