namespace Reports.TraficReport {
	public enum Source {
		Ezbob,
		GooglePpc,
		Adroll,
		Amazon,
		Bing,
		Broker,
		Gmail,
		Ebay,
		Ekm,
		FaceBook,
		GrowTheBusiness,
		Gumtree,
		MoneyCoUk,
		GoogleRemarketing,
		Prestashop,
		SmallBusinessCoUk,
		Tamebay,
		UkBusinessForum,
		Twitter,
		MoneySupermarket,
		Seo,
		Direct,
		Other,
		Total,
		PpcPromotion,
	} // enum Source
} // namesapce
