namespace YodleeLib.datatypes
{
    enum TransactionCategory
    {
        AutomotiveExpenses = 2,
        CharitableGiving = 3,
        ChildOrDependentExpenses = 4,
        ClothingOrShoes = 5,
        Education = 6,
        Entertainment = 7,
        GasolineOrFuel = 8,
        Gifts = 9,
        Groceries = 10,
        HealthcareOrMedical = 11,
        HomeMaintenance = 12,
        HomeImprovement = 13,
        Insurance = 14,
        CableOrSatelliteServices = 15,
        OnlineServices = 16,
        Loans = 17,
        Mortgages = 18,
        OtherExpenses = 19,
        PersonalCare = 20,
        Rent = 21,
        RestaurantsOrDining = 22,
        Travel = 23,
        ServiceChargesOrFees = 24,
        ATMOrCashWithdrawals = 25,
        CreditCardPayments = 26,
        Deposits = 27,
        Transfers = 28,
        PaychecksOrSalary = 29,
        InvestmentIncome = 30,
        RetirementIncome = 31,
        OtherIncome = 32,
        Checks = 33,
        Hobbies = 34,
        OtherBills = 35,
        SecuritiesTrades = 36,
        Taxes = 37,
        TelephoneServices = 38,
        Utilities = 39,
        Savings = 40,
        RetirementContributions = 41,
        PetsOrPetCare = 42,
        Electronics = 43,
        GeneralMerchandise = 44,
        OfficeSupplies = 45,
        Consulting = 92,
        Sales = 94,
        Interest = 96,
        Services = 98,
        Advertising = 100,
        BusinessMiscellaneous = 102,
        PostageandShipping = 104,
        Printing = 106,
        DuesandSubscriptions = 108,
        OfficeMaintenance = 110,
        WagesPaid = 112,
    }
}
