CREATE TABLESPACE TS_SCORTO_INDX
DATAFILE 'D:\lang\oracle\oradata\alexeyb\ts_scorto_indx.ora'
SIZE 10M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TS_SCORTO_TAB
DATAFILE 'D:\lang\oracle\oradata\alexeyb\ts_scorto_tab.ora'
SIZE 10M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/