ALTER TABLE ExperianLtdDL65 ALTER COLUMN AmountSecured NVARCHAR(4000) NULL
GO

ALTER TABLE ExperianLtdDL65 ALTER COLUMN RestrictingProvisions NVARCHAR(4000) NULL
GO

ALTER TABLE ExperianLtdDL65 ALTER COLUMN AlterationsToTheOrder NVARCHAR(4000) NULL
GO
