namespace EzBobTest {
	using System;
	using CallCreditLib;
	using Callcredit.CRBSB;
	using ExperianLib.Tests.Integration;
	using Ezbob.Backend.ModelsWithDB.CallCredit.CallCreditData;
	using Ezbob.Backend.Strategies;
	using NUnit.Framework;
	using Ezbob.Backend.Strategies.CallCreditStrategy;
	using EzServiceAccessor;
	using EzServiceShortcut;
	using StructureMap;
	using ExperianLib.EBusiness;
	using Ezbob.Backend.Strategies.Experian;
	using Ezbob.Database;
	using Ezbob.Logger;

	[TestFixture]
	public class TestCallCredit : BaseTest {
		[SetUp]
		public void Init() {
			Library.Initialize(this.oLog4NetCfg.Environment, this.m_oDB, this.m_oLog);
		} // Init

		[Test]
		
		public CT_SearchResult TestGetData() {
			var user = InitializeUser();
			var retrievedata = new CallCreditGetData(user);
			CT_SearchResult apiresult = retrievedata.GetSearch07a();
	/*		ParseCallCreditTest testsave = new ParseCallCreditTest(apiresult, 1);
			testsave.Execute();*/
			return null;
		}

		private static CT_searchapplicant InitializeUser() {
			CT_searchapplicant user = new CT_searchapplicant();
			
			/*user.dob = new DateTime(1910, 01, 01);
			user.title = "MISS";
			user.forename = "JULIA";
			user.othernames = "";
			user.surname = "AUDI";
			user.buildingno = "1";
			user.street = "TOP GEAR LANE";
			user.postcode = "X9 9LF";*/
			
			/*user.dob = new DateTime(1960, 11, 05);
			user.name[0].title = "MR";
			user.name[0].forename = "OSCAR";
			user.name[0].othernames = "TEST-PERSON";
			user.name[0].surname = "MANX";
			user.address[0].buildingno = "606";
			user.address[0].street1 = "ALLEY CAT LANE";
			user.address[0].postcode = "X9 9AA";
			user.tpoptout = 0;
			user.tpoptoutSpecified = true;
*/
			/* Create a new request applicant object and attach it to the credit request object. */
			CT_searchapplicant apiApplicant = new CT_searchapplicant();
			apiApplicant.dob = new DateTime(1960, 11, 05);
			apiApplicant.dobSpecified = true;
			apiApplicant.tpoptout = 0;
			apiApplicant.tpoptoutSpecified = true;

			/* Create a new name object and attach it to the request applicant object. */
			CT_inputname apiName = new CT_inputname();
			apiName.title = "MR";
			apiName.forename = "OSCAR";
			apiName.othernames = "TEST-PERSON";
			apiName.surname = "MANX";

			apiApplicant.name = new CT_inputname[] { apiName };

			/* Create a new input current address object */
			CT_inputaddress apiInputCurrentAddress = new CT_inputaddress();
			apiInputCurrentAddress.buildingno = "606";
			apiInputCurrentAddress.street1 = "ALLEY CAT LANE";
			apiInputCurrentAddress.postcode = "X9 9AA";

			apiApplicant.address = new CT_inputaddress[] { apiInputCurrentAddress };

			return apiApplicant;
		}
		
		
		

		[SetUp]
		public void init() {
			Library.Initialize(this.oLog4NetCfg.Environment, this.m_oDB, this.m_oLog);
		}

		[Test]
		//[Ignore]
		public void TestSaveToDB() {

			ParseCallCredit testsave = new ParseCallCredit(1);
			testsave.Execute();
		}


	/*	[Test]
		[Ignore]
		public void TestCallCreditBuilder() {
			var a = 5;
			a ++;

			Assert.Greater(a, 5);
			var model = new {Val = 7};

			Assert.IsNotNull(model);
			Assert.AreEqual(5, model.Val);
		}*/

		[Test]
		[Ignore]
		public void TestParseCallCredit() {
			ParseCallCredit test = new ParseCallCredit(24706);
			test.Execute();
		}



		private readonly AConnection db;
		private readonly SafeILog log;

		[Test]
		[Ignore]
		public void TestNonLimitedParser() {
			NonLimitedParser test = new NonLimitedParser(new SqlConnection(), new SafeILog(log));
			test.ParseAndStore(response, "01820769", 556, null);
		}

		[Test]
		[Ignore]
		public void TestNonLimitedParserAnother() {
			NonLimitedParser test = new NonLimitedParser(new SqlConnection(), new SafeILog(log));
			test.ParseAndStore(14832);
		}

		[Test]
		[Ignore]
		public void TestBackfillNonLimitedCompanies() {


			BackfillNonLimitedCompanies test = new BackfillNonLimitedCompanies();
			test.Execute();
		}

		[Test]
		[Ignore]
		public void TestBackfillExperianLtd() {


			BackfillExperianLtd test = new BackfillExperianLtd();
			test.Execute();
		}



		private const string response = @"<GEODS exp_cid=""YT5e"">
  <REQUEST type=""BINSIGHT"" subtype=""CALLBUR"" EXP_ExperianRef="""" success=""Y"" timestamp=""Wed, 6 May 2015 at 9:39 AM"" id=""YT5e"">
    <DK10 seq=""00"">
      <CICSREGION>CIXF    </CICSREGION>
      <MFDATE-YYYY>2015</MFDATE-YYYY>
      <MFDATE-MM>05</MFDATE-MM>
      <MFDATE-DD>6</MFDATE-DD>
      <TIME>093952</TIME>
    </DK10>
    <DK12 seq=""00"">
      <ACCESSITEMSCOUNT>008</ACCESSITEMSCOUNT>
      <ACCESSITEMS>
        <ITEMCODE>BTAR</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>BTPC</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>BTPH</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>CDEL</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>CDEN</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>CDE6</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>SHNA</ITEMCODE>
      </ACCESSITEMS>
      <ACCESSITEMS>
        <ITEMCODE>CD3L</ITEMCODE>
      </ACCESSITEMS>
    </DK12>
    <DN10 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <EARLIESTKNOWNDATE-YYYY>2012</EARLIESTKNOWNDATE-YYYY>
      <EARLIESTKNOWNDATE-MM>08</EARLIESTKNOWNDATE-MM>
      <EARLIESTKNOWNDATE-DD>7</EARLIESTKNOWNDATE-DD>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <LATESTUPDATE-YYYY>2012</LATESTUPDATE-YYYY>
      <LATESTUPDATE-MM>08</LATESTUPDATE-MM>
      <LATESTUPDATE-DD>9</LATESTUPDATE-DD>
      <NUMNOCS>00</NUMNOCS>
      <LENBUSINESSDETAILS>056</LENBUSINESSDETAILS>
      <LENPRINCIPLEACTIVITIES>01</LENPRINCIPLEACTIVITIES>
      <NUM1992SICCODES>01</NUM1992SICCODES>
      <LEN1992SICDESC>001</LEN1992SICDESC>
      <BUSINESSNAME>A POLE NEW ADVENTURE</BUSINESSNAME>
      <BUSADDR1>31 MAXWELL WAY</BUSADDR1>
      <BUSADDR2>SHEFFIELD</BUSADDR2>
      <BUSPOSTCODE>S47JP</BUSPOSTCODE>
      <SICCODES>
        <SICCODE1992>0000 </SICCODE1992>
      </SICCODES>
      <SICDESCS />
    </DN10>
    <DN12 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <MOWNSHPRANGE>N</MOWNSHPRANGE>
      <MBANKRUPTCYCOUNTOWNSHP>0</MBANKRUPTCYCOUNTOWNSHP>
      <MNOCFLAG>N</MNOCFLAG>
      <AOWNSHPRANGE>N</AOWNSHPRANGE>
      <ABANKRUPTCYCOUNTOWNSHP>0</ABANKRUPTCYCOUNTOWNSHP>
      <ANOCFLAG>N</ANOCFLAG>
    </DN12>
    <DN14 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <MOWNSHPRANGE>N</MOWNSHPRANGE>
      <MTOTJUDGCOUNT>0</MTOTJUDGCOUNT>
      <MTOTJUDGVALUE>0</MTOTJUDGVALUE>
      <MAGEMOSTRECJUDGSINCEOWNSHP>0</MAGEMOSTRECJUDGSINCEOWNSHP>
      <MVALMOSTRECJUDGSINCEOWNSHP>0</MVALMOSTRECJUDGSINCEOWNSHP>
      <MTOTJUDGCOUNTLST6MNTHS>0</MTOTJUDGCOUNTLST6MNTHS>
      <MTOTJUDGVALUELST6MNTHS>0</MTOTJUDGVALUELST6MNTHS>
      <MTOTJUDGCOUNTLST12MNTHS>0</MTOTJUDGCOUNTLST12MNTHS>
      <MTOTJUDGVALUELST12MNTHS>0</MTOTJUDGVALUELST12MNTHS>
      <MTOTJUDGCOUNTLST24MNTHS>0</MTOTJUDGCOUNTLST24MNTHS>
      <MTOTJUDGVALUELST24MNTHS>0</MTOTJUDGVALUELST24MNTHS>
      <MTOTJUDGCOUNTLST13TO24MNTHS>0</MTOTJUDGCOUNTLST13TO24MNTHS>
      <MTOTJUDGVALUELST13TO24MNTHS>0</MTOTJUDGVALUELST13TO24MNTHS>
      <MTOTJUDGCOUNTLST25TO36MNTHS>0</MTOTJUDGCOUNTLST25TO36MNTHS>
      <MTOTJUDGVALUELST25TO36MNTHS>0</MTOTJUDGVALUELST25TO36MNTHS>
      <MTOTJUDGCOUNTLST37TO48MNTHS>0</MTOTJUDGCOUNTLST37TO48MNTHS>
      <MTOTJUDGVALUELST37TO48MNTHS>0</MTOTJUDGVALUELST37TO48MNTHS>
      <MTOTJUDGCOUNTLST49TO60MNTHS>0</MTOTJUDGCOUNTLST49TO60MNTHS>
      <MTOTJUDGVALUELST49TO60MNTHS>0</MTOTJUDGVALUELST49TO60MNTHS>
      <MTOTJUDGCOUNTLST61TO72MNTHS>0</MTOTJUDGCOUNTLST61TO72MNTHS>
      <MTOTJUDGVALUELST61TO72MNTHS>0</MTOTJUDGVALUELST61TO72MNTHS>
      <MNOCFLAG>N</MNOCFLAG>
      <AOWNSHPRNGE>N</AOWNSHPRNGE>
      <ATOTJUDGCOUNT>0</ATOTJUDGCOUNT>
      <ATOTJUDGVALUE>0</ATOTJUDGVALUE>
      <AAGEMOSTRECJUDGSINCEOWNSHP>0</AAGEMOSTRECJUDGSINCEOWNSHP>
      <AVALMOSTRECJUDGSINCEOWNSHP>0</AVALMOSTRECJUDGSINCEOWNSHP>
      <ATOTJUDGCOUNTLST6MNTHS>0</ATOTJUDGCOUNTLST6MNTHS>
      <ATOTJUDGVALUELST6MNTHS>0</ATOTJUDGVALUELST6MNTHS>
      <ATOTJUDGCOUNTLST12MNTHS>0</ATOTJUDGCOUNTLST12MNTHS>
      <ATOTJUDGVALUELST12MNTHS>0</ATOTJUDGVALUELST12MNTHS>
      <ATOTJUDGCOUNTLST24MNTHS>0</ATOTJUDGCOUNTLST24MNTHS>
      <ATOTJUDGVALUELST24MNTHS>0</ATOTJUDGVALUELST24MNTHS>
      <ATOTJUDGCOUNTLST13TO24MNTHS>0</ATOTJUDGCOUNTLST13TO24MNTHS>
      <ATOTJUDGVALUELST13TO24MNTHS>0</ATOTJUDGVALUELST13TO24MNTHS>
      <ATOTJUDGCOUNTLST25TO36MNTHS>0</ATOTJUDGCOUNTLST25TO36MNTHS>
      <ATOTJUDGVALUELST25TO36MNTHS>0</ATOTJUDGVALUELST25TO36MNTHS>
      <ATOTJUDGCOUNTLST37TO48MNTHS>0</ATOTJUDGCOUNTLST37TO48MNTHS>
      <ATOTJUDGVALUELST37TO48MNTHS>0</ATOTJUDGVALUELST37TO48MNTHS>
      <ATOTJUDGCOUNTLST49TO60MNTHS>0</ATOTJUDGCOUNTLST49TO60MNTHS>
      <ATOTJUDGVALUELST49TO60MNTHS>0</ATOTJUDGVALUELST49TO60MNTHS>
      <ATOTJUDGCOUNTLST61TO72MNTHS>0</ATOTJUDGCOUNTLST61TO72MNTHS>
      <ATOTJUDGVALUELST61TO72MNTHS>0</ATOTJUDGVALUELST61TO72MNTHS>
      <ANOCFLAG>N</ANOCFLAG>
    </DN14>
    <DN16 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <MAINDATAOSOWNSHPRNGE>N</MAINDATAOSOWNSHPRNGE>
      <MNUMCCLS>0</MNUMCCLS>
      <MNOCFLAG>N</MNOCFLAG>
      <ASSOCDATAOSOWNSHPRNGE>N</ASSOCDATAOSOWNSHPRNGE>
      <ANUMCCLS>0</ANUMCCLS>
      <ANOCFLAG>N</ANOCFLAG>
    </DN16>
    <DN18 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <DATAOSOWNSHPRNGE>N</DATAOSOWNSHPRNGE>
      <NUMPREVSEARCHES3MTHS>0</NUMPREVSEARCHES3MTHS>
      <NUMPREVSEARCHES6MTHS>0</NUMPREVSEARCHES6MTHS>
      <NUMPREVSEARCHES12MTHS>0</NUMPREVSEARCHES12MTHS>
      <NOCFLAG>N</NOCFLAG>
    </DN18>
    <DN25 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <DATEOWNSHPCOMMD-YYYY>2010</DATEOWNSHPCOMMD-YYYY>
      <DATEOWNSHPCOMMD-MM>04</DATEOWNSHPCOMMD-MM>
      <DATEOWNSHPTERMD-YYYY>2015</DATEOWNSHPTERMD-YYYY>
      <DATEOWNSHPTERMD-MM>05</DATEOWNSHPTERMD-MM>
      <MNUMMNTHSPPDATA>0</MNUMMNTHSPPDATA>
      <MNUMOCCSCOMNTERMSDATA>0</MNUMOCCSCOMNTERMSDATA>
      <MNOCFLAG>N</MNOCFLAG>
      <ANOCFLAG>N</ANOCFLAG>
      <MDATAOSOWNSHPRNGE>N</MDATAOSOWNSHPRNGE>
      <ADATAOSOWNSHPRNGE>N</ADATAOSOWNSHPRNGE>
    </DN25>
    <DN36 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <NUMTELNUMBERS>0</NUMTELNUMBERS>
      <NUMFAXNUMBERS>0</NUMFAXNUMBERS>
    </DN36>
    <DN40 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <RISKSCORE>029</RISKSCORE>
      <RISKBAND>4</RISKBAND>
      <STABILITYODDS>22:1      </STABILITYODDS>
      <OVERRIDEIND>N</OVERRIDEIND>
      <TEXTCOUNT>19</TEXTCOUNT>
      <SCOREHISTORYCOUNT>6</SCOREHISTORYCOUNT>
      <RISKBANDTEXT>Above Average Risk</RISKBANDTEXT>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2014</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>11</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>29</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_RISKSCORE>29</SCOREHISTORY_RISKSCORE>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CREDITRATING>000000000000500</SCOREHISTORY_CREDITRATING>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
        <SCOREHISTORY_CREDITLIMIT>000000000000750</SCOREHISTORY_CREDITLIMIT>
      </SCOREHISTORY>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2014</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>12</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>31</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
      </SCOREHISTORY>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2015</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>01</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>31</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
      </SCOREHISTORY>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2015</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>02</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>28</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
      </SCOREHISTORY>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2015</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>03</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>31</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
      </SCOREHISTORY>
      <SCOREHISTORY>
        <SCOREHISTORY_DATE-YYYY>2015</SCOREHISTORY_DATE-YYYY>
        <SCOREHISTORY_DATE-MM>04</SCOREHISTORY_DATE-MM>
        <SCOREHISTORY_DATE-DD>30</SCOREHISTORY_DATE-DD>
        <SCOREHISTORY_OVERRIDEIND>N</SCOREHISTORY_OVERRIDEIND>
        <SCOREHISTORY_CROVERRIDE>N</SCOREHISTORY_CROVERRIDE>
        <SCOREHISTORY_CLOVERRIDE>N</SCOREHISTORY_CLOVERRIDE>
      </SCOREHISTORY>
    </DN40>
    <DN49 seq=""01"">
      <REGNUMBER>10008179</REGNUMBER>
      <NOTECOUNT>1</NOTECOUNT>
      <NOTELEN>153</NOTELEN>
      <NOTES>
        <ALERTCODE>B02</ALERTCODE>
        <ALERTHEADER>Linked Businesses</ALERTHEADER>
        <ALERTNOTE>There is a Linked Business and the data has not been incorporated into the Credit Assessment. This should be investigated further.</ALERTNOTE>
      </NOTES>
    </DN49>
    <DN73 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <KEYSEGMENT>X</KEYSEGMENT>
      <CONSENT>Y</CONSENT>
      <SEARCHTYPE>B</SEARCHTYPE>
      <NLCDSCORE>29</NLCDSCORE>
      <CREDITRATING>00000500</CREDITRATING>
      <CREDITLIMIT>00000750</CREDITLIMIT>
      <PDSCORE>0.00</PDSCORE>
      <STABILITYODDS>22:1      </STABILITYODDS>
      <RISKBAND>4</RISKBAND>
      <CDOVERRIDE>N</CDOVERRIDE>
      <CROVERRIDE>N</CROVERRIDE>
      <CLOVERRIDE>N</CLOVERRIDE>
      <CTOVERRIDE>N</CTOVERRIDE>
      <NUMPROPSSEARCHED>0</NUMPROPSSEARCHED>
      <NUMPROPSFOUND>0</NUMPROPSFOUND>
      <NUMPROPSNODATA>0</NUMPROPSNODATA>
      <NUMADDRNOTTRACED>0</NUMADDRNOTTRACED>
    </DN73>
    <DN74 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <LENRISKTEXT>19</LENRISKTEXT>
      <LENCREDITTEXT>495</LENCREDITTEXT>
      <LENCONCLUDINGTEXT>165</LENCONCLUDINGTEXT>
      <LENNOCTEXT>1</LENNOCTEXT>
      <LENPOSSRELATEDTEXT>1</LENPOSSRELATEDTEXT>
      <RISKTEXT>Above Average Risk</RISKTEXT>
      <CREDITTEXT>Although the existence of the business can be confirmed, there is no record of the business size. Based on the length of ownership entered, the business appears to have been established for over 3 years under the current management. It should be noted that any information which may be held on the same business name and address before the date entered will be ignored for scoring purposes. As no proprietor details have been entered, the score has been calculated on the business details only.</CREDITTEXT>
      <CONCLUDINGTEXT>An above average risk business; it should prove good for credit transactions to the limit assigned.  Dealings in excess of the limit may require careful monitoring.</CONCLUDINGTEXT>
    </DN74>
    <DK11 seq=""01"">
      <DEMOFLAG>N</DEMOFLAG>
      <CAISFLAG>Y</CAISFLAG>
      <PPERFUSER>N</PPERFUSER>
      <CAISSOURCE>0721</CAISSOURCE>
      <CIFASFLAG>N</CIFASFLAG>
    </DK11>
    <DM12 seq=""00"">
      <NOCCOUNT>0</NOCCOUNT>
    </DM12>
    <DK01 seq=""01"">
      <APPNAME>XML8255   </APPNAME>
      <VERSIONMAJOR>0100</VERSIONMAJOR>
      <VERSIONMINOR>0100</VERSIONMINOR>
    </DK01>
    <DK02 seq=""01"">
      <USERDEPT>0</USERDEPT>
      <VER0101END>#</VER0101END>
    </DK02>
    <DK03 seq=""01"">
      <MESSAGETYPE>NLTD</MESSAGETYPE>
      <MESSAGESUBTYPE>0006</MESSAGESUBTYPE>
      <MESSAGEID>00        </MESSAGEID>
    </DK03>
    <DK04 seq=""01"">
      <FLAGCOUNT>1</FLAGCOUNT>
      <FLAGVALUES>
        <FLAGVALUE>YCON</FLAGVALUE>
      </FLAGVALUES>
    </DK04>
    <DN01 seq=""01"">
      <NONLTDKEY>10008179</NONLTDKEY>
      <OWNSHIPYRS>05</OWNSHIPYRS>
      <OWNSHIPMTHS>01</OWNSHIPMTHS>
    </DN01>
  </REQUEST>
</GEODS>";
	}
}
