DECLARE @Length INT
	
SELECT @Length = IC.CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS IC WHERE TABLE_NAME = 'MedalCalculations' AND COLUMN_NAME = 'MedalType'
IF (@Length != 50)
BEGIN
	ALTER TABLE MedalCalculations ALTER COLUMN MedalType NVARCHAR(50)
END
GO
