DECLARE @CurrentLength INT

SELECT @CurrentLength = CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS IC WHERE TABLE_NAME = 'customer' AND COLUMN_NAME = 'ReferenceSource'
IF @CurrentLength = 200
BEGIN
	ALTER TABLE Customer ALTER COLUMN ReferenceSource NVARCHAR(1000)
END

SELECT @CurrentLength = CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS IC WHERE TABLE_NAME = 'broker' AND COLUMN_NAME = 'referredBy'
IF @CurrentLength = 255
BEGIN
	ALTER TABLE Broker ALTER COLUMN referredBy NVARCHAR(1000)
END

GO
