//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoDecisionHistoryCondition
    {
        public int Id { get; set; }
        public Nullable<int> DecisionId { get; set; }
        public Nullable<int> DecisionType { get; set; }
        public Nullable<bool> Satisfied { get; set; }
        public string Description { get; set; }
    }
}
