//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerLead
    {
        public BrokerLead()
        {
            this.BrokerLeadTokens = new HashSet<BrokerLeadToken>();
        }
    
        public int BrokerLeadID { get; set; }
        public int BrokerID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> BrokerLeadDeletedReasonID { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int BrokerLeadAddModeID { get; set; }
        public Nullable<System.DateTime> DateLastInvitationSent { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual BrokerLeadAddMode BrokerLeadAddMode { get; set; }
        public virtual BrokerLeadDeletedReason BrokerLeadDeletedReason { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BrokerLeadToken> BrokerLeadTokens { get; set; }
    }
}
