//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerInstantOfferResponse
    {
        public int Id { get; set; }
        public int BrokerInstantOfferRequestId { get; set; }
        public int ApprovedSum { get; set; }
        public int RepaymentPeriod { get; set; }
        public decimal InterestRate { get; set; }
        public int LoanTypeId { get; set; }
        public int LoanSourceId { get; set; }
        public bool UseBrokerSetupFee { get; set; }
        public bool UseSetupFee { get; set; }
    
        public virtual BrokerInstantOfferRequest BrokerInstantOfferRequest { get; set; }
        public virtual LoanSource LoanSource { get; set; }
        public virtual LoanType LoanType { get; set; }
    }
}
