//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerLeadAddMode
    {
        public BrokerLeadAddMode()
        {
            this.BrokerLeads = new HashSet<BrokerLead>();
        }
    
        public int BrokerLeadAddModeID { get; set; }
        public string BrokerLeadAddModeCode { get; set; }
        public string BrokerLeadAddMode1 { get; set; }
        public byte[] TimestampCounter { get; set; }
        public int SendEmailOnCreate { get; set; }
    
        public virtual ICollection<BrokerLead> BrokerLeads { get; set; }
    }
}
