//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowserVersion
    {
        public BrowserVersion()
        {
            this.UiEvents = new HashSet<UiEvent>();
        }
    
        public int BrowserVersionID { get; set; }
        public string BrowserVersion1 { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual ICollection<UiEvent> UiEvents { get; set; }
    }
}
