//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRequest
    {
        public CashRequest()
        {
            this.LoanLegals = new HashSet<LoanLegal>();
            this.SuggestedAmounts = new HashSet<SuggestedAmount>();
        }
    
        public long Id { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<int> IdUnderwriter { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string SystemDecision { get; set; }
        public string UnderwriterDecision { get; set; }
        public Nullable<System.DateTime> SystemDecisionDate { get; set; }
        public Nullable<System.DateTime> UnderwriterDecisionDate { get; set; }
        public Nullable<System.DateTime> EscalatedDate { get; set; }
        public Nullable<int> SystemCalculatedSum { get; set; }
        public Nullable<int> ManagerApprovedSum { get; set; }
        public string MedalType { get; set; }
        public string EscalationReason { get; set; }
        public Nullable<decimal> APR { get; set; }
        public int RepaymentPeriod { get; set; }
        public Nullable<decimal> ScorePoints { get; set; }
        public Nullable<int> ExpirianRating { get; set; }
        public Nullable<int> AnualTurnover { get; set; }
        public decimal InterestRate { get; set; }
        public int UseSetupFee { get; set; }
        public Nullable<bool> EmailSendingBanned { get; set; }
        public Nullable<int> LoanTypeId { get; set; }
        public string UnderwriterComment { get; set; }
        public Nullable<bool> HasLoans { get; set; }
        public string LoanTemplate { get; set; }
        public Nullable<int> IsLoanTypeSelectionAllowed { get; set; }
        public Nullable<int> DiscountPlanId { get; set; }
        public int LoanSourceID { get; set; }
        public Nullable<System.DateTime> OfferStart { get; set; }
        public Nullable<System.DateTime> OfferValidUntil { get; set; }
        public bool IsCustomerRepaymentPeriodSelectionAllowed { get; set; }
        public bool UseBrokerSetupFee { get; set; }
        public Nullable<int> ManualSetupFeeAmount { get; set; }
        public Nullable<decimal> ManualSetupFeePercent { get; set; }
        public Nullable<int> QuickOfferID { get; set; }
        public string Originator { get; set; }
        public Nullable<int> ApprovedRepaymentPeriod { get; set; }
    
        public virtual LoanSource LoanSource { get; set; }
        public virtual DiscountPlan DiscountPlan { get; set; }
        public virtual QuickOffer QuickOffer { get; set; }
        public virtual ICollection<LoanLegal> LoanLegals { get; set; }
        public virtual ICollection<SuggestedAmount> SuggestedAmounts { get; set; }
    }
}
