//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CciHistory
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public bool CciMark { get; set; }
    }
}
