//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyEmployeeCounts = new HashSet<CompanyEmployeeCount>();
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.Directors = new HashSet<Director>();
            this.CustomerCompanyHistories = new HashSet<CustomerCompanyHistory>();
        }
    
        public int Id { get; set; }
        public string TypeOfBusiness { get; set; }
        public string CompanyNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> TimeAtAddress { get; set; }
        public string TimeInBusiness { get; set; }
        public string BusinessPhone { get; set; }
        public Nullable<bool> PropertyOwnedByCompany { get; set; }
        public string YearsInCompany { get; set; }
        public string RentMonthLeft { get; set; }
        public Nullable<decimal> CapitalExpenditure { get; set; }
        public string ExperianRefNum { get; set; }
        public string ExperianCompanyName { get; set; }
        public string VatReporting { get; set; }
    
        public virtual ICollection<CompanyEmployeeCount> CompanyEmployeeCounts { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<Director> Directors { get; set; }
        public virtual ICollection<CustomerCompanyHistory> CustomerCompanyHistories { get; set; }
    }
}
