//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMStatus
    {
        public CRMStatus()
        {
            this.CustomerRelations = new HashSet<CustomerRelation>();
            this.CustomerRelationStates = new HashSet<CustomerRelationState>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual CRMStatusGroup CRMStatusGroup { get; set; }
        public virtual ICollection<CustomerRelation> CustomerRelations { get; set; }
        public virtual ICollection<CustomerRelationState> CustomerRelationStates { get; set; }
    }
}
