//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BrokerLeads = new HashSet<BrokerLead>();
            this.CampaignClients = new HashSet<CampaignClient>();
            this.CompanyEmployeeCounts = new HashSet<CompanyEmployeeCount>();
            this.CustomerAnalyticsCompanies = new HashSet<CustomerAnalyticsCompany>();
            this.CustomerAnalyticsDirectors = new HashSet<CustomerAnalyticsDirector>();
            this.CustomerAnalyticsLocalDatas = new HashSet<CustomerAnalyticsLocalData>();
            this.CustomerAnalyticsPersonals = new HashSet<CustomerAnalyticsPersonal>();
            this.CustomerBrokerHistories = new HashSet<CustomerBrokerHistory>();
            this.CustomerLoyaltyPrograms = new HashSet<CustomerLoyaltyProgram>();
            this.MP_CustomerMarketPlace = new HashSet<MP_CustomerMarketPlace>();
            this.Esignatures = new HashSet<Esignature>();
            this.ExperianConsentAgreements = new HashSet<ExperianConsentAgreement>();
            this.ExperianDirectors = new HashSet<ExperianDirector>();
            this.FraudDetections = new HashSet<FraudDetection>();
            this.FraudDetections1 = new HashSet<FraudDetection>();
            this.FraudRequests = new HashSet<FraudRequest>();
            this.LandRegistries = new HashSet<LandRegistry>();
            this.MP_CompanyFilesMetaData = new HashSet<MP_CompanyFilesMetaData>();
            this.MP_ExperianHistory = new HashSet<MP_ExperianHistory>();
            this.CustomerCompanyHistories = new HashSet<CustomerCompanyHistory>();
            this.SuggestedAmounts = new HashSet<SuggestedAmount>();
            this.MP_VatReturnSummary = new HashSet<MP_VatReturnSummary>();
            this.VipRequests = new HashSet<VipRequest>();
            this.WhatsNewCustomerMaps = new HashSet<WhatsNewCustomerMap>();
            this.YodleeAccounts = new HashSet<YodleeAccount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CreditResult { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public Nullable<int> GreetingMailSent { get; set; }
        public System.DateTime GreetingMailSentDate { get; set; }
        public string Status { get; set; }
        public string AccountNumber { get; set; }
        public string SortCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> TimeAtAddress { get; set; }
        public Nullable<bool> ConsentToSearch { get; set; }
        public Nullable<System.DateTime> ApplyForLoan { get; set; }
        public string MedalType { get; set; }
        public string PayPointTransactionId { get; set; }
        public Nullable<System.DateTime> DateEscalated { get; set; }
        public string UnderwriterName { get; set; }
        public string ManagerName { get; set; }
        public string EscalationReason { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApplyCount { get; set; }
        public string RejectedReason { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string TypeOfBusiness { get; set; }
        public string SystemDecision { get; set; }
        public string CreditCardNo { get; set; }
        public string DaytimePhone { get; set; }
        public string MobilePhone { get; set; }
        public string Fullname { get; set; }
        public Nullable<decimal> OverallTurnOver { get; set; }
        public Nullable<decimal> WebSiteTurnOver { get; set; }
        public string BWAResult { get; set; }
        public string AMLResult { get; set; }
        public Nullable<bool> Fraud { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> PayPointErrorsCount { get; set; }
        public Nullable<decimal> SetupFee { get; set; }
        public string Comments { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> ValidFor { get; set; }
        public int CollectionStatus { get; set; }
        public string ApprovedReason { get; set; }
        public string ReferenceSource { get; set; }
        public string EmailState { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public Nullable<int> CurrentDebitCard { get; set; }
        public string BankAccountType { get; set; }
        public Nullable<int> BankAccountValidationInvalidAttempts { get; set; }
        public string CollectionDescription { get; set; }
        public Nullable<int> WizardStep { get; set; }
        public Nullable<int> LastStartedMainStrategyId { get; set; }
        public Nullable<System.DateTime> LastStartedMainStrategyEndTime { get; set; }
        public string PendingStatus { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public Nullable<int> IsLoanTypeSelectionAllowed { get; set; }
        public string ABTesting { get; set; }
        public int NumApproves { get; set; }
        public int NumRejects { get; set; }
        public decimal SystemCalculatedSum { get; set; }
        public decimal ManagerApprovedSum { get; set; }
        public Nullable<System.DateTime> FirstLoanDate { get; set; }
        public Nullable<System.DateTime> LastLoanDate { get; set; }
        public decimal AmountTaken { get; set; }
        public decimal LastLoanAmount { get; set; }
        public decimal TotalPrincipalRepaid { get; set; }
        public string LastStatus { get; set; }
        public bool AvoidAutomaticDescison { get; set; }
        public Nullable<int> FraudStatus { get; set; }
        public Nullable<bool> IsWasLate { get; set; }
        public Nullable<bool> IsOffline { get; set; }
        public string PromoCode { get; set; }
        public Nullable<bool> MonthlyStatusEnabled { get; set; }
        public bool CciMark { get; set; }
        public string GoogleCookie { get; set; }
        public string LimitedPostcode { get; set; }
        public string NonLimitedPostcode { get; set; }
        public int TrustPilotStatusID { get; set; }
        public Nullable<bool> IsDirector { get; set; }
        public string IndustryType { get; set; }
        public Nullable<int> QuickOfferID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public bool FilledByBroker { get; set; }
        public bool Vip { get; set; }
        public bool DefaultCardSelectionAllowed { get; set; }
        public string FirstVisitTime { get; set; }
        public string AmlDescription { get; set; }
        public Nullable<int> AmlScore { get; set; }
        public Nullable<int> PropertyStatusId { get; set; }
        public Nullable<int> ExperianConsumerScore { get; set; }
        public bool MobilePhoneVerified { get; set; }
        public Nullable<int> WhiteLabelId { get; set; }
        public Nullable<bool> IsWaitingForSignature { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual ICollection<BrokerLead> BrokerLeads { get; set; }
        public virtual ICollection<CampaignClient> CampaignClients { get; set; }
        public virtual CardInfo CardInfo { get; set; }
        public virtual ICollection<CompanyEmployeeCount> CompanyEmployeeCounts { get; set; }
        public virtual CustomerStatus CustomerStatus { get; set; }
        public virtual QuickOffer QuickOffer { get; set; }
        public virtual TrustPilotStatu TrustPilotStatu { get; set; }
        public virtual WhiteLabelProvider WhiteLabelProvider { get; set; }
        public virtual WizardStepType WizardStepType { get; set; }
        public virtual ICollection<CustomerAnalyticsCompany> CustomerAnalyticsCompanies { get; set; }
        public virtual ICollection<CustomerAnalyticsDirector> CustomerAnalyticsDirectors { get; set; }
        public virtual ICollection<CustomerAnalyticsLocalData> CustomerAnalyticsLocalDatas { get; set; }
        public virtual ICollection<CustomerAnalyticsPersonal> CustomerAnalyticsPersonals { get; set; }
        public virtual ICollection<CustomerBrokerHistory> CustomerBrokerHistories { get; set; }
        public virtual CustomerInviteFriend CustomerInviteFriend { get; set; }
        public virtual ICollection<CustomerLoyaltyProgram> CustomerLoyaltyPrograms { get; set; }
        public virtual ICollection<MP_CustomerMarketPlace> MP_CustomerMarketPlace { get; set; }
        public virtual CustomerRequestedLoan CustomerRequestedLoan { get; set; }
        public virtual ICollection<Esignature> Esignatures { get; set; }
        public virtual ICollection<ExperianConsentAgreement> ExperianConsentAgreements { get; set; }
        public virtual ICollection<ExperianDirector> ExperianDirectors { get; set; }
        public virtual ICollection<FraudDetection> FraudDetections { get; set; }
        public virtual ICollection<FraudDetection> FraudDetections1 { get; set; }
        public virtual ICollection<FraudRequest> FraudRequests { get; set; }
        public virtual ICollection<LandRegistry> LandRegistries { get; set; }
        public virtual ICollection<MP_CompanyFilesMetaData> MP_CompanyFilesMetaData { get; set; }
        public virtual ICollection<MP_ExperianHistory> MP_ExperianHistory { get; set; }
        public virtual ICollection<CustomerCompanyHistory> CustomerCompanyHistories { get; set; }
        public virtual ICollection<SuggestedAmount> SuggestedAmounts { get; set; }
        public virtual ICollection<MP_VatReturnSummary> MP_VatReturnSummary { get; set; }
        public virtual ICollection<VipRequest> VipRequests { get; set; }
        public virtual ICollection<WhatsNewCustomerMap> WhatsNewCustomerMaps { get; set; }
        public virtual ICollection<YodleeAccount> YodleeAccounts { get; set; }
    }
}
