//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequestedLoan
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int CustomerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string OtherReason { get; set; }
        public Nullable<int> SourceOfRepaymentId { get; set; }
        public string OtherSourceOfRepayment { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerReason CustomerReason { get; set; }
        public virtual CustomerSourceOfRepayment CustomerSourceOfRepayment { get; set; }
    }
}
