//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRelation
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<bool> IsBroker { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual CRMAction CRMAction { get; set; }
        public virtual CRMRank CRMRank { get; set; }
        public virtual CRMStatus CRMStatus { get; set; }
    }
}
