//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReason
    {
        public CustomerReason()
        {
            this.CustomerRequestedLoans = new HashSet<CustomerRequestedLoan>();
        }
    
        public int Id { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ReasonType { get; set; }
    
        public virtual ICollection<CustomerRequestedLoan> CustomerRequestedLoans { get; set; }
    }
}
