//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public int id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Middle { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsShareholder { get; set; }
        public Nullable<bool> IsDirector { get; set; }
        public Nullable<int> ExperianConsumerScore { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
