//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esignature
    {
        public Esignature()
        {
            this.EsignatureHistories = new HashSet<EsignatureHistory>();
            this.Esigners = new HashSet<Esigner>();
        }
    
        public long EsignatureID { get; set; }
        public int CustomerID { get; set; }
        public int EsignTemplateID { get; set; }
        public string DocumentKey { get; set; }
        public System.DateTime SendDate { get; set; }
        public int StatusID { get; set; }
        public string SignedDocumentMimeType { get; set; }
        public byte[] SignedDocument { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EsignAgreementStatu EsignAgreementStatu { get; set; }
        public virtual ICollection<EsignatureHistory> EsignatureHistories { get; set; }
        public virtual EsignTemplate EsignTemplate { get; set; }
        public virtual ICollection<Esigner> Esigners { get; set; }
    }
}
