//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperianLtdLenderDetail
    {
        public long ExperianLtdLenderDetailsID { get; set; }
        public long DL65ID { get; set; }
        public string LenderName { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual ExperianLtdDL65 ExperianLtdDL65 { get; set; }
    }
}
