//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperianConsumerDataCaisBalance
    {
        public long Id { get; set; }
        public Nullable<long> ExperianConsumerDataCaisId { get; set; }
        public Nullable<int> AccountBalance { get; set; }
        public string Status { get; set; }
    
        public virtual ExperianConsumerDataCai ExperianConsumerDataCai { get; set; }
    }
}
