//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperianLtd
    {
        public ExperianLtd()
        {
            this.ExperianLtdCaisMonthlies = new HashSet<ExperianLtdCaisMonthly>();
            this.ExperianLtdCreditSummaries = new HashSet<ExperianLtdCreditSummary>();
            this.ExperianLtdDL48 = new HashSet<ExperianLtdDL48>();
            this.ExperianLtdDL52 = new HashSet<ExperianLtdDL52>();
            this.ExperianLtdDL65 = new HashSet<ExperianLtdDL65>();
            this.ExperianLtdDL68 = new HashSet<ExperianLtdDL68>();
            this.ExperianLtdDL72 = new HashSet<ExperianLtdDL72>();
            this.ExperianLtdDL97 = new HashSet<ExperianLtdDL97>();
            this.ExperianLtdDL99 = new HashSet<ExperianLtdDL99>();
            this.ExperianLtdDLA2 = new HashSet<ExperianLtdDLA2>();
            this.ExperianLtdDLB5 = new HashSet<ExperianLtdDLB5>();
            this.ExperianLtdErrors = new HashSet<ExperianLtdError>();
            this.ExperianLtdPrevCompanyNames = new HashSet<ExperianLtdPrevCompanyName>();
            this.ExperianLtdShareholders = new HashSet<ExperianLtdShareholder>();
        }
    
        public long ExperianLtdID { get; set; }
        public long ServiceLogID { get; set; }
        public string RegisteredNumber { get; set; }
        public string LegalStatus { get; set; }
        public Nullable<System.DateTime> IncorporationDate { get; set; }
        public Nullable<System.DateTime> DissolutionDate { get; set; }
        public string CompanyName { get; set; }
        public string OfficeAddress1 { get; set; }
        public string OfficeAddress2 { get; set; }
        public string OfficeAddress3 { get; set; }
        public string OfficeAddress4 { get; set; }
        public string OfficeAddressPostcode { get; set; }
        public Nullable<int> CommercialDelphiScore { get; set; }
        public string StabilityOdds { get; set; }
        public string CommercialDelphiBandText { get; set; }
        public Nullable<decimal> CommercialDelphiCreditLimit { get; set; }
        public string SameTradingAddressG { get; set; }
        public Nullable<int> LengthOf1992SICArea { get; set; }
        public string TradingPhoneNumber { get; set; }
        public string PrincipalActivities { get; set; }
        public string First1992SICCodeDescription { get; set; }
        public string BankSortcode { get; set; }
        public string BankName { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string BankAddress3 { get; set; }
        public string BankAddress4 { get; set; }
        public string BankAddressPostcode { get; set; }
        public string RegisteredNumberOfTheCurrentUltimateParentCompany { get; set; }
        public string RegisteredNameOfTheCurrentUltimateParentCompany { get; set; }
        public Nullable<int> TotalNumberOfCurrentDirectors { get; set; }
        public Nullable<int> NumberOfCurrentDirectorshipsLessThan12Months { get; set; }
        public Nullable<int> NumberOfAppointmentsInTheLast12Months { get; set; }
        public Nullable<int> NumberOfResignationsInTheLast12Months { get; set; }
        public Nullable<int> AgeOfMostRecentCCJDecreeMonths { get; set; }
        public Nullable<int> NumberOfCCJsDuringLast12Months { get; set; }
        public Nullable<decimal> ValueOfCCJsDuringLast12Months { get; set; }
        public Nullable<int> NumberOfCCJsBetween13And24MonthsAgo { get; set; }
        public Nullable<decimal> ValueOfCCJsBetween13And24MonthsAgo { get; set; }
        public Nullable<decimal> CompanyAverageDBT3Months { get; set; }
        public Nullable<decimal> CompanyAverageDBT6Months { get; set; }
        public Nullable<decimal> CompanyAverageDBT12Months { get; set; }
        public Nullable<decimal> CompanyNumberOfDbt1000 { get; set; }
        public Nullable<decimal> CompanyNumberOfDbt10000 { get; set; }
        public Nullable<decimal> CompanyNumberOfDbt100000 { get; set; }
        public Nullable<decimal> CompanyNumberOfDbt100000Plus { get; set; }
        public Nullable<decimal> IndustryAverageDBT3Months { get; set; }
        public Nullable<decimal> IndustryAverageDBT6Months { get; set; }
        public Nullable<decimal> IndustryAverageDBT12Months { get; set; }
        public Nullable<decimal> IndustryNumberOfDbt1000 { get; set; }
        public Nullable<decimal> IndustryNumberOfDbt10000 { get; set; }
        public Nullable<decimal> IndustryNumberOfDbt100000 { get; set; }
        public Nullable<decimal> IndustryNumberOfDbt100000Plus { get; set; }
        public string CompanyPaymentPattern { get; set; }
        public string IndustryPaymentPattern { get; set; }
        public string SupplierPaymentPattern { get; set; }
        public byte[] TimestampCounter { get; set; }
        public System.DateTime Created { get; set; }
        public string First1992SICCode { get; set; }
        public string First1980SICCodeDescription { get; set; }
        public string First1980SICCode { get; set; }
    
        public virtual MP_ServiceLog MP_ServiceLog { get; set; }
        public virtual ICollection<ExperianLtdCaisMonthly> ExperianLtdCaisMonthlies { get; set; }
        public virtual ICollection<ExperianLtdCreditSummary> ExperianLtdCreditSummaries { get; set; }
        public virtual ICollection<ExperianLtdDL48> ExperianLtdDL48 { get; set; }
        public virtual ICollection<ExperianLtdDL52> ExperianLtdDL52 { get; set; }
        public virtual ICollection<ExperianLtdDL65> ExperianLtdDL65 { get; set; }
        public virtual ICollection<ExperianLtdDL68> ExperianLtdDL68 { get; set; }
        public virtual ICollection<ExperianLtdDL72> ExperianLtdDL72 { get; set; }
        public virtual ICollection<ExperianLtdDL97> ExperianLtdDL97 { get; set; }
        public virtual ICollection<ExperianLtdDL99> ExperianLtdDL99 { get; set; }
        public virtual ICollection<ExperianLtdDLA2> ExperianLtdDLA2 { get; set; }
        public virtual ICollection<ExperianLtdDLB5> ExperianLtdDLB5 { get; set; }
        public virtual ICollection<ExperianLtdError> ExperianLtdErrors { get; set; }
        public virtual ICollection<ExperianLtdPrevCompanyName> ExperianLtdPrevCompanyNames { get; set; }
        public virtual ICollection<ExperianLtdShareholder> ExperianLtdShareholders { get; set; }
    }
}
