//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperianConsumerData
    {
        public ExperianConsumerData()
        {
            this.ExperianConsumerDataApplicants = new HashSet<ExperianConsumerDataApplicant>();
            this.ExperianConsumerDataCais = new HashSet<ExperianConsumerDataCai>();
            this.ExperianConsumerDataLocations = new HashSet<ExperianConsumerDataLocation>();
            this.ExperianConsumerDataNocs = new HashSet<ExperianConsumerDataNoc>();
            this.ExperianConsumerDataResidencies = new HashSet<ExperianConsumerDataResidency>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ServiceLogId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public string Error { get; set; }
        public bool HasParsingError { get; set; }
        public bool HasExperianError { get; set; }
        public Nullable<int> BureauScore { get; set; }
        public Nullable<int> CII { get; set; }
        public Nullable<int> CreditCardBalances { get; set; }
        public Nullable<int> ActiveCaisBalanceExcMortgages { get; set; }
        public Nullable<int> NumCreditCards { get; set; }
        public Nullable<int> CreditLimitUtilisation { get; set; }
        public Nullable<int> CreditCardOverLimit { get; set; }
        public string PersonalLoanStatus { get; set; }
        public string WorstStatus { get; set; }
        public string WorstCurrentStatus { get; set; }
        public string WorstHistoricalStatus { get; set; }
        public Nullable<int> TotalAccountBalances { get; set; }
        public Nullable<int> NumAccounts { get; set; }
        public Nullable<int> NumCCJs { get; set; }
        public Nullable<int> CCJLast2Years { get; set; }
        public Nullable<int> TotalCCJValue1 { get; set; }
        public Nullable<int> TotalCCJValue2 { get; set; }
        public Nullable<int> EnquiriesLast6Months { get; set; }
        public Nullable<int> EnquiriesLast3Months { get; set; }
        public Nullable<int> MortgageBalance { get; set; }
        public Nullable<System.DateTime> CaisDOB { get; set; }
        public Nullable<int> CreditCommitmentsRevolving { get; set; }
        public Nullable<int> CreditCommitmentsNonRevolving { get; set; }
        public Nullable<int> MortgagePayments { get; set; }
        public bool Bankruptcy { get; set; }
        public bool OtherBankruptcy { get; set; }
        public Nullable<int> CAISDefaults { get; set; }
        public string BadDebt { get; set; }
        public bool NOCsOnCCJ { get; set; }
        public bool NOCsOnCAIS { get; set; }
        public bool NOCAndNOD { get; set; }
        public bool SatisfiedJudgement { get; set; }
        public string CAISSpecialInstructionFlag { get; set; }
    
        public virtual MP_ServiceLog MP_ServiceLog { get; set; }
        public virtual ICollection<ExperianConsumerDataApplicant> ExperianConsumerDataApplicants { get; set; }
        public virtual ICollection<ExperianConsumerDataCai> ExperianConsumerDataCais { get; set; }
        public virtual ICollection<ExperianConsumerDataLocation> ExperianConsumerDataLocations { get; set; }
        public virtual ICollection<ExperianConsumerDataNoc> ExperianConsumerDataNocs { get; set; }
        public virtual ICollection<ExperianConsumerDataResidency> ExperianConsumerDataResidencies { get; set; }
    }
}
