//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EzServiceCronjobArgumentType
    {
        public EzServiceCronjobArgumentType()
        {
            this.EzServiceCronjobArguments = new HashSet<EzServiceCronjobArgument>();
            this.EzServiceCronjobLogArguments = new HashSet<EzServiceCronjobLogArgument>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public bool IsNullable { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual ICollection<EzServiceCronjobArgument> EzServiceCronjobArguments { get; set; }
        public virtual ICollection<EzServiceCronjobLogArgument> EzServiceCronjobLogArguments { get; set; }
    }
}
