//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EzServiceActionHistory
    {
        public long EntryID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.Guid ActionID { get; set; }
        public bool IsSync { get; set; }
        public int ActionStatusID { get; set; }
        public int CurrentThreadID { get; set; }
        public int UnderlyingThreadID { get; set; }
        public string Comment { get; set; }
        public byte[] TimestampCounter { get; set; }
        public Nullable<int> ActionNameID { get; set; }
        public Nullable<int> ServiceInstanceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual EzServiceActionStatu EzServiceActionStatu { get; set; }
        public virtual EzServiceInstance EzServiceInstance { get; set; }
        public virtual EzServiceActionName EzServiceActionName { get; set; }
    }
}
