//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EzServiceInstance
    {
        public EzServiceInstance()
        {
            this.EzServiceActionHistories = new HashSet<EzServiceActionHistory>();
            this.EzServiceDefaultInstances = new HashSet<EzServiceDefaultInstance>();
        }
    
        public int InstanceID { get; set; }
        public string InstanceName { get; set; }
        public int SleepTimeout { get; set; }
        public int AdminPort { get; set; }
        public int ClientPort { get; set; }
        public string HostName { get; set; }
        public byte[] TimestampCounter { get; set; }
        public int ClientTimeoutSeconds { get; set; }
    
        public virtual ICollection<EzServiceActionHistory> EzServiceActionHistories { get; set; }
        public virtual ICollection<EzServiceDefaultInstance> EzServiceDefaultInstances { get; set; }
    }
}
