//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraudUser
    {
        public FraudUser()
        {
            this.FraudAddresses = new HashSet<FraudAddress>();
            this.FraudBankAccounts = new HashSet<FraudBankAccount>();
            this.FraudCompanies = new HashSet<FraudCompany>();
            this.FraudDetections = new HashSet<FraudDetection>();
            this.FraudEmails = new HashSet<FraudEmail>();
            this.FraudEmailDomains = new HashSet<FraudEmailDomain>();
            this.FraudPhones = new HashSet<FraudPhone>();
            this.FraudShops = new HashSet<FraudShop>();
        }
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<FraudAddress> FraudAddresses { get; set; }
        public virtual ICollection<FraudBankAccount> FraudBankAccounts { get; set; }
        public virtual ICollection<FraudCompany> FraudCompanies { get; set; }
        public virtual ICollection<FraudDetection> FraudDetections { get; set; }
        public virtual ICollection<FraudEmail> FraudEmails { get; set; }
        public virtual ICollection<FraudEmailDomain> FraudEmailDomains { get; set; }
        public virtual ICollection<FraudPhone> FraudPhones { get; set; }
        public virtual ICollection<FraudShop> FraudShops { get; set; }
    }
}
