//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInterestFreeze
    {
        public int Id { get; set; }
        public int LoanId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal InterestRate { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
