//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanOfferMultiplier
    {
        public int Id { get; set; }
        public Nullable<int> Start { get; set; }
        public Nullable<int> End { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
