//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedalCoefficient
    {
        public int Id { get; set; }
        public string MedalFlow { get; set; }
        public string Medal { get; set; }
        public Nullable<decimal> AnnualTurnover { get; set; }
        public Nullable<decimal> ValueAdded { get; set; }
        public Nullable<decimal> FreeCashFlow { get; set; }
    }
}
