//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_AnalysisFunctionTimePeriod
    {
        public MP_AnalysisFunctionTimePeriod()
        {
            this.MP_AmazonFeedbackItem = new HashSet<MP_AmazonFeedbackItem>();
            this.MP_AnalyisisFunctionValues = new HashSet<MP_AnalyisisFunctionValues>();
            this.MP_EbayFeedbackItem = new HashSet<MP_EbayFeedbackItem>();
            this.MP_EbayRaitingItem = new HashSet<MP_EbayRaitingItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid InternalId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MP_AmazonFeedbackItem> MP_AmazonFeedbackItem { get; set; }
        public virtual ICollection<MP_AnalyisisFunctionValues> MP_AnalyisisFunctionValues { get; set; }
        public virtual ICollection<MP_EbayFeedbackItem> MP_EbayFeedbackItem { get; set; }
        public virtual ICollection<MP_EbayRaitingItem> MP_EbayRaitingItem { get; set; }
    }
}
