//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_CustomerMarketplaceUpdatingActionLog
    {
        public MP_CustomerMarketplaceUpdatingActionLog()
        {
            this.MP_CustomerMarketplaceUpdatingCounter = new HashSet<MP_CustomerMarketplaceUpdatingCounter>();
        }
    
        public long Id { get; set; }
        public Nullable<int> CustomerMarketplaceUpdatingHistoryRecordId { get; set; }
        public Nullable<System.DateTime> UpdatingStart { get; set; }
        public Nullable<System.DateTime> UpdatingEnd { get; set; }
        public string ActionName { get; set; }
        public string ControlValueName { get; set; }
        public string ControlValue { get; set; }
        public string Error { get; set; }
        public Nullable<int> UpdatingTimePassInSeconds { get; set; }
        public Nullable<long> ElapsedAggregateData { get; set; }
        public Nullable<long> ElapsedRetrieveDataFromDatabase { get; set; }
        public Nullable<long> ElapsedRetrieveDataFromExternalService { get; set; }
        public Nullable<long> ElapsedStoreAggregatedData { get; set; }
        public Nullable<long> ElapsedStoreDataToDatabase { get; set; }
    
        public virtual MP_CustomerMarketPlaceUpdatingHistory MP_CustomerMarketPlaceUpdatingHistory { get; set; }
        public virtual ICollection<MP_CustomerMarketplaceUpdatingCounter> MP_CustomerMarketplaceUpdatingCounter { get; set; }
    }
}
