//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_CustomerMarketplaceUpdatingCounter
    {
        public long Id { get; set; }
        public long CustomerMarketplaceUpdatingActionLogId { get; set; }
        public System.DateTime Created { get; set; }
        public string Method { get; set; }
        public string Details { get; set; }
    
        public virtual MP_CustomerMarketplaceUpdatingActionLog MP_CustomerMarketplaceUpdatingActionLog { get; set; }
    }
}
