//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_Currency
    {
        public MP_Currency()
        {
            this.MP_CurrencyRateHistory = new HashSet<MP_CurrencyRateHistory>();
            this.MP_PayPalTransactionItem2 = new HashSet<MP_PayPalTransactionItem2>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<MP_CurrencyRateHistory> MP_CurrencyRateHistory { get; set; }
        public virtual ICollection<MP_PayPalTransactionItem2> MP_PayPalTransactionItem2 { get; set; }
    }
}
