//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_CurrencyRateHistory
    {
        public long Id { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual MP_Currency MP_Currency { get; set; }
    }
}
