//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_EbayAmazonCategory
    {
        public MP_EbayAmazonCategory()
        {
            this.MP_AmazonOrderItemDetailCatgory = new HashSet<MP_AmazonOrderItemDetailCatgory>();
            this.MP_EbayAmazonCategory1 = new HashSet<MP_EbayAmazonCategory>();
            this.MP_EBayOrderItemDetail = new HashSet<MP_EBayOrderItemDetail>();
            this.MP_EBayOrderItemDetail1 = new HashSet<MP_EBayOrderItemDetail>();
            this.MP_EBayOrderItemDetail2 = new HashSet<MP_EBayOrderItemDetail>();
            this.MP_EBayOrderItemDetail3 = new HashSet<MP_EBayOrderItemDetail>();
        }
    
        public int Id { get; set; }
        public int MarketplaceTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ServiceCategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsVirtual { get; set; }
    
        public virtual ICollection<MP_AmazonOrderItemDetailCatgory> MP_AmazonOrderItemDetailCatgory { get; set; }
        public virtual ICollection<MP_EbayAmazonCategory> MP_EbayAmazonCategory1 { get; set; }
        public virtual MP_EbayAmazonCategory MP_EbayAmazonCategory2 { get; set; }
        public virtual MP_MarketplaceType MP_MarketplaceType { get; set; }
        public virtual ICollection<MP_EBayOrderItemDetail> MP_EBayOrderItemDetail { get; set; }
        public virtual ICollection<MP_EBayOrderItemDetail> MP_EBayOrderItemDetail1 { get; set; }
        public virtual ICollection<MP_EBayOrderItemDetail> MP_EBayOrderItemDetail2 { get; set; }
        public virtual ICollection<MP_EBayOrderItemDetail> MP_EBayOrderItemDetail3 { get; set; }
    }
}
