//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_EbayUserAccountData
    {
        public MP_EbayUserAccountData()
        {
            this.MP_EbayUserAdditionalAccountData = new HashSet<MP_EbayUserAdditionalAccountData>();
        }
    
        public int Id { get; set; }
        public int CustomerMarketPlaceId { get; set; }
        public System.DateTime Created { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> PastDue { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<System.DateTime> CreditCardModifyDate { get; set; }
        public string CreditCardInfo { get; set; }
        public Nullable<System.DateTime> CreditCardExpiration { get; set; }
        public Nullable<System.DateTime> BankModifyDate { get; set; }
        public string AccountState { get; set; }
        public string AmountPastDueCurrency { get; set; }
        public Nullable<double> AmountPastDueAmount { get; set; }
        public string BankAccountInfo { get; set; }
        public string AccountId { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CustomerMarketPlaceUpdatingHistoryRecordId { get; set; }
    
        public virtual MP_CustomerMarketPlace MP_CustomerMarketPlace { get; set; }
        public virtual ICollection<MP_EbayUserAdditionalAccountData> MP_EbayUserAdditionalAccountData { get; set; }
    }
}
