//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_ExperianHistory
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public long ServiceLogId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> CII { get; set; }
        public Nullable<decimal> CaisBalance { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public string CompanyRefNum { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MP_ServiceLog MP_ServiceLog { get; set; }
    }
}
