//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_FreeAgentRequest
    {
        public MP_FreeAgentRequest()
        {
            this.MP_FreeAgentCompany = new HashSet<MP_FreeAgentCompany>();
            this.MP_FreeAgentExpense = new HashSet<MP_FreeAgentExpense>();
            this.MP_FreeAgentInvoice = new HashSet<MP_FreeAgentInvoice>();
            this.MP_FreeAgentUsers = new HashSet<MP_FreeAgentUsers>();
        }
    
        public int Id { get; set; }
        public int CustomerMarketPlaceId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CustomerMarketPlaceUpdatingHistoryRecordId { get; set; }
    
        public virtual MP_CustomerMarketPlace MP_CustomerMarketPlace { get; set; }
        public virtual ICollection<MP_FreeAgentCompany> MP_FreeAgentCompany { get; set; }
        public virtual ICollection<MP_FreeAgentExpense> MP_FreeAgentExpense { get; set; }
        public virtual ICollection<MP_FreeAgentInvoice> MP_FreeAgentInvoice { get; set; }
        public virtual ICollection<MP_FreeAgentUsers> MP_FreeAgentUsers { get; set; }
    }
}
