//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_MarketplaceGroup
    {
        public MP_MarketplaceGroup()
        {
            this.MP_MarketplaceType = new HashSet<MP_MarketplaceType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool ActiveWizardOnline { get; set; }
        public bool ActiveWizardOffline { get; set; }
        public bool ActiveDashboardOnline { get; set; }
        public bool ActiveDashboardOffline { get; set; }
        public int PriorityOnline { get; set; }
        public int PriorityOffline { get; set; }
        public byte[] TimestampCounter { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<MP_MarketplaceType> MP_MarketplaceType { get; set; }
    }
}
