//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_PayPalAggregationFormula
    {
        public int Id { get; set; }
        public int FormulaNum { get; set; }
        public string FormulaName { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Positive { get; set; }
    }
}
