//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_SageRequest
    {
        public MP_SageRequest()
        {
            this.MP_SageExpenditure = new HashSet<MP_SageExpenditure>();
            this.MP_SageIncome = new HashSet<MP_SageIncome>();
            this.MP_SagePurchaseInvoice = new HashSet<MP_SagePurchaseInvoice>();
            this.MP_SageSalesInvoice = new HashSet<MP_SageSalesInvoice>();
        }
    
        public int Id { get; set; }
        public int CustomerMarketPlaceId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CustomerMarketPlaceUpdatingHistoryRecordId { get; set; }
    
        public virtual MP_CustomerMarketPlace MP_CustomerMarketPlace { get; set; }
        public virtual ICollection<MP_SageExpenditure> MP_SageExpenditure { get; set; }
        public virtual ICollection<MP_SageIncome> MP_SageIncome { get; set; }
        public virtual ICollection<MP_SagePurchaseInvoice> MP_SagePurchaseInvoice { get; set; }
        public virtual ICollection<MP_SageSalesInvoice> MP_SageSalesInvoice { get; set; }
    }
}
