//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_SageSalesInvoice
    {
        public MP_SageSalesInvoice()
        {
            this.MP_SageSalesInvoiceItem = new HashSet<MP_SageSalesInvoiceItem>();
            this.MP_SageSalesInvoiceItem1 = new HashSet<MP_SageSalesInvoiceItem>();
        }
    
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int SageId { get; set; }
        public string invoice_number { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string void_reason { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
        public Nullable<decimal> total_net_amount { get; set; }
        public Nullable<decimal> total_tax_amount { get; set; }
        public Nullable<int> tax_scheme_period_id { get; set; }
        public Nullable<decimal> carriage { get; set; }
        public Nullable<int> CarriageTaxCodeId { get; set; }
        public Nullable<decimal> carriage_tax_rate_percentage { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string contact_name { get; set; }
        public string main_address { get; set; }
        public string delivery_address { get; set; }
        public Nullable<bool> delivery_address_same_as_main { get; set; }
        public string reference { get; set; }
        public string notes { get; set; }
        public string terms_and_conditions { get; set; }
        public Nullable<int> lock_version { get; set; }
    
        public virtual MP_SageRequest MP_SageRequest { get; set; }
        public virtual ICollection<MP_SageSalesInvoiceItem> MP_SageSalesInvoiceItem { get; set; }
        public virtual ICollection<MP_SageSalesInvoiceItem> MP_SageSalesInvoiceItem1 { get; set; }
    }
}
