//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_VatReturnRecords
    {
        public MP_VatReturnRecords()
        {
            this.MP_VatReturnRecordDeleteHistory = new HashSet<MP_VatReturnRecordDeleteHistory>();
            this.MP_VatReturnRecordDeleteHistory1 = new HashSet<MP_VatReturnRecordDeleteHistory>();
        }
    
        public int Id { get; set; }
        public int CustomerMarketPlaceId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CustomerMarketPlaceUpdatingHistoryRecordId { get; set; }
        public string Period { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateDue { get; set; }
        public int BusinessId { get; set; }
        public long RegistrationNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int SourceID { get; set; }
        public System.Guid InternalID { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual MP_CustomerMarketPlace MP_CustomerMarketPlace { get; set; }
        public virtual ICollection<MP_VatReturnRecordDeleteHistory> MP_VatReturnRecordDeleteHistory { get; set; }
        public virtual ICollection<MP_VatReturnRecordDeleteHistory> MP_VatReturnRecordDeleteHistory1 { get; set; }
        public virtual VatReturnRecordSource VatReturnRecordSource { get; set; }
    }
}
