//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_VatReturnEntries
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int NameId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
