//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_VatReturnSummary
    {
        public MP_VatReturnSummary()
        {
            this.MP_VatReturnSummaryPeriods = new HashSet<MP_VatReturnSummaryPeriods>();
        }
    
        public long SummaryID { get; set; }
        public int CustomerID { get; set; }
        public int BusinessID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> PctOfAnnualRevenues { get; set; }
        public Nullable<decimal> Revenues { get; set; }
        public Nullable<decimal> Opex { get; set; }
        public Nullable<decimal> TotalValueAdded { get; set; }
        public Nullable<decimal> PctOfRevenues { get; set; }
        public Nullable<decimal> Salaries { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Ebida { get; set; }
        public Nullable<decimal> PctOfAnnual { get; set; }
        public Nullable<decimal> ActualLoanRepayment { get; set; }
        public Nullable<decimal> FreeCashFlow { get; set; }
        public byte[] TimestampCounter { get; set; }
        public Nullable<decimal> SalariesMultiplier { get; set; }
        public Nullable<int> CustomerMarketplaceID { get; set; }
        public System.Guid CalculationID { get; set; }
        public Nullable<decimal> AnnualizedTurnover { get; set; }
        public Nullable<decimal> AnnualizedValueAdded { get; set; }
        public Nullable<decimal> AnnualizedFreeCashFlow { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<MP_VatReturnSummaryPeriods> MP_VatReturnSummaryPeriods { get; set; }
    }
}
