//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_ValueType
    {
        public MP_ValueType()
        {
            this.MP_AnalyisisFunction = new HashSet<MP_AnalyisisFunction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid InternalId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MP_AnalyisisFunction> MP_AnalyisisFunction { get; set; }
    }
}
