//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_YodleeOrderItemBankTransaction
    {
        public int Id { get; set; }
        public int OrderItemId { get; set; }
        public Nullable<int> isSeidFromDataSource { get; set; }
        public Nullable<bool> isSeidFromDataSourceSpecified { get; set; }
        public Nullable<int> isSeidMod { get; set; }
        public Nullable<bool> isSeidModSpecified { get; set; }
        public string srcElementId { get; set; }
        public Nullable<int> transactionTypeId { get; set; }
        public Nullable<bool> transactionTypeIdSpecified { get; set; }
        public string transactionType { get; set; }
        public string localizedTransactionType { get; set; }
        public Nullable<int> transactionStatusId { get; set; }
        public Nullable<bool> transactionStatusIdSpecified { get; set; }
        public string transactionStatus { get; set; }
        public string localizedTransactionStatus { get; set; }
        public Nullable<int> transactionBaseTypeId { get; set; }
        public Nullable<bool> transactionBaseTypeIdSpecified { get; set; }
        public string transactionBaseType { get; set; }
        public string localizedTransactionBaseType { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<bool> categoryIdSpecified { get; set; }
        public Nullable<int> bankTransactionId { get; set; }
        public Nullable<bool> bankTransactionIdSpecified { get; set; }
        public Nullable<int> bankAccountId { get; set; }
        public Nullable<bool> bankAccountIdSpecified { get; set; }
        public Nullable<int> bankStatementId { get; set; }
        public Nullable<bool> bankStatementIdSpecified { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<bool> isDeletedSpecified { get; set; }
        public Nullable<int> lastUpdated { get; set; }
        public Nullable<bool> lastUpdatedSpecified { get; set; }
        public Nullable<int> hasDetails { get; set; }
        public Nullable<bool> hasDetailsSpecified { get; set; }
        public string transactionId { get; set; }
        public string transactionCategoryId { get; set; }
        public string siteCategoryType { get; set; }
        public string siteCategory { get; set; }
        public string classUpdationSource { get; set; }
        public string lastCategorised { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public Nullable<int> isReimbursable { get; set; }
        public Nullable<bool> isReimbursableSpecified { get; set; }
        public string mcCode { get; set; }
        public Nullable<int> prevLastCategorised { get; set; }
        public Nullable<bool> prevLastCategorisedSpecified { get; set; }
        public string naicsCode { get; set; }
        public Nullable<double> runningBalance { get; set; }
        public string runningBalanceCurrency { get; set; }
        public string userDescription { get; set; }
        public Nullable<int> customCategoryId { get; set; }
        public Nullable<bool> customCategoryIdSpecified { get; set; }
        public string memo { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<bool> parentIdSpecified { get; set; }
        public Nullable<int> isOlbUserDesc { get; set; }
        public Nullable<bool> isOlbUserDescSpecified { get; set; }
        public string categorisationSourceId { get; set; }
        public string plainTextDescription { get; set; }
        public string splitType { get; set; }
        public Nullable<int> categoryLevelId { get; set; }
        public Nullable<bool> categoryLevelIdSpecified { get; set; }
        public Nullable<double> calcRunningBalance { get; set; }
        public string calcRunningBalanceCurrency { get; set; }
        public string category { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public Nullable<int> prevTransactionCategoryId { get; set; }
        public Nullable<bool> prevTransactionCategoryIdSpecified { get; set; }
        public Nullable<int> isBusinessExpense { get; set; }
        public Nullable<bool> isBusinessExpenseSpecified { get; set; }
        public Nullable<int> descriptionViewPref { get; set; }
        public Nullable<bool> descriptionViewPrefSpecified { get; set; }
        public Nullable<int> prevCategorisationSourceId { get; set; }
        public Nullable<bool> prevCategorisationSourceIdSpecified { get; set; }
        public Nullable<double> transactionAmount { get; set; }
        public string transactionAmountCurrency { get; set; }
        public Nullable<int> transactionPostingOrder { get; set; }
        public Nullable<bool> transactionPostingOrderSpecified { get; set; }
        public string checkNumber { get; set; }
        public string description { get; set; }
        public Nullable<int> isTaxDeductible { get; set; }
        public Nullable<bool> isTaxDeductibleSpecified { get; set; }
        public Nullable<int> isMedicalExpense { get; set; }
        public Nullable<bool> isMedicalExpenseSpecified { get; set; }
        public string categorizationKeyword { get; set; }
        public string sourceTransactionType { get; set; }
        public Nullable<int> EzbobCategory { get; set; }
    
        public virtual MP_YodleeGroup MP_YodleeGroup { get; set; }
        public virtual MP_YodleeOrderItem MP_YodleeOrderItem { get; set; }
        public virtual MP_YodleeTransactionCategories MP_YodleeTransactionCategories { get; set; }
    }
}
