//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perk
    {
        public int Id { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public bool Active { get; set; }
        public string PerkHtml { get; set; }
    }
}
