//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickOfferConfiguration
    {
        public int ID { get; set; }
        public int Enabled { get; set; }
        public int CompanySeniorityMonths { get; set; }
        public int ApplicantMinAgeYears { get; set; }
        public int NoDefaultsInLastMonths { get; set; }
        public int AmlMin { get; set; }
        public int PersonalScoreMin { get; set; }
        public int BusinessScoreMin { get; set; }
        public int MaxLoanCountPerDay { get; set; }
        public int MaxIssuedValuePerDay { get; set; }
        public int OfferDurationHours { get; set; }
        public int MinOfferAmount { get; set; }
        public decimal OfferCapPct { get; set; }
        public int ImmediateMaxAmount { get; set; }
        public int ImmediateTermMonths { get; set; }
        public decimal ImmediateInterestRate { get; set; }
        public decimal ImmediateSetupFee { get; set; }
        public int PotentialMaxAmount { get; set; }
        public int PotentialTermMonths { get; set; }
        public decimal PotentialSetupFee { get; set; }
        public string OfferAmountCalculator { get; set; }
        public string PriceCalculator { get; set; }
        public byte[] TimestampCounter { get; set; }
    }
}
