//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_vUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string EMail { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> SessionCreationDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<long> PassExpPeriod { get; set; }
        public Nullable<int> ForcePassChange { get; set; }
        public Nullable<int> DisablePassChange { get; set; }
        public string CertificateThumbprint { get; set; }
    }
}
