//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAnalytic
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SiteAnalyticsCode { get; set; }
        public Nullable<int> SiteAnalyticsValue { get; set; }
        public string Source { get; set; }
    
        public virtual SiteAnalyticsCode SiteAnalyticsCode1 { get; set; }
    }
}
