//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedAmount
    {
        public long Id { get; set; }
        public int CustomerId { get; set; }
        public int UnderwriterId { get; set; }
        public long CashRequestId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public decimal Amount { get; set; }
        public string Method { get; set; }
        public string Medal { get; set; }
        public decimal Percents { get; set; }
    
        public virtual CashRequest CashRequest { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Security_User Security_User { get; set; }
    }
}
