//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UiControl
    {
        public UiControl()
        {
            this.UiControlGroupRelevances = new HashSet<UiControlGroupRelevance>();
            this.UiEvents = new HashSet<UiEvent>();
        }
    
        public int UiControlID { get; set; }
        public string UiControlName { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual ICollection<UiControlGroupRelevance> UiControlGroupRelevances { get; set; }
        public virtual ICollection<UiEvent> UiEvents { get; set; }
    }
}
