//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardStepSequence
    {
        public int ID { get; set; }
        public string StepName { get; set; }
        public Nullable<int> OnlineProgressBarPct { get; set; }
        public Nullable<int> OfflineProgressBarPct { get; set; }
        public int WizardStepType { get; set; }
        public byte[] TimestampCounter { get; set; }
    
        public virtual WizardStepType WizardStepType1 { get; set; }
    }
}
