create or replace package DBCONSTANTS is
  -- Purpose : Global constants
  STRATEGY_LOCKED CONSTANT NUMBER := 0;
  STRATEGY_UNLOCKED CONSTANT NUMBER := 1;
  STRATEGY_STATE_CHALLANGE CONSTANT NUMBER := 0;
  STRATEGY_STATE_CHAMPION CONSTANT NUMBER := 1;
  STRATEGY_ERR_ISLOCKED CONSTANT VARCHAR2(25) := 'StrategyIsLocked';
  STRATEGY_ERRCODE_ISLOCKED CONSTANT NUMBER := -20001;
  STRATEGY_ERR_NOTEXISTS CONSTANT Varchar2(25) := 'StrategyNoExist';
  STRATEGY_ERRCODE_NOTEXISTS CONSTANT Number := -20000;

  STRATEGY_PUBLISH_CHAMPION CONSTANT NUMBER := 2; --Published (Champion);
  STRATEGY_SUSPEND_CHAMPION CONSTANT NUMBER := 3;  -- Suspended (Champion)
  STRATEGY_ERR_CANTFIND CONSTANT VARCHAR2(25) := 'CantFind';
  STRATEGY_ERRCODE_CANTFIND CONSTANT NUMBER := -20002;

  ERR_APP_WAS_PROCESSED_MSG CONSTANT Varchar2(100) := 'ApplicationWasProcessed';
  ERR_APP_WAS_PROCESSED_ERRCODE CONSTANT NUMBER := -20003;

  ERR_APP_ID_DOESN_EXIST_MSG CONSTANT Varchar2(100) := 'ApplicationIdDoesNotExist';
  ERR_APP_ID_DOESN_EXIST_ERRCODE CONSTANT NUMBER := -20004;

  ERR_APP_LCKD_BY_USER_MSG CONSTANT Varchar2(100) := 'ApplicationLockedByOtherUser';
  ERR_APP_LCKD_BY_USER_ERRCODE CONSTANT NUMBER := -20005;

  ERR_APP_NOT_FOUND_MSG CONSTANT Varchar2(100) := 'ApplicationNotFound';
  ERR_APP_NOT_FOUND_ERRCODE CONSTANT NUMBER := -20006;

  ERR_APP_EXEC_BY_SE_MSG CONSTANT Varchar2(50) :=  'ApplicationExecutingByEngine';
  ERR_APP_EXEC_BY_SE_ERRCODE CONSTANT NUMBER := -20007;
end DBCONSTANTS;
/