SET SQLSERVER_NAME=%1
SET SYSTEMUSER=%2
SET SYSTEMPWD=%3
SET DATABASE_NAME=%4

  echo ReCREATE new scema
cd Scripts
call install-4TFS.cmd %SQLSERVER_NAME% %SYSTEMUSER% %SYSTEMPWD% %DATABASE_NAME%
cd ..

  echo LOAD DATA!
cd MIGRATION
call start_all-4TFS.bat %SQLSERVER_NAME% %SYSTEMUSER% %SYSTEMPWD% %DATABASE_NAME%
cd ..