namespace Ezbob.Utils.MimeTypes {
	using System;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

	public class MimeTypeResolver {
		static MimeTypeResolver() {
			ms_oFileExtMap = new SortedDictionary<string, MimeType> {
				{ ".323", new MimeType { FileExtension = ".323", IsText = true, PrimaryMimeType = "text/h323", SecondaryMimeTypes = "" } },
				{ ".3g2", new MimeType { FileExtension = ".3g2", IsText = false, PrimaryMimeType = "video/3gpp2", SecondaryMimeTypes = "" } },
				{ ".3gp", new MimeType { FileExtension = ".3gp", IsText = false, PrimaryMimeType = "video/3gpp", SecondaryMimeTypes = "" } },
				{ ".3gp2", new MimeType { FileExtension = ".3gp2", IsText = false, PrimaryMimeType = "video/3gpp2", SecondaryMimeTypes = "" } },
				{ ".3gpp", new MimeType { FileExtension = ".3gpp", IsText = false, PrimaryMimeType = "video/3gpp", SecondaryMimeTypes = "" } },
				{ ".7z", new MimeType { FileExtension = ".7z", IsText = false, PrimaryMimeType = "application/x-7z-compressed", SecondaryMimeTypes = "" } },
				{ ".aa", new MimeType { FileExtension = ".aa", IsText = false, PrimaryMimeType = "audio/audible", SecondaryMimeTypes = "" } },
				{ ".AAC", new MimeType { FileExtension = ".AAC", IsText = false, PrimaryMimeType = "audio/aac", SecondaryMimeTypes = "" } },
				{ ".aaf", new MimeType { FileExtension = ".aaf", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".aax", new MimeType { FileExtension = ".aax", IsText = false, PrimaryMimeType = "audio/vnd.audible.aax", SecondaryMimeTypes = "" } },
				{ ".ac3", new MimeType { FileExtension = ".ac3", IsText = false, PrimaryMimeType = "audio/ac3", SecondaryMimeTypes = "" } },
				{ ".aca", new MimeType { FileExtension = ".aca", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".accda", new MimeType { FileExtension = ".accda", IsText = false, PrimaryMimeType = "application/msaccess.addin", SecondaryMimeTypes = "" } },
				{ ".accdb", new MimeType { FileExtension = ".accdb", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdc", new MimeType { FileExtension = ".accdc", IsText = false, PrimaryMimeType = "application/msaccess.cab", SecondaryMimeTypes = "" } },
				{ ".accde", new MimeType { FileExtension = ".accde", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdr", new MimeType { FileExtension = ".accdr", IsText = false, PrimaryMimeType = "application/msaccess.runtime", SecondaryMimeTypes = "" } },
				{ ".accdt", new MimeType { FileExtension = ".accdt", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdw", new MimeType { FileExtension = ".accdw", IsText = false, PrimaryMimeType = "application/msaccess.webapplication", SecondaryMimeTypes = "" } },
				{ ".accft", new MimeType { FileExtension = ".accft", IsText = false, PrimaryMimeType = "application/msaccess.ftemplate", SecondaryMimeTypes = "" } },
				{ ".acx", new MimeType { FileExtension = ".acx", IsText = false, PrimaryMimeType = "application/internet-property-stream", SecondaryMimeTypes = "" } },
				{ ".AddIn", new MimeType { FileExtension = ".AddIn", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".ade", new MimeType { FileExtension = ".ade", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".adobebridge", new MimeType { FileExtension = ".adobebridge", IsText = false, PrimaryMimeType = "application/x-bridge-url", SecondaryMimeTypes = "" } },
				{ ".adp", new MimeType { FileExtension = ".adp", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".ADT", new MimeType { FileExtension = ".ADT", IsText = false, PrimaryMimeType = "audio/vnd.dlna.adts", SecondaryMimeTypes = "" } },
				{ ".ADTS", new MimeType { FileExtension = ".ADTS", IsText = false, PrimaryMimeType = "audio/aac", SecondaryMimeTypes = "" } },
				{ ".afm", new MimeType { FileExtension = ".afm", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ai", new MimeType { FileExtension = ".ai", IsText = false, PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".aif", new MimeType { FileExtension = ".aif", IsText = false, PrimaryMimeType = "audio/x-aiff", SecondaryMimeTypes = "" } },
				{ ".aifc", new MimeType { FileExtension = ".aifc", IsText = false, PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".aiff", new MimeType { FileExtension = ".aiff", IsText = false, PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".air", new MimeType { FileExtension = ".air", IsText = false, PrimaryMimeType = "application/vnd.adobe.air-application-installer-package+zip", SecondaryMimeTypes = "" } },
				{ ".amc", new MimeType { FileExtension = ".amc", IsText = false, PrimaryMimeType = "application/x-mpeg", SecondaryMimeTypes = "" } },
				{ ".application", new MimeType { FileExtension = ".application", IsText = false, PrimaryMimeType = "application/x-ms-application", SecondaryMimeTypes = "" } },
				{ ".art", new MimeType { FileExtension = ".art", IsText = false, PrimaryMimeType = "image/x-jg", SecondaryMimeTypes = "" } },
				{ ".asa", new MimeType { FileExtension = ".asa", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asax", new MimeType { FileExtension = ".asax", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".ascx", new MimeType { FileExtension = ".ascx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asd", new MimeType { FileExtension = ".asd", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".asf", new MimeType { FileExtension = ".asf", IsText = false, PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".ashx", new MimeType { FileExtension = ".ashx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asi", new MimeType { FileExtension = ".asi", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".asm", new MimeType { FileExtension = ".asm", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".asmx", new MimeType { FileExtension = ".asmx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".aspx", new MimeType { FileExtension = ".aspx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asr", new MimeType { FileExtension = ".asr", IsText = false, PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".asx", new MimeType { FileExtension = ".asx", IsText = false, PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".atom", new MimeType { FileExtension = ".atom", IsText = false, PrimaryMimeType = "application/atom+xml", SecondaryMimeTypes = "" } },
				{ ".au", new MimeType { FileExtension = ".au", IsText = false, PrimaryMimeType = "audio/basic", SecondaryMimeTypes = "" } },
				{ ".avi", new MimeType { FileExtension = ".avi", IsText = false, PrimaryMimeType = "video/x-msvideo", SecondaryMimeTypes = "" } },
				{ ".axs", new MimeType { FileExtension = ".axs", IsText = false, PrimaryMimeType = "application/olescript", SecondaryMimeTypes = "" } },
				{ ".bas", new MimeType { FileExtension = ".bas", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".bcpio", new MimeType { FileExtension = ".bcpio", IsText = false, PrimaryMimeType = "application/x-bcpio", SecondaryMimeTypes = "" } },
				{ ".bin", new MimeType { FileExtension = ".bin", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".bmp", new MimeType { FileExtension = ".bmp", IsText = false, PrimaryMimeType = "image/bmp", SecondaryMimeTypes = "" } },
				{ ".c", new MimeType { FileExtension = ".c", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".cab", new MimeType { FileExtension = ".cab", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".caf", new MimeType { FileExtension = ".caf", IsText = false, PrimaryMimeType = "audio/x-caf", SecondaryMimeTypes = "" } },
				{ ".calx", new MimeType { FileExtension = ".calx", IsText = false, PrimaryMimeType = "application/vnd.ms-office.calx", SecondaryMimeTypes = "" } },
				{ ".cat", new MimeType { FileExtension = ".cat", IsText = false, PrimaryMimeType = "application/vnd.ms-pki.seccat", SecondaryMimeTypes = "" } },
				{ ".cc", new MimeType { FileExtension = ".cc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".cd", new MimeType { FileExtension = ".cd", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".cdda", new MimeType { FileExtension = ".cdda", IsText = false, PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".cdf", new MimeType { FileExtension = ".cdf", IsText = false, PrimaryMimeType = "application/x-cdf", SecondaryMimeTypes = "" } },
				{ ".cer", new MimeType { FileExtension = ".cer", IsText = false, PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".chm", new MimeType { FileExtension = ".chm", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".class", new MimeType { FileExtension = ".class", IsText = false, PrimaryMimeType = "application/x-java-applet", SecondaryMimeTypes = "" } },
				{ ".clp", new MimeType { FileExtension = ".clp", IsText = false, PrimaryMimeType = "application/x-msclip", SecondaryMimeTypes = "" } },
				{ ".cmx", new MimeType { FileExtension = ".cmx", IsText = false, PrimaryMimeType = "image/x-cmx", SecondaryMimeTypes = "" } },
				{ ".cnf", new MimeType { FileExtension = ".cnf", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".cod", new MimeType { FileExtension = ".cod", IsText = false, PrimaryMimeType = "image/cis-cod", SecondaryMimeTypes = "" } },
				{ ".config", new MimeType { FileExtension = ".config", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".contact", new MimeType { FileExtension = ".contact", IsText = true, PrimaryMimeType = "text/x-ms-contact", SecondaryMimeTypes = "" } },
				{ ".coverage", new MimeType { FileExtension = ".coverage", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".cpio", new MimeType { FileExtension = ".cpio", IsText = false, PrimaryMimeType = "application/x-cpio", SecondaryMimeTypes = "" } },
				{ ".cpp", new MimeType { FileExtension = ".cpp", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".crd", new MimeType { FileExtension = ".crd", IsText = false, PrimaryMimeType = "application/x-mscardfile", SecondaryMimeTypes = "" } },
				{ ".crl", new MimeType { FileExtension = ".crl", IsText = false, PrimaryMimeType = "application/pkix-crl", SecondaryMimeTypes = "" } },
				{ ".crt", new MimeType { FileExtension = ".crt", IsText = false, PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".cs", new MimeType { FileExtension = ".cs", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".csdproj", new MimeType { FileExtension = ".csdproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".csh", new MimeType { FileExtension = ".csh", IsText = true, PrimaryMimeType = "application/x-csh", SecondaryMimeTypes = "" } },
				{ ".csproj", new MimeType { FileExtension = ".csproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".css", new MimeType { FileExtension = ".css", IsText = true, PrimaryMimeType = "text/css", SecondaryMimeTypes = "" } },
				{ ".csv", new MimeType { FileExtension = ".csv", IsText = true, PrimaryMimeType = "text/csv", SecondaryMimeTypes = "" } },
				{ ".cur", new MimeType { FileExtension = ".cur", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".cxx", new MimeType { FileExtension = ".cxx", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".dat", new MimeType { FileExtension = ".dat", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".datasource", new MimeType { FileExtension = ".datasource", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".dbproj", new MimeType { FileExtension = ".dbproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".dcr", new MimeType { FileExtension = ".dcr", IsText = false, PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".def", new MimeType { FileExtension = ".def", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".deploy", new MimeType { FileExtension = ".deploy", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".der", new MimeType { FileExtension = ".der", IsText = false, PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".dgml", new MimeType { FileExtension = ".dgml", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".dib", new MimeType { FileExtension = ".dib", IsText = false, PrimaryMimeType = "image/bmp", SecondaryMimeTypes = "" } },
				{ ".dif", new MimeType { FileExtension = ".dif", IsText = false, PrimaryMimeType = "video/x-dv", SecondaryMimeTypes = "" } },
				{ ".dir", new MimeType { FileExtension = ".dir", IsText = false, PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".disco", new MimeType { FileExtension = ".disco", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dll", new MimeType { FileExtension = ".dll", IsText = false, PrimaryMimeType = "application/x-msdownload", SecondaryMimeTypes = "" } },
				{ ".dll.config", new MimeType { FileExtension = ".dll.config", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dlm", new MimeType { FileExtension = ".dlm", IsText = true, PrimaryMimeType = "text/dlm", SecondaryMimeTypes = "" } },
				{ ".doc", new MimeType { FileExtension = ".doc", IsText = false, PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".docm", new MimeType { FileExtension = ".docm", IsText = false, PrimaryMimeType = "application/vnd.ms-word.document.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".docx", new MimeType { FileExtension = ".docx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", SecondaryMimeTypes = "zip" } },
				{ ".dot", new MimeType { FileExtension = ".dot", IsText = false, PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".dotm", new MimeType { FileExtension = ".dotm", IsText = false, PrimaryMimeType = "application/vnd.ms-word.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".dotx", new MimeType { FileExtension = ".dotx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.template", SecondaryMimeTypes = "zip" } },
				{ ".dsp", new MimeType { FileExtension = ".dsp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".dsw", new MimeType { FileExtension = ".dsw", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".dtd", new MimeType { FileExtension = ".dtd", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dtsConfig", new MimeType { FileExtension = ".dtsConfig", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dv", new MimeType { FileExtension = ".dv", IsText = false, PrimaryMimeType = "video/x-dv", SecondaryMimeTypes = "" } },
				{ ".dvi", new MimeType { FileExtension = ".dvi", IsText = false, PrimaryMimeType = "application/x-dvi", SecondaryMimeTypes = "" } },
				{ ".dwf", new MimeType { FileExtension = ".dwf", IsText = false, PrimaryMimeType = "drawing/x-dwf", SecondaryMimeTypes = "" } },
				{ ".dwp", new MimeType { FileExtension = ".dwp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".dxr", new MimeType { FileExtension = ".dxr", IsText = false, PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".eml", new MimeType { FileExtension = ".eml", IsText = false, PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".emz", new MimeType { FileExtension = ".emz", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".eot", new MimeType { FileExtension = ".eot", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".eps", new MimeType { FileExtension = ".eps", IsText = false, PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".etl", new MimeType { FileExtension = ".etl", IsText = false, PrimaryMimeType = "application/etl", SecondaryMimeTypes = "" } },
				{ ".etx", new MimeType { FileExtension = ".etx", IsText = true, PrimaryMimeType = "text/x-setext", SecondaryMimeTypes = "" } },
				{ ".evy", new MimeType { FileExtension = ".evy", IsText = false, PrimaryMimeType = "application/envoy", SecondaryMimeTypes = "" } },
				{ ".exe", new MimeType { FileExtension = ".exe", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".exe.config", new MimeType { FileExtension = ".exe.config", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".fdf", new MimeType { FileExtension = ".fdf", IsText = false, PrimaryMimeType = "application/vnd.fdf", SecondaryMimeTypes = "" } },
				{ ".fif", new MimeType { FileExtension = ".fif", IsText = false, PrimaryMimeType = "application/fractals", SecondaryMimeTypes = "" } },
				{ ".filters", new MimeType { FileExtension = ".filters", IsText = true, PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".fla", new MimeType { FileExtension = ".fla", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".flr", new MimeType { FileExtension = ".flr", IsText = false, PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".flv", new MimeType { FileExtension = ".flv", IsText = false, PrimaryMimeType = "video/x-flv", SecondaryMimeTypes = "" } },
				{ ".fsscript", new MimeType { FileExtension = ".fsscript", IsText = false, PrimaryMimeType = "application/fsharp-script", SecondaryMimeTypes = "" } },
				{ ".fsx", new MimeType { FileExtension = ".fsx", IsText = false, PrimaryMimeType = "application/fsharp-script", SecondaryMimeTypes = "" } },
				{ ".generictest", new MimeType { FileExtension = ".generictest", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".gif", new MimeType { FileExtension = ".gif", IsText = false, PrimaryMimeType = "image/gif", SecondaryMimeTypes = "" } },
				{ ".group", new MimeType { FileExtension = ".group", IsText = true, PrimaryMimeType = "text/x-ms-group", SecondaryMimeTypes = "" } },
				{ ".gsm", new MimeType { FileExtension = ".gsm", IsText = false, PrimaryMimeType = "audio/x-gsm", SecondaryMimeTypes = "" } },
				{ ".gtar", new MimeType { FileExtension = ".gtar", IsText = false, PrimaryMimeType = "application/x-gtar", SecondaryMimeTypes = "" } },
				{ ".gz", new MimeType { FileExtension = ".gz", IsText = false, PrimaryMimeType = "application/x-gzip", SecondaryMimeTypes = "" } },
				{ ".h", new MimeType { FileExtension = ".h", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hdf", new MimeType { FileExtension = ".hdf", IsText = false, PrimaryMimeType = "application/x-hdf", SecondaryMimeTypes = "" } },
				{ ".hdml", new MimeType { FileExtension = ".hdml", IsText = true, PrimaryMimeType = "text/x-hdml", SecondaryMimeTypes = "" } },
				{ ".hhc", new MimeType { FileExtension = ".hhc", IsText = false, PrimaryMimeType = "application/x-oleobject", SecondaryMimeTypes = "" } },
				{ ".hhk", new MimeType { FileExtension = ".hhk", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hhp", new MimeType { FileExtension = ".hhp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hlp", new MimeType { FileExtension = ".hlp", IsText = false, PrimaryMimeType = "application/winhlp", SecondaryMimeTypes = "" } },
				{ ".hpp", new MimeType { FileExtension = ".hpp", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hqx", new MimeType { FileExtension = ".hqx", IsText = false, PrimaryMimeType = "application/mac-binhex40", SecondaryMimeTypes = "" } },
				{ ".hta", new MimeType { FileExtension = ".hta", IsText = false, PrimaryMimeType = "application/hta", SecondaryMimeTypes = "" } },
				{ ".htc", new MimeType { FileExtension = ".htc", IsText = true, PrimaryMimeType = "text/x-component", SecondaryMimeTypes = "" } },
				{ ".htm", new MimeType { FileExtension = ".htm", IsText = true, PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".html", new MimeType { FileExtension = ".html", IsText = true, PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".htt", new MimeType { FileExtension = ".htt", IsText = true, PrimaryMimeType = "text/webviewhtml", SecondaryMimeTypes = "" } },
				{ ".hxa", new MimeType { FileExtension = ".hxa", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxc", new MimeType { FileExtension = ".hxc", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxd", new MimeType { FileExtension = ".hxd", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxe", new MimeType { FileExtension = ".hxe", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxf", new MimeType { FileExtension = ".hxf", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxh", new MimeType { FileExtension = ".hxh", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxi", new MimeType { FileExtension = ".hxi", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxk", new MimeType { FileExtension = ".hxk", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxq", new MimeType { FileExtension = ".hxq", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxr", new MimeType { FileExtension = ".hxr", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxs", new MimeType { FileExtension = ".hxs", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxt", new MimeType { FileExtension = ".hxt", IsText = true, PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".hxv", new MimeType { FileExtension = ".hxv", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxw", new MimeType { FileExtension = ".hxw", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".hxx", new MimeType { FileExtension = ".hxx", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".i", new MimeType { FileExtension = ".i", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ico", new MimeType { FileExtension = ".ico", IsText = false, PrimaryMimeType = "image/x-icon", SecondaryMimeTypes = "" } },
				{ ".ics", new MimeType { FileExtension = ".ics", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".idl", new MimeType { FileExtension = ".idl", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ief", new MimeType { FileExtension = ".ief", IsText = false, PrimaryMimeType = "image/ief", SecondaryMimeTypes = "" } },
				{ ".iii", new MimeType { FileExtension = ".iii", IsText = false, PrimaryMimeType = "application/x-iphone", SecondaryMimeTypes = "" } },
				{ ".inc", new MimeType { FileExtension = ".inc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".inf", new MimeType { FileExtension = ".inf", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".inl", new MimeType { FileExtension = ".inl", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ins", new MimeType { FileExtension = ".ins", IsText = false, PrimaryMimeType = "application/x-internet-signup", SecondaryMimeTypes = "" } },
				{ ".ipa", new MimeType { FileExtension = ".ipa", IsText = false, PrimaryMimeType = "application/x-itunes-ipa", SecondaryMimeTypes = "" } },
				{ ".ipg", new MimeType { FileExtension = ".ipg", IsText = false, PrimaryMimeType = "application/x-itunes-ipg", SecondaryMimeTypes = "" } },
				{ ".ipproj", new MimeType { FileExtension = ".ipproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ipsw", new MimeType { FileExtension = ".ipsw", IsText = false, PrimaryMimeType = "application/x-itunes-ipsw", SecondaryMimeTypes = "" } },
				{ ".iqy", new MimeType { FileExtension = ".iqy", IsText = true, PrimaryMimeType = "text/x-ms-iqy", SecondaryMimeTypes = "" } },
				{ ".isp", new MimeType { FileExtension = ".isp", IsText = false, PrimaryMimeType = "application/x-internet-signup", SecondaryMimeTypes = "" } },
				{ ".ite", new MimeType { FileExtension = ".ite", IsText = false, PrimaryMimeType = "application/x-itunes-ite", SecondaryMimeTypes = "" } },
				{ ".itlp", new MimeType { FileExtension = ".itlp", IsText = false, PrimaryMimeType = "application/x-itunes-itlp", SecondaryMimeTypes = "" } },
				{ ".itms", new MimeType { FileExtension = ".itms", IsText = false, PrimaryMimeType = "application/x-itunes-itms", SecondaryMimeTypes = "" } },
				{ ".itpc", new MimeType { FileExtension = ".itpc", IsText = false, PrimaryMimeType = "application/x-itunes-itpc", SecondaryMimeTypes = "" } },
				{ ".IVF", new MimeType { FileExtension = ".IVF", IsText = false, PrimaryMimeType = "video/x-ivf", SecondaryMimeTypes = "" } },
				{ ".jar", new MimeType { FileExtension = ".jar", IsText = false, PrimaryMimeType = "application/java-archive", SecondaryMimeTypes = "" } },
				{ ".java", new MimeType { FileExtension = ".java", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".jck", new MimeType { FileExtension = ".jck", IsText = false, PrimaryMimeType = "application/liquidmotion", SecondaryMimeTypes = "" } },
				{ ".jcz", new MimeType { FileExtension = ".jcz", IsText = false, PrimaryMimeType = "application/liquidmotion", SecondaryMimeTypes = "" } },
				{ ".jfif", new MimeType { FileExtension = ".jfif", IsText = false, PrimaryMimeType = "image/pjpeg", SecondaryMimeTypes = "" } },
				{ ".jnlp", new MimeType { FileExtension = ".jnlp", IsText = false, PrimaryMimeType = "application/x-java-jnlp-file", SecondaryMimeTypes = "" } },
				{ ".jpb", new MimeType { FileExtension = ".jpb", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".jpe", new MimeType { FileExtension = ".jpe", IsText = false, PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".jpeg", new MimeType { FileExtension = ".jpeg", IsText = false, PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".jpg", new MimeType { FileExtension = ".jpg", IsText = false, PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".js", new MimeType { FileExtension = ".js", IsText = true, PrimaryMimeType = "application/x-javascript", SecondaryMimeTypes = "" } },
				{ ".jsx", new MimeType { FileExtension = ".jsx", IsText = true, PrimaryMimeType = "text/jscript", SecondaryMimeTypes = "" } },
				{ ".jsxbin", new MimeType { FileExtension = ".jsxbin", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".latex", new MimeType { FileExtension = ".latex", IsText = false, PrimaryMimeType = "application/x-latex", SecondaryMimeTypes = "" } },
				{ ".library-ms", new MimeType { FileExtension = ".library-ms", IsText = false, PrimaryMimeType = "application/windows-library+xml", SecondaryMimeTypes = "" } },
				{ ".lit", new MimeType { FileExtension = ".lit", IsText = false, PrimaryMimeType = "application/x-ms-reader", SecondaryMimeTypes = "" } },
				{ ".loadtest", new MimeType { FileExtension = ".loadtest", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".lpk", new MimeType { FileExtension = ".lpk", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".lsf", new MimeType { FileExtension = ".lsf", IsText = false, PrimaryMimeType = "video/x-la-asf", SecondaryMimeTypes = "" } },
				{ ".lst", new MimeType { FileExtension = ".lst", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".lsx", new MimeType { FileExtension = ".lsx", IsText = false, PrimaryMimeType = "video/x-la-asf", SecondaryMimeTypes = "" } },
				{ ".lzh", new MimeType { FileExtension = ".lzh", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".m13", new MimeType { FileExtension = ".m13", IsText = false, PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".m14", new MimeType { FileExtension = ".m14", IsText = false, PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".m1v", new MimeType { FileExtension = ".m1v", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".m2t", new MimeType { FileExtension = ".m2t", IsText = false, PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".m2ts", new MimeType { FileExtension = ".m2ts", IsText = false, PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".m2v", new MimeType { FileExtension = ".m2v", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".m3u", new MimeType { FileExtension = ".m3u", IsText = false, PrimaryMimeType = "audio/x-mpegurl", SecondaryMimeTypes = "" } },
				{ ".m3u8", new MimeType { FileExtension = ".m3u8", IsText = false, PrimaryMimeType = "audio/x-mpegurl", SecondaryMimeTypes = "" } },
				{ ".m4a", new MimeType { FileExtension = ".m4a", IsText = false, PrimaryMimeType = "audio/m4a", SecondaryMimeTypes = "" } },
				{ ".m4b", new MimeType { FileExtension = ".m4b", IsText = false, PrimaryMimeType = "audio/m4b", SecondaryMimeTypes = "" } },
				{ ".m4p", new MimeType { FileExtension = ".m4p", IsText = false, PrimaryMimeType = "audio/m4p", SecondaryMimeTypes = "" } },
				{ ".m4r", new MimeType { FileExtension = ".m4r", IsText = false, PrimaryMimeType = "audio/x-m4r", SecondaryMimeTypes = "" } },
				{ ".m4v", new MimeType { FileExtension = ".m4v", IsText = false, PrimaryMimeType = "video/x-m4v", SecondaryMimeTypes = "" } },
				{ ".mac", new MimeType { FileExtension = ".mac", IsText = false, PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".mak", new MimeType { FileExtension = ".mak", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".man", new MimeType { FileExtension = ".man", IsText = false, PrimaryMimeType = "application/x-troff-man", SecondaryMimeTypes = "" } },
				{ ".manifest", new MimeType { FileExtension = ".manifest", IsText = false, PrimaryMimeType = "application/x-ms-manifest", SecondaryMimeTypes = "" } },
				{ ".map", new MimeType { FileExtension = ".map", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".master", new MimeType { FileExtension = ".master", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".mda", new MimeType { FileExtension = ".mda", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".mdb", new MimeType { FileExtension = ".mdb", IsText = false, PrimaryMimeType = "application/x-msaccess", SecondaryMimeTypes = "" } },
				{ ".mde", new MimeType { FileExtension = ".mde", IsText = false, PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".mdp", new MimeType { FileExtension = ".mdp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".me", new MimeType { FileExtension = ".me", IsText = false, PrimaryMimeType = "application/x-troff-me", SecondaryMimeTypes = "" } },
				{ ".mfp", new MimeType { FileExtension = ".mfp", IsText = false, PrimaryMimeType = "application/x-shockwave-flash", SecondaryMimeTypes = "" } },
				{ ".mht", new MimeType { FileExtension = ".mht", IsText = false, PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".mhtml", new MimeType { FileExtension = ".mhtml", IsText = false, PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".mid", new MimeType { FileExtension = ".mid", IsText = false, PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".midi", new MimeType { FileExtension = ".midi", IsText = false, PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".mix", new MimeType { FileExtension = ".mix", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".mk", new MimeType { FileExtension = ".mk", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".mmf", new MimeType { FileExtension = ".mmf", IsText = false, PrimaryMimeType = "application/x-smaf", SecondaryMimeTypes = "" } },
				{ ".mno", new MimeType { FileExtension = ".mno", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".mny", new MimeType { FileExtension = ".mny", IsText = false, PrimaryMimeType = "application/x-msmoney", SecondaryMimeTypes = "" } },
				{ ".mod", new MimeType { FileExtension = ".mod", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mov", new MimeType { FileExtension = ".mov", IsText = false, PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".movie", new MimeType { FileExtension = ".movie", IsText = false, PrimaryMimeType = "video/x-sgi-movie", SecondaryMimeTypes = "" } },
				{ ".mp2", new MimeType { FileExtension = ".mp2", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp2v", new MimeType { FileExtension = ".mp2v", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp3", new MimeType { FileExtension = ".mp3", IsText = false, PrimaryMimeType = "audio/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp4", new MimeType { FileExtension = ".mp4", IsText = false, PrimaryMimeType = "video/mp4", SecondaryMimeTypes = "" } },
				{ ".mp4v", new MimeType { FileExtension = ".mp4v", IsText = false, PrimaryMimeType = "video/mp4", SecondaryMimeTypes = "" } },
				{ ".mpa", new MimeType { FileExtension = ".mpa", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpe", new MimeType { FileExtension = ".mpe", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpeg", new MimeType { FileExtension = ".mpeg", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpf", new MimeType { FileExtension = ".mpf", IsText = false, PrimaryMimeType = "application/vnd.ms-mediapackage", SecondaryMimeTypes = "" } },
				{ ".mpg", new MimeType { FileExtension = ".mpg", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpp", new MimeType { FileExtension = ".mpp", IsText = false, PrimaryMimeType = "application/vnd.ms-project", SecondaryMimeTypes = "" } },
				{ ".mpv2", new MimeType { FileExtension = ".mpv2", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mqv", new MimeType { FileExtension = ".mqv", IsText = false, PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".ms", new MimeType { FileExtension = ".ms", IsText = false, PrimaryMimeType = "application/x-troff-ms", SecondaryMimeTypes = "" } },
				{ ".msg", new MimeType { FileExtension = ".msg", IsText = false, PrimaryMimeType = "application/vnd.ms-outlook", SecondaryMimeTypes = "" } },
				{ ".msi", new MimeType { FileExtension = ".msi", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".mso", new MimeType { FileExtension = ".mso", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".mts", new MimeType { FileExtension = ".mts", IsText = false, PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".mtx", new MimeType { FileExtension = ".mtx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".mvb", new MimeType { FileExtension = ".mvb", IsText = false, PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".mvc", new MimeType { FileExtension = ".mvc", IsText = false, PrimaryMimeType = "application/x-miva-compiled", SecondaryMimeTypes = "" } },
				{ ".mxp", new MimeType { FileExtension = ".mxp", IsText = false, PrimaryMimeType = "application/x-mmxp", SecondaryMimeTypes = "" } },
				{ ".nc", new MimeType { FileExtension = ".nc", IsText = false, PrimaryMimeType = "application/x-netcdf", SecondaryMimeTypes = "" } },
				{ ".nsc", new MimeType { FileExtension = ".nsc", IsText = false, PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".nws", new MimeType { FileExtension = ".nws", IsText = false, PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".ocx", new MimeType { FileExtension = ".ocx", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".oda", new MimeType { FileExtension = ".oda", IsText = false, PrimaryMimeType = "application/oda", SecondaryMimeTypes = "" } },
				{ ".odc", new MimeType { FileExtension = ".odc", IsText = true, PrimaryMimeType = "text/x-ms-odc", SecondaryMimeTypes = "" } },
				{ ".odh", new MimeType { FileExtension = ".odh", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".odl", new MimeType { FileExtension = ".odl", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".odp", new MimeType { FileExtension = ".odp", IsText = false, PrimaryMimeType = "application/vnd.oasis.opendocument.presentation", SecondaryMimeTypes = "zip" } },
				{ ".ods", new MimeType { FileExtension = ".ods", IsText = false, PrimaryMimeType = "application/oleobject", SecondaryMimeTypes = "zip" } },
				{ ".odt", new MimeType { FileExtension = ".odt", IsText = false, PrimaryMimeType = "application/vnd.oasis.opendocument.text", SecondaryMimeTypes = "zip" } },
				{ ".one", new MimeType { FileExtension = ".one", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onea", new MimeType { FileExtension = ".onea", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onepkg", new MimeType { FileExtension = ".onepkg", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetmp", new MimeType { FileExtension = ".onetmp", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetoc", new MimeType { FileExtension = ".onetoc", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetoc2", new MimeType { FileExtension = ".onetoc2", IsText = false, PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".orderedtest", new MimeType { FileExtension = ".orderedtest", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".osdx", new MimeType { FileExtension = ".osdx", IsText = false, PrimaryMimeType = "application/opensearchdescription+xml", SecondaryMimeTypes = "" } },
				{ ".p10", new MimeType { FileExtension = ".p10", IsText = false, PrimaryMimeType = "application/pkcs10", SecondaryMimeTypes = "" } },
				{ ".p12", new MimeType { FileExtension = ".p12", IsText = false, PrimaryMimeType = "application/x-pkcs12", SecondaryMimeTypes = "" } },
				{ ".p7b", new MimeType { FileExtension = ".p7b", IsText = false, PrimaryMimeType = "application/x-pkcs7-certificates", SecondaryMimeTypes = "" } },
				{ ".p7c", new MimeType { FileExtension = ".p7c", IsText = false, PrimaryMimeType = "application/pkcs7-mime", SecondaryMimeTypes = "" } },
				{ ".p7m", new MimeType { FileExtension = ".p7m", IsText = false, PrimaryMimeType = "application/pkcs7-mime", SecondaryMimeTypes = "" } },
				{ ".p7r", new MimeType { FileExtension = ".p7r", IsText = false, PrimaryMimeType = "application/x-pkcs7-certreqresp", SecondaryMimeTypes = "" } },
				{ ".p7s", new MimeType { FileExtension = ".p7s", IsText = false, PrimaryMimeType = "application/pkcs7-signature", SecondaryMimeTypes = "" } },
				{ ".pbm", new MimeType { FileExtension = ".pbm", IsText = false, PrimaryMimeType = "image/x-portable-bitmap", SecondaryMimeTypes = "" } },
				{ ".pcast", new MimeType { FileExtension = ".pcast", IsText = false, PrimaryMimeType = "application/x-podcast", SecondaryMimeTypes = "" } },
				{ ".pct", new MimeType { FileExtension = ".pct", IsText = false, PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pcx", new MimeType { FileExtension = ".pcx", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pcz", new MimeType { FileExtension = ".pcz", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pdf", new MimeType { FileExtension = ".pdf", IsText = false, PrimaryMimeType = "application/pdf", SecondaryMimeTypes = "" } },
				{ ".pfb", new MimeType { FileExtension = ".pfb", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pfm", new MimeType { FileExtension = ".pfm", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pfx", new MimeType { FileExtension = ".pfx", IsText = false, PrimaryMimeType = "application/x-pkcs12", SecondaryMimeTypes = "" } },
				{ ".pgm", new MimeType { FileExtension = ".pgm", IsText = false, PrimaryMimeType = "image/x-portable-graymap", SecondaryMimeTypes = "" } },
				{ ".pic", new MimeType { FileExtension = ".pic", IsText = false, PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pict", new MimeType { FileExtension = ".pict", IsText = false, PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pkgdef", new MimeType { FileExtension = ".pkgdef", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pkgundef", new MimeType { FileExtension = ".pkgundef", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pko", new MimeType { FileExtension = ".pko", IsText = false, PrimaryMimeType = "application/vnd.ms-pki.pko", SecondaryMimeTypes = "" } },
				{ ".pls", new MimeType { FileExtension = ".pls", IsText = false, PrimaryMimeType = "audio/scpls", SecondaryMimeTypes = "" } },
				{ ".pma", new MimeType { FileExtension = ".pma", IsText = false, PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmc", new MimeType { FileExtension = ".pmc", IsText = false, PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pml", new MimeType { FileExtension = ".pml", IsText = false, PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmr", new MimeType { FileExtension = ".pmr", IsText = false, PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmw", new MimeType { FileExtension = ".pmw", IsText = false, PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".png", new MimeType { FileExtension = ".png", IsText = false, PrimaryMimeType = "image/png", SecondaryMimeTypes = "png" } },
				{ ".pngCustom", new MimeType { FileExtension = ".png", IsText = false, PrimaryMimeType = "image/x-png", SecondaryMimeTypes = "png" } },
				{ ".pnm", new MimeType { FileExtension = ".pnm", IsText = false, PrimaryMimeType = "image/x-portable-anymap", SecondaryMimeTypes = "" } },
				{ ".pnt", new MimeType { FileExtension = ".pnt", IsText = false, PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".pntg", new MimeType { FileExtension = ".pntg", IsText = false, PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".pnz", new MimeType { FileExtension = ".pnz", IsText = false, PrimaryMimeType = "image/png", SecondaryMimeTypes = "" } },
				{ ".pot", new MimeType { FileExtension = ".pot", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".potm", new MimeType { FileExtension = ".potm", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".potx", new MimeType { FileExtension = ".potx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.template", SecondaryMimeTypes = "zip" } },
				{ ".ppa", new MimeType { FileExtension = ".ppa", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".ppam", new MimeType { FileExtension = ".ppam", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint.addin.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".ppm", new MimeType { FileExtension = ".ppm", IsText = false, PrimaryMimeType = "image/x-portable-pixmap", SecondaryMimeTypes = "" } },
				{ ".pps", new MimeType { FileExtension = ".pps", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".ppsm", new MimeType { FileExtension = ".ppsm", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint.slideshow.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".ppsx", new MimeType { FileExtension = ".ppsx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.slideshow", SecondaryMimeTypes = "zip" } },
				{ ".ppt", new MimeType { FileExtension = ".ppt", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".pptm", new MimeType { FileExtension = ".pptm", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint.presentation.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".pptx", new MimeType { FileExtension = ".pptx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation", SecondaryMimeTypes = "zip" } },
				{ ".prf", new MimeType { FileExtension = ".prf", IsText = false, PrimaryMimeType = "application/pics-rules", SecondaryMimeTypes = "" } },
				{ ".prm", new MimeType { FileExtension = ".prm", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".prx", new MimeType { FileExtension = ".prx", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ps", new MimeType { FileExtension = ".ps", IsText = false, PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".psc1", new MimeType { FileExtension = ".psc1", IsText = false, PrimaryMimeType = "application/PowerShell", SecondaryMimeTypes = "" } },
				{ ".psd", new MimeType { FileExtension = ".psd", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".psess", new MimeType { FileExtension = ".psess", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".psm", new MimeType { FileExtension = ".psm", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".psp", new MimeType { FileExtension = ".psp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".pub", new MimeType { FileExtension = ".pub", IsText = false, PrimaryMimeType = "application/x-mspublisher", SecondaryMimeTypes = "" } },
				{ ".pwz", new MimeType { FileExtension = ".pwz", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".qht", new MimeType { FileExtension = ".qht", IsText = true, PrimaryMimeType = "text/x-html-insertion", SecondaryMimeTypes = "" } },
				{ ".qhtm", new MimeType { FileExtension = ".qhtm", IsText = true, PrimaryMimeType = "text/x-html-insertion", SecondaryMimeTypes = "" } },
				{ ".qt", new MimeType { FileExtension = ".qt", IsText = false, PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".qti", new MimeType { FileExtension = ".qti", IsText = false, PrimaryMimeType = "image/x-quicktime", SecondaryMimeTypes = "" } },
				{ ".qtif", new MimeType { FileExtension = ".qtif", IsText = false, PrimaryMimeType = "image/x-quicktime", SecondaryMimeTypes = "" } },
				{ ".qtl", new MimeType { FileExtension = ".qtl", IsText = false, PrimaryMimeType = "application/x-quicktimeplayer", SecondaryMimeTypes = "" } },
				{ ".qxd", new MimeType { FileExtension = ".qxd", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ra", new MimeType { FileExtension = ".ra", IsText = false, PrimaryMimeType = "audio/x-pn-realaudio", SecondaryMimeTypes = "" } },
				{ ".ram", new MimeType { FileExtension = ".ram", IsText = false, PrimaryMimeType = "audio/x-pn-realaudio", SecondaryMimeTypes = "" } },
				{ ".rar", new MimeType { FileExtension = ".rar", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ras", new MimeType { FileExtension = ".ras", IsText = false, PrimaryMimeType = "image/x-cmu-raster", SecondaryMimeTypes = "" } },
				{ ".rat", new MimeType { FileExtension = ".rat", IsText = false, PrimaryMimeType = "application/rat-file", SecondaryMimeTypes = "" } },
				{ ".rc", new MimeType { FileExtension = ".rc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".rc2", new MimeType { FileExtension = ".rc2", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".rct", new MimeType { FileExtension = ".rct", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".rdlc", new MimeType { FileExtension = ".rdlc", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".resx", new MimeType { FileExtension = ".resx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".rf", new MimeType { FileExtension = ".rf", IsText = false, PrimaryMimeType = "image/vnd.rn-realflash", SecondaryMimeTypes = "" } },
				{ ".rgb", new MimeType { FileExtension = ".rgb", IsText = false, PrimaryMimeType = "image/x-rgb", SecondaryMimeTypes = "" } },
				{ ".rgs", new MimeType { FileExtension = ".rgs", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".rm", new MimeType { FileExtension = ".rm", IsText = false, PrimaryMimeType = "application/vnd.rn-realmedia", SecondaryMimeTypes = "" } },
				{ ".rmi", new MimeType { FileExtension = ".rmi", IsText = false, PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".rmp", new MimeType { FileExtension = ".rmp", IsText = false, PrimaryMimeType = "application/vnd.rn-rn_music_package", SecondaryMimeTypes = "" } },
				{ ".roff", new MimeType { FileExtension = ".roff", IsText = false, PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".rpm", new MimeType { FileExtension = ".rpm", IsText = false, PrimaryMimeType = "audio/x-pn-realaudio-plugin", SecondaryMimeTypes = "" } },
				{ ".rqy", new MimeType { FileExtension = ".rqy", IsText = true, PrimaryMimeType = "text/x-ms-rqy", SecondaryMimeTypes = "" } },
				{ ".rtf", new MimeType { FileExtension = ".rtf", IsText = false, PrimaryMimeType = "application/rtf", SecondaryMimeTypes = "rtf" } },
				{ ".rtx", new MimeType { FileExtension = ".rtx", IsText = true, PrimaryMimeType = "text/richtext", SecondaryMimeTypes = "rtf" } },
				{ ".ruleset", new MimeType { FileExtension = ".ruleset", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".s", new MimeType { FileExtension = ".s", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".safariextz", new MimeType { FileExtension = ".safariextz", IsText = false, PrimaryMimeType = "application/x-safari-safariextz", SecondaryMimeTypes = "" } },
				{ ".scd", new MimeType { FileExtension = ".scd", IsText = false, PrimaryMimeType = "application/x-msschedule", SecondaryMimeTypes = "" } },
				{ ".sct", new MimeType { FileExtension = ".sct", IsText = true, PrimaryMimeType = "text/scriptlet", SecondaryMimeTypes = "" } },
				{ ".sd2", new MimeType { FileExtension = ".sd2", IsText = false, PrimaryMimeType = "audio/x-sd2", SecondaryMimeTypes = "" } },
				{ ".sdp", new MimeType { FileExtension = ".sdp", IsText = false, PrimaryMimeType = "application/sdp", SecondaryMimeTypes = "" } },
				{ ".sea", new MimeType { FileExtension = ".sea", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".searchConnector-ms", new MimeType { FileExtension = ".searchConnector-ms", IsText = false, PrimaryMimeType = "application/windows-search-connector+xml", SecondaryMimeTypes = "" } },
				{ ".setpay", new MimeType { FileExtension = ".setpay", IsText = false, PrimaryMimeType = "application/set-payment-initiation", SecondaryMimeTypes = "" } },
				{ ".setreg", new MimeType { FileExtension = ".setreg", IsText = false, PrimaryMimeType = "application/set-registration-initiation", SecondaryMimeTypes = "" } },
				{ ".settings", new MimeType { FileExtension = ".settings", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".sgimb", new MimeType { FileExtension = ".sgimb", IsText = false, PrimaryMimeType = "application/x-sgimb", SecondaryMimeTypes = "" } },
				{ ".sgml", new MimeType { FileExtension = ".sgml", IsText = true, PrimaryMimeType = "text/sgml", SecondaryMimeTypes = "" } },
				{ ".sh", new MimeType { FileExtension = ".sh", IsText = true, PrimaryMimeType = "application/x-sh", SecondaryMimeTypes = "" } },
				{ ".shar", new MimeType { FileExtension = ".shar", IsText = false, PrimaryMimeType = "application/x-shar", SecondaryMimeTypes = "" } },
				{ ".shtml", new MimeType { FileExtension = ".shtml", IsText = true, PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".sit", new MimeType { FileExtension = ".sit", IsText = false, PrimaryMimeType = "application/x-stuffit", SecondaryMimeTypes = "" } },
				{ ".sitemap", new MimeType { FileExtension = ".sitemap", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".skin", new MimeType { FileExtension = ".skin", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".sldm", new MimeType { FileExtension = ".sldm", IsText = false, PrimaryMimeType = "application/vnd.ms-powerpoint.slide.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".sldx", new MimeType { FileExtension = ".sldx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.slide", SecondaryMimeTypes = "" } },
				{ ".slk", new MimeType { FileExtension = ".slk", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".sln", new MimeType { FileExtension = ".sln", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".slupkg-ms", new MimeType { FileExtension = ".slupkg-ms", IsText = false, PrimaryMimeType = "application/x-ms-license", SecondaryMimeTypes = "" } },
				{ ".smd", new MimeType { FileExtension = ".smd", IsText = false, PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".smi", new MimeType { FileExtension = ".smi", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".smx", new MimeType { FileExtension = ".smx", IsText = false, PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".smz", new MimeType { FileExtension = ".smz", IsText = false, PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".snd", new MimeType { FileExtension = ".snd", IsText = false, PrimaryMimeType = "audio/basic", SecondaryMimeTypes = "" } },
				{ ".snippet", new MimeType { FileExtension = ".snippet", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".snp", new MimeType { FileExtension = ".snp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".sol", new MimeType { FileExtension = ".sol", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".sor", new MimeType { FileExtension = ".sor", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".spc", new MimeType { FileExtension = ".spc", IsText = false, PrimaryMimeType = "application/x-pkcs7-certificates", SecondaryMimeTypes = "" } },
				{ ".spl", new MimeType { FileExtension = ".spl", IsText = false, PrimaryMimeType = "application/futuresplash", SecondaryMimeTypes = "" } },
				{ ".src", new MimeType { FileExtension = ".src", IsText = false, PrimaryMimeType = "application/x-wais-source", SecondaryMimeTypes = "" } },
				{ ".srf", new MimeType { FileExtension = ".srf", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".SSISDeploymentManifest", new MimeType { FileExtension = ".SSISDeploymentManifest", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".ssm", new MimeType { FileExtension = ".ssm", IsText = false, PrimaryMimeType = "application/streamingmedia", SecondaryMimeTypes = "" } },
				{ ".sst", new MimeType { FileExtension = ".sst", IsText = false, PrimaryMimeType = "application/vnd.ms-pki.certstore", SecondaryMimeTypes = "" } },
				{ ".stl", new MimeType { FileExtension = ".stl", IsText = false, PrimaryMimeType = "application/vnd.ms-pki.stl", SecondaryMimeTypes = "" } },
				{ ".sv4cpio", new MimeType { FileExtension = ".sv4cpio", IsText = false, PrimaryMimeType = "application/x-sv4cpio", SecondaryMimeTypes = "" } },
				{ ".sv4crc", new MimeType { FileExtension = ".sv4crc", IsText = false, PrimaryMimeType = "application/x-sv4crc", SecondaryMimeTypes = "" } },
				{ ".svc", new MimeType { FileExtension = ".svc", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".swf", new MimeType { FileExtension = ".swf", IsText = false, PrimaryMimeType = "application/x-shockwave-flash", SecondaryMimeTypes = "" } },
				{ ".t", new MimeType { FileExtension = ".t", IsText = false, PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".tar", new MimeType { FileExtension = ".tar", IsText = false, PrimaryMimeType = "application/x-tar", SecondaryMimeTypes = "" } },
				{ ".tcl", new MimeType { FileExtension = ".tcl", IsText = false, PrimaryMimeType = "application/x-tcl", SecondaryMimeTypes = "" } },
				{ ".testrunconfig", new MimeType { FileExtension = ".testrunconfig", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".testsettings", new MimeType { FileExtension = ".testsettings", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".tex", new MimeType { FileExtension = ".tex", IsText = false, PrimaryMimeType = "application/x-tex", SecondaryMimeTypes = "" } },
				{ ".texi", new MimeType { FileExtension = ".texi", IsText = false, PrimaryMimeType = "application/x-texinfo", SecondaryMimeTypes = "" } },
				{ ".texinfo", new MimeType { FileExtension = ".texinfo", IsText = false, PrimaryMimeType = "application/x-texinfo", SecondaryMimeTypes = "" } },
				{ ".tgz", new MimeType { FileExtension = ".tgz", IsText = false, PrimaryMimeType = "application/x-compressed", SecondaryMimeTypes = "" } },
				{ ".thmx", new MimeType { FileExtension = ".thmx", IsText = false, PrimaryMimeType = "application/vnd.ms-officetheme", SecondaryMimeTypes = "" } },
				{ ".thn", new MimeType { FileExtension = ".thn", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".tif", new MimeType { FileExtension = ".tif", IsText = false, PrimaryMimeType = "image/tiff", SecondaryMimeTypes = "" } },
				{ ".tiff", new MimeType { FileExtension = ".tiff", IsText = false, PrimaryMimeType = "image/tiff", SecondaryMimeTypes = "" } },
				{ ".tlh", new MimeType { FileExtension = ".tlh", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".tli", new MimeType { FileExtension = ".tli", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".toc", new MimeType { FileExtension = ".toc", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".tr", new MimeType { FileExtension = ".tr", IsText = false, PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".trm", new MimeType { FileExtension = ".trm", IsText = false, PrimaryMimeType = "application/x-msterminal", SecondaryMimeTypes = "" } },
				{ ".trx", new MimeType { FileExtension = ".trx", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".ts", new MimeType { FileExtension = ".ts", IsText = false, PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".tsv", new MimeType { FileExtension = ".tsv", IsText = true, PrimaryMimeType = "text/tab-separated-values", SecondaryMimeTypes = "" } },
				{ ".ttf", new MimeType { FileExtension = ".ttf", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".tts", new MimeType { FileExtension = ".tts", IsText = false, PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".txt", new MimeType { FileExtension = ".txt", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".u32", new MimeType { FileExtension = ".u32", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".uls", new MimeType { FileExtension = ".uls", IsText = true, PrimaryMimeType = "text/iuls", SecondaryMimeTypes = "" } },
				{ ".user", new MimeType { FileExtension = ".user", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".ustar", new MimeType { FileExtension = ".ustar", IsText = false, PrimaryMimeType = "application/x-ustar", SecondaryMimeTypes = "" } },
				{ ".vb", new MimeType { FileExtension = ".vb", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vbdproj", new MimeType { FileExtension = ".vbdproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vbk", new MimeType { FileExtension = ".vbk", IsText = false, PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".vbproj", new MimeType { FileExtension = ".vbproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vbs", new MimeType { FileExtension = ".vbs", IsText = true, PrimaryMimeType = "text/vbscript", SecondaryMimeTypes = "" } },
				{ ".vcf", new MimeType { FileExtension = ".vcf", IsText = true, PrimaryMimeType = "text/x-vcard", SecondaryMimeTypes = "" } },
				{ ".vcproj", new MimeType { FileExtension = ".vcproj", IsText = true, PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".vcs", new MimeType { FileExtension = ".vcs", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vcxproj", new MimeType { FileExtension = ".vcxproj", IsText = true, PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".vddproj", new MimeType { FileExtension = ".vddproj", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vdp", new MimeType { FileExtension = ".vdp", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vdproj", new MimeType { FileExtension = ".vdproj", IsText = false, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vdx", new MimeType { FileExtension = ".vdx", IsText = false, PrimaryMimeType = "application/vnd.ms-visio.viewer", SecondaryMimeTypes = "" } },
				{ ".vml", new MimeType { FileExtension = ".vml", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vscontent", new MimeType { FileExtension = ".vscontent", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".vsct", new MimeType { FileExtension = ".vsct", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsd", new MimeType { FileExtension = ".vsd", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsi", new MimeType { FileExtension = ".vsi", IsText = false, PrimaryMimeType = "application/ms-vsi", SecondaryMimeTypes = "" } },
				{ ".vsix", new MimeType { FileExtension = ".vsix", IsText = false, PrimaryMimeType = "application/vsix", SecondaryMimeTypes = "" } },
				{ ".vsixlangpack", new MimeType { FileExtension = ".vsixlangpack", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsixmanifest", new MimeType { FileExtension = ".vsixmanifest", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsmdi", new MimeType { FileExtension = ".vsmdi", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".vspscc", new MimeType { FileExtension = ".vspscc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vss", new MimeType { FileExtension = ".vss", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsscc", new MimeType { FileExtension = ".vsscc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vssettings", new MimeType { FileExtension = ".vssettings", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vssscc", new MimeType { FileExtension = ".vssscc", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".vst", new MimeType { FileExtension = ".vst", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vstemplate", new MimeType { FileExtension = ".vstemplate", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsto", new MimeType { FileExtension = ".vsto", IsText = false, PrimaryMimeType = "application/x-ms-vsto", SecondaryMimeTypes = "" } },
				{ ".vsw", new MimeType { FileExtension = ".vsw", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsx", new MimeType { FileExtension = ".vsx", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vtx", new MimeType { FileExtension = ".vtx", IsText = false, PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".wav", new MimeType { FileExtension = ".wav", IsText = false, PrimaryMimeType = "audio/wav", SecondaryMimeTypes = "" } },
				{ ".wave", new MimeType { FileExtension = ".wave", IsText = false, PrimaryMimeType = "audio/wav", SecondaryMimeTypes = "" } },
				{ ".wax", new MimeType { FileExtension = ".wax", IsText = false, PrimaryMimeType = "audio/x-ms-wax", SecondaryMimeTypes = "" } },
				{ ".wbk", new MimeType { FileExtension = ".wbk", IsText = false, PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".wbmp", new MimeType { FileExtension = ".wbmp", IsText = false, PrimaryMimeType = "image/vnd.wap.wbmp", SecondaryMimeTypes = "" } },
				{ ".wcm", new MimeType { FileExtension = ".wcm", IsText = false, PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wdb", new MimeType { FileExtension = ".wdb", IsText = false, PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wdp", new MimeType { FileExtension = ".wdp", IsText = false, PrimaryMimeType = "image/vnd.ms-photo", SecondaryMimeTypes = "" } },
				{ ".webarchive", new MimeType { FileExtension = ".webarchive", IsText = false, PrimaryMimeType = "application/x-safari-webarchive", SecondaryMimeTypes = "" } },
				{ ".webtest", new MimeType { FileExtension = ".webtest", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".wiq", new MimeType { FileExtension = ".wiq", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".wiz", new MimeType { FileExtension = ".wiz", IsText = false, PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".wks", new MimeType { FileExtension = ".wks", IsText = false, PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".WLMP", new MimeType { FileExtension = ".WLMP", IsText = false, PrimaryMimeType = "application/wlmoviemaker", SecondaryMimeTypes = "" } },
				{ ".wlpginstall", new MimeType { FileExtension = ".wlpginstall", IsText = false, PrimaryMimeType = "application/x-wlpg-detect", SecondaryMimeTypes = "" } },
				{ ".wlpginstall3", new MimeType { FileExtension = ".wlpginstall3", IsText = false, PrimaryMimeType = "application/x-wlpg3-detect", SecondaryMimeTypes = "" } },
				{ ".wm", new MimeType { FileExtension = ".wm", IsText = false, PrimaryMimeType = "video/x-ms-wm", SecondaryMimeTypes = "" } },
				{ ".wma", new MimeType { FileExtension = ".wma", IsText = false, PrimaryMimeType = "audio/x-ms-wma", SecondaryMimeTypes = "" } },
				{ ".wmd", new MimeType { FileExtension = ".wmd", IsText = false, PrimaryMimeType = "application/x-ms-wmd", SecondaryMimeTypes = "" } },
				{ ".wmf", new MimeType { FileExtension = ".wmf", IsText = false, PrimaryMimeType = "application/x-msmetafile", SecondaryMimeTypes = "" } },
				{ ".wml", new MimeType { FileExtension = ".wml", IsText = true, PrimaryMimeType = "text/vnd.wap.wml", SecondaryMimeTypes = "" } },
				{ ".wmlc", new MimeType { FileExtension = ".wmlc", IsText = false, PrimaryMimeType = "application/vnd.wap.wmlc", SecondaryMimeTypes = "" } },
				{ ".wmls", new MimeType { FileExtension = ".wmls", IsText = true, PrimaryMimeType = "text/vnd.wap.wmlscript", SecondaryMimeTypes = "" } },
				{ ".wmlsc", new MimeType { FileExtension = ".wmlsc", IsText = false, PrimaryMimeType = "application/vnd.wap.wmlscriptc", SecondaryMimeTypes = "" } },
				{ ".wmp", new MimeType { FileExtension = ".wmp", IsText = false, PrimaryMimeType = "video/x-ms-wmp", SecondaryMimeTypes = "" } },
				{ ".wmv", new MimeType { FileExtension = ".wmv", IsText = false, PrimaryMimeType = "video/x-ms-wmv", SecondaryMimeTypes = "" } },
				{ ".wmx", new MimeType { FileExtension = ".wmx", IsText = false, PrimaryMimeType = "video/x-ms-wmx", SecondaryMimeTypes = "" } },
				{ ".wmz", new MimeType { FileExtension = ".wmz", IsText = false, PrimaryMimeType = "application/x-ms-wmz", SecondaryMimeTypes = "" } },
				{ ".wpl", new MimeType { FileExtension = ".wpl", IsText = false, PrimaryMimeType = "application/vnd.ms-wpl", SecondaryMimeTypes = "" } },
				{ ".wps", new MimeType { FileExtension = ".wps", IsText = false, PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wri", new MimeType { FileExtension = ".wri", IsText = false, PrimaryMimeType = "application/x-mswrite", SecondaryMimeTypes = "" } },
				{ ".wrl", new MimeType { FileExtension = ".wrl", IsText = false, PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".wrz", new MimeType { FileExtension = ".wrz", IsText = false, PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".wsc", new MimeType { FileExtension = ".wsc", IsText = true, PrimaryMimeType = "text/scriptlet", SecondaryMimeTypes = "" } },
				{ ".wsdl", new MimeType { FileExtension = ".wsdl", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".wvx", new MimeType { FileExtension = ".wvx", IsText = false, PrimaryMimeType = "video/x-ms-wvx", SecondaryMimeTypes = "" } },
				{ ".x", new MimeType { FileExtension = ".x", IsText = false, PrimaryMimeType = "application/directx", SecondaryMimeTypes = "" } },
				{ ".xaf", new MimeType { FileExtension = ".xaf", IsText = false, PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".xaml", new MimeType { FileExtension = ".xaml", IsText = false, PrimaryMimeType = "application/xaml+xml", SecondaryMimeTypes = "" } },
				{ ".xap", new MimeType { FileExtension = ".xap", IsText = false, PrimaryMimeType = "application/x-silverlight-app", SecondaryMimeTypes = "" } },
				{ ".xbap", new MimeType { FileExtension = ".xbap", IsText = false, PrimaryMimeType = "application/x-ms-xbap", SecondaryMimeTypes = "" } },
				{ ".xbm", new MimeType { FileExtension = ".xbm", IsText = false, PrimaryMimeType = "image/x-xbitmap", SecondaryMimeTypes = "" } },
				{ ".xdr", new MimeType { FileExtension = ".xdr", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".xht", new MimeType { FileExtension = ".xht", IsText = false, PrimaryMimeType = "application/xhtml+xml", SecondaryMimeTypes = "" } },
				{ ".xhtml", new MimeType { FileExtension = ".xhtml", IsText = false, PrimaryMimeType = "application/xhtml+xml", SecondaryMimeTypes = "" } },
				{ ".xla", new MimeType { FileExtension = ".xla", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlam", new MimeType { FileExtension = ".xlam", IsText = false, PrimaryMimeType = "application/vnd.ms-excel.addin.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlc", new MimeType { FileExtension = ".xlc", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xld", new MimeType { FileExtension = ".xld", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlk", new MimeType { FileExtension = ".xlk", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xll", new MimeType { FileExtension = ".xll", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlm", new MimeType { FileExtension = ".xlm", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xls", new MimeType { FileExtension = ".xls", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlsb", new MimeType { FileExtension = ".xlsb", IsText = false, PrimaryMimeType = "application/vnd.ms-excel.sheet.binary.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlsm", new MimeType { FileExtension = ".xlsm", IsText = false, PrimaryMimeType = "application/vnd.ms-excel.sheet.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlsx", new MimeType { FileExtension = ".xlsx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", SecondaryMimeTypes = "zip" } },
				{ ".xlt", new MimeType { FileExtension = ".xlt", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xltm", new MimeType { FileExtension = ".xltm", IsText = false, PrimaryMimeType = "application/vnd.ms-excel.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xltx", new MimeType { FileExtension = ".xltx", IsText = false, PrimaryMimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.template", SecondaryMimeTypes = "zip" } },
				{ ".xlw", new MimeType { FileExtension = ".xlw", IsText = false, PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xml", new MimeType { FileExtension = ".xml", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xmta", new MimeType { FileExtension = ".xmta", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xof", new MimeType { FileExtension = ".xof", IsText = false, PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".XOML", new MimeType { FileExtension = ".XOML", IsText = true, PrimaryMimeType = TextMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".xpm", new MimeType { FileExtension = ".xpm", IsText = false, PrimaryMimeType = "image/x-xpixmap", SecondaryMimeTypes = "" } },
				{ ".xps", new MimeType { FileExtension = ".xps", IsText = false, PrimaryMimeType = "application/vnd.ms-xpsdocument", SecondaryMimeTypes = "" } },
				{ ".xrm-ms", new MimeType { FileExtension = ".xrm-ms", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsc", new MimeType { FileExtension = ".xsc", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xsd", new MimeType { FileExtension = ".xsd", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsf", new MimeType { FileExtension = ".xsf", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsl", new MimeType { FileExtension = ".xsl", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xslt", new MimeType { FileExtension = ".xslt", IsText = true, PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsn", new MimeType { FileExtension = ".xsn", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".xss", new MimeType { FileExtension = ".xss", IsText = true, PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xtp", new MimeType { FileExtension = ".xtp", IsText = false, PrimaryMimeType = BinaryMimeTypeName, SecondaryMimeTypes = "" } },
				{ ".xwd", new MimeType { FileExtension = ".xwd", IsText = false, PrimaryMimeType = "image/x-xwindowdump", SecondaryMimeTypes = "" } },
				{ ".z", new MimeType { FileExtension = ".z", IsText = false, PrimaryMimeType = "application/x-compress", SecondaryMimeTypes = "" } },
				{ ".zip", new MimeType { FileExtension = ".zip", IsText = false, PrimaryMimeType = "application/x-zip-compressed", SecondaryMimeTypes = "zip" } },
			};

			ms_oMimeTypeMap = new SortedDictionary<string, MimeType>();

			foreach (KeyValuePair<string, MimeType> pair in ms_oFileExtMap) {
				string sMimeType = pair.Value.PrimaryMimeType;

				if (ms_oMimeTypeMap.ContainsKey(sMimeType))
					ms_oMimeTypeMap[sMimeType].AddSecondary(pair.Value);
				else
					ms_oMimeTypeMap[sMimeType] = pair.Value.CloneSecondary();
			} // for each
		} // static constructor

		public const string BinaryMimeTypeName = "application/octet-stream";
		public const string TextMimeTypeName = "text/plain";

		public MimeType Find(string sMimeType) {
			MimeType oType = null;

			if (!string.IsNullOrWhiteSpace(sMimeType))
				ms_oMimeTypeMap.TryGetValue(sMimeType, out oType);

			return oType;
		} // Find

		public MimeType Get(string sFileName) {
			string sExtension = null;

			if (!string.IsNullOrWhiteSpace(sFileName)) {
				int nPos = sFileName.LastIndexOf('.');

				if (nPos >= 0)
					sExtension = sFileName.Substring(nPos);
			} // if

			sExtension = (sExtension ?? string.Empty).Trim();

			if (!sExtension.StartsWith("."))
				sExtension = "." + sExtension;

			MimeType oMimeType;

			if (ms_oFileExtMap.TryGetValue(sExtension.ToLowerInvariant(), out oMimeType))
				return oMimeType;

			return null;
		} // Get

		public string this[string sExtension] {
			get {
				sExtension = (sExtension ?? string.Empty).Trim();

				if (!sExtension.StartsWith("."))
					sExtension = "." + sExtension;

				MimeType oMimeType;

				return ms_oFileExtMap.TryGetValue(sExtension.ToLowerInvariant(), out oMimeType) ? oMimeType.PrimaryMimeType : BinaryMimeTypeName;
			} // get
		} // indexer

		public string GetFromFile(byte[] oBuffer, int? nBufferLength = 256) {
			try {
				System.UInt32 oMimeType;

				int nBufLen = nBufferLength ?? oBuffer.Length;

				if ((nBufLen <= 0) || (nBufLen > oBuffer.Length))
					nBufLen = oBuffer.Length;

				FindMimeFromData(0, null, oBuffer, (uint)nBufLen, null, 0, out oMimeType, 0);

				System.IntPtr pMimeType = new IntPtr(oMimeType);

				string sMimeType = Marshal.PtrToStringUni(pMimeType);

				Marshal.FreeCoTaskMem(pMimeType);

				return sMimeType;
			}
			catch (Exception) {
				return null;
			} // try
		} // GetFromFile

		private static readonly SortedDictionary<string, MimeType> ms_oFileExtMap;
		private static readonly SortedDictionary<string, MimeType> ms_oMimeTypeMap;

		[DllImport(@"urlmon.dll", CharSet = CharSet.Auto)]
		private extern static System.UInt32 FindMimeFromData(
			System.UInt32 pBC,
			[MarshalAs(UnmanagedType.LPStr)] System.String pwzUrl,
			[MarshalAs(UnmanagedType.LPArray)] byte[] pBuffer,
			System.UInt32 cbSize,
			[MarshalAs(UnmanagedType.LPStr)] System.String pwzMimeProposed,
			System.UInt32 dwMimeFlags,
			out System.UInt32 ppwzMimeOut,
			System.UInt32 dwReserverd
		);

	} // class MimeTypeResolver
} // namespace
