namespace Ezbob.Utils.MimeTypes {
	using System;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

	public class MimeTypeResolver {
		#region static constructor

		static MimeTypeResolver() {
			#region init file extension map

			ms_oFileExtMap = new SortedDictionary<string, MimeType> {
				{ ".323", new MimeType { FileExtension = ".323", PrimaryMimeType = "text/h323", SecondaryMimeTypes = "" } },
				{ ".3g2", new MimeType { FileExtension = ".3g2", PrimaryMimeType = "video/3gpp2", SecondaryMimeTypes = "" } },
				{ ".3gp", new MimeType { FileExtension = ".3gp", PrimaryMimeType = "video/3gpp", SecondaryMimeTypes = "" } },
				{ ".3gp2", new MimeType { FileExtension = ".3gp2", PrimaryMimeType = "video/3gpp2", SecondaryMimeTypes = "" } },
				{ ".3gpp", new MimeType { FileExtension = ".3gpp", PrimaryMimeType = "video/3gpp", SecondaryMimeTypes = "" } },
				{ ".7z", new MimeType { FileExtension = ".7z", PrimaryMimeType = "application/x-7z-compressed", SecondaryMimeTypes = "" } },
				{ ".aa", new MimeType { FileExtension = ".aa", PrimaryMimeType = "audio/audible", SecondaryMimeTypes = "" } },
				{ ".AAC", new MimeType { FileExtension = ".AAC", PrimaryMimeType = "audio/aac", SecondaryMimeTypes = "" } },
				{ ".aaf", new MimeType { FileExtension = ".aaf", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".aax", new MimeType { FileExtension = ".aax", PrimaryMimeType = "audio/vnd.audible.aax", SecondaryMimeTypes = "" } },
				{ ".ac3", new MimeType { FileExtension = ".ac3", PrimaryMimeType = "audio/ac3", SecondaryMimeTypes = "" } },
				{ ".aca", new MimeType { FileExtension = ".aca", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".accda", new MimeType { FileExtension = ".accda", PrimaryMimeType = "application/msaccess.addin", SecondaryMimeTypes = "" } },
				{ ".accdb", new MimeType { FileExtension = ".accdb", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdc", new MimeType { FileExtension = ".accdc", PrimaryMimeType = "application/msaccess.cab", SecondaryMimeTypes = "" } },
				{ ".accde", new MimeType { FileExtension = ".accde", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdr", new MimeType { FileExtension = ".accdr", PrimaryMimeType = "application/msaccess.runtime", SecondaryMimeTypes = "" } },
				{ ".accdt", new MimeType { FileExtension = ".accdt", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".accdw", new MimeType { FileExtension = ".accdw", PrimaryMimeType = "application/msaccess.webapplication", SecondaryMimeTypes = "" } },
				{ ".accft", new MimeType { FileExtension = ".accft", PrimaryMimeType = "application/msaccess.ftemplate", SecondaryMimeTypes = "" } },
				{ ".acx", new MimeType { FileExtension = ".acx", PrimaryMimeType = "application/internet-property-stream", SecondaryMimeTypes = "" } },
				{ ".AddIn", new MimeType { FileExtension = ".AddIn", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".ade", new MimeType { FileExtension = ".ade", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".adobebridge", new MimeType { FileExtension = ".adobebridge", PrimaryMimeType = "application/x-bridge-url", SecondaryMimeTypes = "" } },
				{ ".adp", new MimeType { FileExtension = ".adp", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".ADT", new MimeType { FileExtension = ".ADT", PrimaryMimeType = "audio/vnd.dlna.adts", SecondaryMimeTypes = "" } },
				{ ".ADTS", new MimeType { FileExtension = ".ADTS", PrimaryMimeType = "audio/aac", SecondaryMimeTypes = "" } },
				{ ".afm", new MimeType { FileExtension = ".afm", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".ai", new MimeType { FileExtension = ".ai", PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".aif", new MimeType { FileExtension = ".aif", PrimaryMimeType = "audio/x-aiff", SecondaryMimeTypes = "" } },
				{ ".aifc", new MimeType { FileExtension = ".aifc", PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".aiff", new MimeType { FileExtension = ".aiff", PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".air", new MimeType { FileExtension = ".air", PrimaryMimeType = "application/vnd.adobe.air-application-installer-package+zip", SecondaryMimeTypes = "" } },
				{ ".amc", new MimeType { FileExtension = ".amc", PrimaryMimeType = "application/x-mpeg", SecondaryMimeTypes = "" } },
				{ ".application", new MimeType { FileExtension = ".application", PrimaryMimeType = "application/x-ms-application", SecondaryMimeTypes = "" } },
				{ ".art", new MimeType { FileExtension = ".art", PrimaryMimeType = "image/x-jg", SecondaryMimeTypes = "" } },
				{ ".asa", new MimeType { FileExtension = ".asa", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asax", new MimeType { FileExtension = ".asax", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".ascx", new MimeType { FileExtension = ".ascx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asd", new MimeType { FileExtension = ".asd", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".asf", new MimeType { FileExtension = ".asf", PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".ashx", new MimeType { FileExtension = ".ashx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asi", new MimeType { FileExtension = ".asi", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".asm", new MimeType { FileExtension = ".asm", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".asmx", new MimeType { FileExtension = ".asmx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".aspx", new MimeType { FileExtension = ".aspx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".asr", new MimeType { FileExtension = ".asr", PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".asx", new MimeType { FileExtension = ".asx", PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".atom", new MimeType { FileExtension = ".atom", PrimaryMimeType = "application/atom+xml", SecondaryMimeTypes = "" } },
				{ ".au", new MimeType { FileExtension = ".au", PrimaryMimeType = "audio/basic", SecondaryMimeTypes = "" } },
				{ ".avi", new MimeType { FileExtension = ".avi", PrimaryMimeType = "video/x-msvideo", SecondaryMimeTypes = "" } },
				{ ".axs", new MimeType { FileExtension = ".axs", PrimaryMimeType = "application/olescript", SecondaryMimeTypes = "" } },
				{ ".bas", new MimeType { FileExtension = ".bas", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".bcpio", new MimeType { FileExtension = ".bcpio", PrimaryMimeType = "application/x-bcpio", SecondaryMimeTypes = "" } },
				{ ".bin", new MimeType { FileExtension = ".bin", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".bmp", new MimeType { FileExtension = ".bmp", PrimaryMimeType = "image/bmp", SecondaryMimeTypes = "" } },
				{ ".c", new MimeType { FileExtension = ".c", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".cab", new MimeType { FileExtension = ".cab", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".caf", new MimeType { FileExtension = ".caf", PrimaryMimeType = "audio/x-caf", SecondaryMimeTypes = "" } },
				{ ".calx", new MimeType { FileExtension = ".calx", PrimaryMimeType = "application/vnd.ms-office.calx", SecondaryMimeTypes = "" } },
				{ ".cat", new MimeType { FileExtension = ".cat", PrimaryMimeType = "application/vnd.ms-pki.seccat", SecondaryMimeTypes = "" } },
				{ ".cc", new MimeType { FileExtension = ".cc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".cd", new MimeType { FileExtension = ".cd", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".cdda", new MimeType { FileExtension = ".cdda", PrimaryMimeType = "audio/aiff", SecondaryMimeTypes = "" } },
				{ ".cdf", new MimeType { FileExtension = ".cdf", PrimaryMimeType = "application/x-cdf", SecondaryMimeTypes = "" } },
				{ ".cer", new MimeType { FileExtension = ".cer", PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".chm", new MimeType { FileExtension = ".chm", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".class", new MimeType { FileExtension = ".class", PrimaryMimeType = "application/x-java-applet", SecondaryMimeTypes = "" } },
				{ ".clp", new MimeType { FileExtension = ".clp", PrimaryMimeType = "application/x-msclip", SecondaryMimeTypes = "" } },
				{ ".cmx", new MimeType { FileExtension = ".cmx", PrimaryMimeType = "image/x-cmx", SecondaryMimeTypes = "" } },
				{ ".cnf", new MimeType { FileExtension = ".cnf", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".cod", new MimeType { FileExtension = ".cod", PrimaryMimeType = "image/cis-cod", SecondaryMimeTypes = "" } },
				{ ".config", new MimeType { FileExtension = ".config", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".contact", new MimeType { FileExtension = ".contact", PrimaryMimeType = "text/x-ms-contact", SecondaryMimeTypes = "" } },
				{ ".coverage", new MimeType { FileExtension = ".coverage", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".cpio", new MimeType { FileExtension = ".cpio", PrimaryMimeType = "application/x-cpio", SecondaryMimeTypes = "" } },
				{ ".cpp", new MimeType { FileExtension = ".cpp", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".crd", new MimeType { FileExtension = ".crd", PrimaryMimeType = "application/x-mscardfile", SecondaryMimeTypes = "" } },
				{ ".crl", new MimeType { FileExtension = ".crl", PrimaryMimeType = "application/pkix-crl", SecondaryMimeTypes = "" } },
				{ ".crt", new MimeType { FileExtension = ".crt", PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".cs", new MimeType { FileExtension = ".cs", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".csdproj", new MimeType { FileExtension = ".csdproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".csh", new MimeType { FileExtension = ".csh", PrimaryMimeType = "application/x-csh", SecondaryMimeTypes = "" } },
				{ ".csproj", new MimeType { FileExtension = ".csproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".css", new MimeType { FileExtension = ".css", PrimaryMimeType = "text/css", SecondaryMimeTypes = "" } },
				{ ".csv", new MimeType { FileExtension = ".csv", PrimaryMimeType = "text/csv", SecondaryMimeTypes = "" } },
				{ ".cur", new MimeType { FileExtension = ".cur", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".cxx", new MimeType { FileExtension = ".cxx", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".dat", new MimeType { FileExtension = ".dat", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".datasource", new MimeType { FileExtension = ".datasource", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".dbproj", new MimeType { FileExtension = ".dbproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".dcr", new MimeType { FileExtension = ".dcr", PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".def", new MimeType { FileExtension = ".def", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".deploy", new MimeType { FileExtension = ".deploy", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".der", new MimeType { FileExtension = ".der", PrimaryMimeType = "application/x-x509-ca-cert", SecondaryMimeTypes = "" } },
				{ ".dgml", new MimeType { FileExtension = ".dgml", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".dib", new MimeType { FileExtension = ".dib", PrimaryMimeType = "image/bmp", SecondaryMimeTypes = "" } },
				{ ".dif", new MimeType { FileExtension = ".dif", PrimaryMimeType = "video/x-dv", SecondaryMimeTypes = "" } },
				{ ".dir", new MimeType { FileExtension = ".dir", PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".disco", new MimeType { FileExtension = ".disco", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dll", new MimeType { FileExtension = ".dll", PrimaryMimeType = "application/x-msdownload", SecondaryMimeTypes = "" } },
				{ ".dll.config", new MimeType { FileExtension = ".dll.config", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dlm", new MimeType { FileExtension = ".dlm", PrimaryMimeType = "text/dlm", SecondaryMimeTypes = "" } },
				{ ".doc", new MimeType { FileExtension = ".doc", PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".docm", new MimeType { FileExtension = ".docm", PrimaryMimeType = "application/vnd.ms-word.document.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".docx", new MimeType { FileExtension = ".docx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", SecondaryMimeTypes = "zip" } },
				{ ".dot", new MimeType { FileExtension = ".dot", PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".dotm", new MimeType { FileExtension = ".dotm", PrimaryMimeType = "application/vnd.ms-word.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".dotx", new MimeType { FileExtension = ".dotx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.template", SecondaryMimeTypes = "zip" } },
				{ ".dsp", new MimeType { FileExtension = ".dsp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".dsw", new MimeType { FileExtension = ".dsw", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".dtd", new MimeType { FileExtension = ".dtd", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dtsConfig", new MimeType { FileExtension = ".dtsConfig", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".dv", new MimeType { FileExtension = ".dv", PrimaryMimeType = "video/x-dv", SecondaryMimeTypes = "" } },
				{ ".dvi", new MimeType { FileExtension = ".dvi", PrimaryMimeType = "application/x-dvi", SecondaryMimeTypes = "" } },
				{ ".dwf", new MimeType { FileExtension = ".dwf", PrimaryMimeType = "drawing/x-dwf", SecondaryMimeTypes = "" } },
				{ ".dwp", new MimeType { FileExtension = ".dwp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".dxr", new MimeType { FileExtension = ".dxr", PrimaryMimeType = "application/x-director", SecondaryMimeTypes = "" } },
				{ ".eml", new MimeType { FileExtension = ".eml", PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".emz", new MimeType { FileExtension = ".emz", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".eot", new MimeType { FileExtension = ".eot", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".eps", new MimeType { FileExtension = ".eps", PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".etl", new MimeType { FileExtension = ".etl", PrimaryMimeType = "application/etl", SecondaryMimeTypes = "" } },
				{ ".etx", new MimeType { FileExtension = ".etx", PrimaryMimeType = "text/x-setext", SecondaryMimeTypes = "" } },
				{ ".evy", new MimeType { FileExtension = ".evy", PrimaryMimeType = "application/envoy", SecondaryMimeTypes = "" } },
				{ ".exe", new MimeType { FileExtension = ".exe", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".exe.config", new MimeType { FileExtension = ".exe.config", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".fdf", new MimeType { FileExtension = ".fdf", PrimaryMimeType = "application/vnd.fdf", SecondaryMimeTypes = "" } },
				{ ".fif", new MimeType { FileExtension = ".fif", PrimaryMimeType = "application/fractals", SecondaryMimeTypes = "" } },
				{ ".filters", new MimeType { FileExtension = ".filters", PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".fla", new MimeType { FileExtension = ".fla", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".flr", new MimeType { FileExtension = ".flr", PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".flv", new MimeType { FileExtension = ".flv", PrimaryMimeType = "video/x-flv", SecondaryMimeTypes = "" } },
				{ ".fsscript", new MimeType { FileExtension = ".fsscript", PrimaryMimeType = "application/fsharp-script", SecondaryMimeTypes = "" } },
				{ ".fsx", new MimeType { FileExtension = ".fsx", PrimaryMimeType = "application/fsharp-script", SecondaryMimeTypes = "" } },
				{ ".generictest", new MimeType { FileExtension = ".generictest", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".gif", new MimeType { FileExtension = ".gif", PrimaryMimeType = "image/gif", SecondaryMimeTypes = "" } },
				{ ".group", new MimeType { FileExtension = ".group", PrimaryMimeType = "text/x-ms-group", SecondaryMimeTypes = "" } },
				{ ".gsm", new MimeType { FileExtension = ".gsm", PrimaryMimeType = "audio/x-gsm", SecondaryMimeTypes = "" } },
				{ ".gtar", new MimeType { FileExtension = ".gtar", PrimaryMimeType = "application/x-gtar", SecondaryMimeTypes = "" } },
				{ ".gz", new MimeType { FileExtension = ".gz", PrimaryMimeType = "application/x-gzip", SecondaryMimeTypes = "" } },
				{ ".h", new MimeType { FileExtension = ".h", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".hdf", new MimeType { FileExtension = ".hdf", PrimaryMimeType = "application/x-hdf", SecondaryMimeTypes = "" } },
				{ ".hdml", new MimeType { FileExtension = ".hdml", PrimaryMimeType = "text/x-hdml", SecondaryMimeTypes = "" } },
				{ ".hhc", new MimeType { FileExtension = ".hhc", PrimaryMimeType = "application/x-oleobject", SecondaryMimeTypes = "" } },
				{ ".hhk", new MimeType { FileExtension = ".hhk", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hhp", new MimeType { FileExtension = ".hhp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hlp", new MimeType { FileExtension = ".hlp", PrimaryMimeType = "application/winhlp", SecondaryMimeTypes = "" } },
				{ ".hpp", new MimeType { FileExtension = ".hpp", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".hqx", new MimeType { FileExtension = ".hqx", PrimaryMimeType = "application/mac-binhex40", SecondaryMimeTypes = "" } },
				{ ".hta", new MimeType { FileExtension = ".hta", PrimaryMimeType = "application/hta", SecondaryMimeTypes = "" } },
				{ ".htc", new MimeType { FileExtension = ".htc", PrimaryMimeType = "text/x-component", SecondaryMimeTypes = "" } },
				{ ".htm", new MimeType { FileExtension = ".htm", PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".html", new MimeType { FileExtension = ".html", PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".htt", new MimeType { FileExtension = ".htt", PrimaryMimeType = "text/webviewhtml", SecondaryMimeTypes = "" } },
				{ ".hxa", new MimeType { FileExtension = ".hxa", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxc", new MimeType { FileExtension = ".hxc", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxd", new MimeType { FileExtension = ".hxd", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxe", new MimeType { FileExtension = ".hxe", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxf", new MimeType { FileExtension = ".hxf", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxh", new MimeType { FileExtension = ".hxh", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxi", new MimeType { FileExtension = ".hxi", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxk", new MimeType { FileExtension = ".hxk", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxq", new MimeType { FileExtension = ".hxq", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxr", new MimeType { FileExtension = ".hxr", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxs", new MimeType { FileExtension = ".hxs", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxt", new MimeType { FileExtension = ".hxt", PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".hxv", new MimeType { FileExtension = ".hxv", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".hxw", new MimeType { FileExtension = ".hxw", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".hxx", new MimeType { FileExtension = ".hxx", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".i", new MimeType { FileExtension = ".i", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".ico", new MimeType { FileExtension = ".ico", PrimaryMimeType = "image/x-icon", SecondaryMimeTypes = "" } },
				{ ".ics", new MimeType { FileExtension = ".ics", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".idl", new MimeType { FileExtension = ".idl", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".ief", new MimeType { FileExtension = ".ief", PrimaryMimeType = "image/ief", SecondaryMimeTypes = "" } },
				{ ".iii", new MimeType { FileExtension = ".iii", PrimaryMimeType = "application/x-iphone", SecondaryMimeTypes = "" } },
				{ ".inc", new MimeType { FileExtension = ".inc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".inf", new MimeType { FileExtension = ".inf", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".inl", new MimeType { FileExtension = ".inl", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".ins", new MimeType { FileExtension = ".ins", PrimaryMimeType = "application/x-internet-signup", SecondaryMimeTypes = "" } },
				{ ".ipa", new MimeType { FileExtension = ".ipa", PrimaryMimeType = "application/x-itunes-ipa", SecondaryMimeTypes = "" } },
				{ ".ipg", new MimeType { FileExtension = ".ipg", PrimaryMimeType = "application/x-itunes-ipg", SecondaryMimeTypes = "" } },
				{ ".ipproj", new MimeType { FileExtension = ".ipproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".ipsw", new MimeType { FileExtension = ".ipsw", PrimaryMimeType = "application/x-itunes-ipsw", SecondaryMimeTypes = "" } },
				{ ".iqy", new MimeType { FileExtension = ".iqy", PrimaryMimeType = "text/x-ms-iqy", SecondaryMimeTypes = "" } },
				{ ".isp", new MimeType { FileExtension = ".isp", PrimaryMimeType = "application/x-internet-signup", SecondaryMimeTypes = "" } },
				{ ".ite", new MimeType { FileExtension = ".ite", PrimaryMimeType = "application/x-itunes-ite", SecondaryMimeTypes = "" } },
				{ ".itlp", new MimeType { FileExtension = ".itlp", PrimaryMimeType = "application/x-itunes-itlp", SecondaryMimeTypes = "" } },
				{ ".itms", new MimeType { FileExtension = ".itms", PrimaryMimeType = "application/x-itunes-itms", SecondaryMimeTypes = "" } },
				{ ".itpc", new MimeType { FileExtension = ".itpc", PrimaryMimeType = "application/x-itunes-itpc", SecondaryMimeTypes = "" } },
				{ ".IVF", new MimeType { FileExtension = ".IVF", PrimaryMimeType = "video/x-ivf", SecondaryMimeTypes = "" } },
				{ ".jar", new MimeType { FileExtension = ".jar", PrimaryMimeType = "application/java-archive", SecondaryMimeTypes = "" } },
				{ ".java", new MimeType { FileExtension = ".java", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".jck", new MimeType { FileExtension = ".jck", PrimaryMimeType = "application/liquidmotion", SecondaryMimeTypes = "" } },
				{ ".jcz", new MimeType { FileExtension = ".jcz", PrimaryMimeType = "application/liquidmotion", SecondaryMimeTypes = "" } },
				{ ".jfif", new MimeType { FileExtension = ".jfif", PrimaryMimeType = "image/pjpeg", SecondaryMimeTypes = "" } },
				{ ".jnlp", new MimeType { FileExtension = ".jnlp", PrimaryMimeType = "application/x-java-jnlp-file", SecondaryMimeTypes = "" } },
				{ ".jpb", new MimeType { FileExtension = ".jpb", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".jpe", new MimeType { FileExtension = ".jpe", PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".jpeg", new MimeType { FileExtension = ".jpeg", PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".jpg", new MimeType { FileExtension = ".jpg", PrimaryMimeType = "image/jpeg", SecondaryMimeTypes = "" } },
				{ ".js", new MimeType { FileExtension = ".js", PrimaryMimeType = "application/x-javascript", SecondaryMimeTypes = "" } },
				{ ".jsx", new MimeType { FileExtension = ".jsx", PrimaryMimeType = "text/jscript", SecondaryMimeTypes = "" } },
				{ ".jsxbin", new MimeType { FileExtension = ".jsxbin", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".latex", new MimeType { FileExtension = ".latex", PrimaryMimeType = "application/x-latex", SecondaryMimeTypes = "" } },
				{ ".library-ms", new MimeType { FileExtension = ".library-ms", PrimaryMimeType = "application/windows-library+xml", SecondaryMimeTypes = "" } },
				{ ".lit", new MimeType { FileExtension = ".lit", PrimaryMimeType = "application/x-ms-reader", SecondaryMimeTypes = "" } },
				{ ".loadtest", new MimeType { FileExtension = ".loadtest", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".lpk", new MimeType { FileExtension = ".lpk", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".lsf", new MimeType { FileExtension = ".lsf", PrimaryMimeType = "video/x-la-asf", SecondaryMimeTypes = "" } },
				{ ".lst", new MimeType { FileExtension = ".lst", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".lsx", new MimeType { FileExtension = ".lsx", PrimaryMimeType = "video/x-la-asf", SecondaryMimeTypes = "" } },
				{ ".lzh", new MimeType { FileExtension = ".lzh", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".m13", new MimeType { FileExtension = ".m13", PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".m14", new MimeType { FileExtension = ".m14", PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".m1v", new MimeType { FileExtension = ".m1v", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".m2t", new MimeType { FileExtension = ".m2t", PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".m2ts", new MimeType { FileExtension = ".m2ts", PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".m2v", new MimeType { FileExtension = ".m2v", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".m3u", new MimeType { FileExtension = ".m3u", PrimaryMimeType = "audio/x-mpegurl", SecondaryMimeTypes = "" } },
				{ ".m3u8", new MimeType { FileExtension = ".m3u8", PrimaryMimeType = "audio/x-mpegurl", SecondaryMimeTypes = "" } },
				{ ".m4a", new MimeType { FileExtension = ".m4a", PrimaryMimeType = "audio/m4a", SecondaryMimeTypes = "" } },
				{ ".m4b", new MimeType { FileExtension = ".m4b", PrimaryMimeType = "audio/m4b", SecondaryMimeTypes = "" } },
				{ ".m4p", new MimeType { FileExtension = ".m4p", PrimaryMimeType = "audio/m4p", SecondaryMimeTypes = "" } },
				{ ".m4r", new MimeType { FileExtension = ".m4r", PrimaryMimeType = "audio/x-m4r", SecondaryMimeTypes = "" } },
				{ ".m4v", new MimeType { FileExtension = ".m4v", PrimaryMimeType = "video/x-m4v", SecondaryMimeTypes = "" } },
				{ ".mac", new MimeType { FileExtension = ".mac", PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".mak", new MimeType { FileExtension = ".mak", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".man", new MimeType { FileExtension = ".man", PrimaryMimeType = "application/x-troff-man", SecondaryMimeTypes = "" } },
				{ ".manifest", new MimeType { FileExtension = ".manifest", PrimaryMimeType = "application/x-ms-manifest", SecondaryMimeTypes = "" } },
				{ ".map", new MimeType { FileExtension = ".map", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".master", new MimeType { FileExtension = ".master", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".mda", new MimeType { FileExtension = ".mda", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".mdb", new MimeType { FileExtension = ".mdb", PrimaryMimeType = "application/x-msaccess", SecondaryMimeTypes = "" } },
				{ ".mde", new MimeType { FileExtension = ".mde", PrimaryMimeType = "application/msaccess", SecondaryMimeTypes = "" } },
				{ ".mdp", new MimeType { FileExtension = ".mdp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".me", new MimeType { FileExtension = ".me", PrimaryMimeType = "application/x-troff-me", SecondaryMimeTypes = "" } },
				{ ".mfp", new MimeType { FileExtension = ".mfp", PrimaryMimeType = "application/x-shockwave-flash", SecondaryMimeTypes = "" } },
				{ ".mht", new MimeType { FileExtension = ".mht", PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".mhtml", new MimeType { FileExtension = ".mhtml", PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".mid", new MimeType { FileExtension = ".mid", PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".midi", new MimeType { FileExtension = ".midi", PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".mix", new MimeType { FileExtension = ".mix", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".mk", new MimeType { FileExtension = ".mk", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".mmf", new MimeType { FileExtension = ".mmf", PrimaryMimeType = "application/x-smaf", SecondaryMimeTypes = "" } },
				{ ".mno", new MimeType { FileExtension = ".mno", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".mny", new MimeType { FileExtension = ".mny", PrimaryMimeType = "application/x-msmoney", SecondaryMimeTypes = "" } },
				{ ".mod", new MimeType { FileExtension = ".mod", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mov", new MimeType { FileExtension = ".mov", PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".movie", new MimeType { FileExtension = ".movie", PrimaryMimeType = "video/x-sgi-movie", SecondaryMimeTypes = "" } },
				{ ".mp2", new MimeType { FileExtension = ".mp2", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp2v", new MimeType { FileExtension = ".mp2v", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp3", new MimeType { FileExtension = ".mp3", PrimaryMimeType = "audio/mpeg", SecondaryMimeTypes = "" } },
				{ ".mp4", new MimeType { FileExtension = ".mp4", PrimaryMimeType = "video/mp4", SecondaryMimeTypes = "" } },
				{ ".mp4v", new MimeType { FileExtension = ".mp4v", PrimaryMimeType = "video/mp4", SecondaryMimeTypes = "" } },
				{ ".mpa", new MimeType { FileExtension = ".mpa", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpe", new MimeType { FileExtension = ".mpe", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpeg", new MimeType { FileExtension = ".mpeg", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpf", new MimeType { FileExtension = ".mpf", PrimaryMimeType = "application/vnd.ms-mediapackage", SecondaryMimeTypes = "" } },
				{ ".mpg", new MimeType { FileExtension = ".mpg", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mpp", new MimeType { FileExtension = ".mpp", PrimaryMimeType = "application/vnd.ms-project", SecondaryMimeTypes = "" } },
				{ ".mpv2", new MimeType { FileExtension = ".mpv2", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".mqv", new MimeType { FileExtension = ".mqv", PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".ms", new MimeType { FileExtension = ".ms", PrimaryMimeType = "application/x-troff-ms", SecondaryMimeTypes = "" } },
				{ ".msg", new MimeType { FileExtension = ".msg", PrimaryMimeType = "application/vnd.ms-outlook", SecondaryMimeTypes = "" } },
				{ ".msi", new MimeType { FileExtension = ".msi", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".mso", new MimeType { FileExtension = ".mso", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".mts", new MimeType { FileExtension = ".mts", PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".mtx", new MimeType { FileExtension = ".mtx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".mvb", new MimeType { FileExtension = ".mvb", PrimaryMimeType = "application/x-msmediaview", SecondaryMimeTypes = "" } },
				{ ".mvc", new MimeType { FileExtension = ".mvc", PrimaryMimeType = "application/x-miva-compiled", SecondaryMimeTypes = "" } },
				{ ".mxp", new MimeType { FileExtension = ".mxp", PrimaryMimeType = "application/x-mmxp", SecondaryMimeTypes = "" } },
				{ ".nc", new MimeType { FileExtension = ".nc", PrimaryMimeType = "application/x-netcdf", SecondaryMimeTypes = "" } },
				{ ".nsc", new MimeType { FileExtension = ".nsc", PrimaryMimeType = "video/x-ms-asf", SecondaryMimeTypes = "" } },
				{ ".nws", new MimeType { FileExtension = ".nws", PrimaryMimeType = "message/rfc822", SecondaryMimeTypes = "" } },
				{ ".ocx", new MimeType { FileExtension = ".ocx", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".oda", new MimeType { FileExtension = ".oda", PrimaryMimeType = "application/oda", SecondaryMimeTypes = "" } },
				{ ".odc", new MimeType { FileExtension = ".odc", PrimaryMimeType = "text/x-ms-odc", SecondaryMimeTypes = "" } },
				{ ".odh", new MimeType { FileExtension = ".odh", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".odl", new MimeType { FileExtension = ".odl", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".odp", new MimeType { FileExtension = ".odp", PrimaryMimeType = "application/vnd.oasis.opendocument.presentation", SecondaryMimeTypes = "zip" } },
				{ ".ods", new MimeType { FileExtension = ".ods", PrimaryMimeType = "application/oleobject", SecondaryMimeTypes = "zip" } },
				{ ".odt", new MimeType { FileExtension = ".odt", PrimaryMimeType = "application/vnd.oasis.opendocument.text", SecondaryMimeTypes = "zip" } },
				{ ".one", new MimeType { FileExtension = ".one", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onea", new MimeType { FileExtension = ".onea", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onepkg", new MimeType { FileExtension = ".onepkg", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetmp", new MimeType { FileExtension = ".onetmp", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetoc", new MimeType { FileExtension = ".onetoc", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".onetoc2", new MimeType { FileExtension = ".onetoc2", PrimaryMimeType = "application/onenote", SecondaryMimeTypes = "" } },
				{ ".orderedtest", new MimeType { FileExtension = ".orderedtest", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".osdx", new MimeType { FileExtension = ".osdx", PrimaryMimeType = "application/opensearchdescription+xml", SecondaryMimeTypes = "" } },
				{ ".p10", new MimeType { FileExtension = ".p10", PrimaryMimeType = "application/pkcs10", SecondaryMimeTypes = "" } },
				{ ".p12", new MimeType { FileExtension = ".p12", PrimaryMimeType = "application/x-pkcs12", SecondaryMimeTypes = "" } },
				{ ".p7b", new MimeType { FileExtension = ".p7b", PrimaryMimeType = "application/x-pkcs7-certificates", SecondaryMimeTypes = "" } },
				{ ".p7c", new MimeType { FileExtension = ".p7c", PrimaryMimeType = "application/pkcs7-mime", SecondaryMimeTypes = "" } },
				{ ".p7m", new MimeType { FileExtension = ".p7m", PrimaryMimeType = "application/pkcs7-mime", SecondaryMimeTypes = "" } },
				{ ".p7r", new MimeType { FileExtension = ".p7r", PrimaryMimeType = "application/x-pkcs7-certreqresp", SecondaryMimeTypes = "" } },
				{ ".p7s", new MimeType { FileExtension = ".p7s", PrimaryMimeType = "application/pkcs7-signature", SecondaryMimeTypes = "" } },
				{ ".pbm", new MimeType { FileExtension = ".pbm", PrimaryMimeType = "image/x-portable-bitmap", SecondaryMimeTypes = "" } },
				{ ".pcast", new MimeType { FileExtension = ".pcast", PrimaryMimeType = "application/x-podcast", SecondaryMimeTypes = "" } },
				{ ".pct", new MimeType { FileExtension = ".pct", PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pcx", new MimeType { FileExtension = ".pcx", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".pcz", new MimeType { FileExtension = ".pcz", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".pdf", new MimeType { FileExtension = ".pdf", PrimaryMimeType = "application/pdf", SecondaryMimeTypes = "" } },
				{ ".pfb", new MimeType { FileExtension = ".pfb", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".pfm", new MimeType { FileExtension = ".pfm", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".pfx", new MimeType { FileExtension = ".pfx", PrimaryMimeType = "application/x-pkcs12", SecondaryMimeTypes = "" } },
				{ ".pgm", new MimeType { FileExtension = ".pgm", PrimaryMimeType = "image/x-portable-graymap", SecondaryMimeTypes = "" } },
				{ ".pic", new MimeType { FileExtension = ".pic", PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pict", new MimeType { FileExtension = ".pict", PrimaryMimeType = "image/pict", SecondaryMimeTypes = "" } },
				{ ".pkgdef", new MimeType { FileExtension = ".pkgdef", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".pkgundef", new MimeType { FileExtension = ".pkgundef", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".pko", new MimeType { FileExtension = ".pko", PrimaryMimeType = "application/vnd.ms-pki.pko", SecondaryMimeTypes = "" } },
				{ ".pls", new MimeType { FileExtension = ".pls", PrimaryMimeType = "audio/scpls", SecondaryMimeTypes = "" } },
				{ ".pma", new MimeType { FileExtension = ".pma", PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmc", new MimeType { FileExtension = ".pmc", PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pml", new MimeType { FileExtension = ".pml", PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmr", new MimeType { FileExtension = ".pmr", PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".pmw", new MimeType { FileExtension = ".pmw", PrimaryMimeType = "application/x-perfmon", SecondaryMimeTypes = "" } },
				{ ".png", new MimeType { FileExtension = ".png", PrimaryMimeType = "image/png", SecondaryMimeTypes = "" } },
				{ ".pnm", new MimeType { FileExtension = ".pnm", PrimaryMimeType = "image/x-portable-anymap", SecondaryMimeTypes = "" } },
				{ ".pnt", new MimeType { FileExtension = ".pnt", PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".pntg", new MimeType { FileExtension = ".pntg", PrimaryMimeType = "image/x-macpaint", SecondaryMimeTypes = "" } },
				{ ".pnz", new MimeType { FileExtension = ".pnz", PrimaryMimeType = "image/png", SecondaryMimeTypes = "" } },
				{ ".pot", new MimeType { FileExtension = ".pot", PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".potm", new MimeType { FileExtension = ".potm", PrimaryMimeType = "application/vnd.ms-powerpoint.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".potx", new MimeType { FileExtension = ".potx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.template", SecondaryMimeTypes = "zip" } },
				{ ".ppa", new MimeType { FileExtension = ".ppa", PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".ppam", new MimeType { FileExtension = ".ppam", PrimaryMimeType = "application/vnd.ms-powerpoint.addin.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".ppm", new MimeType { FileExtension = ".ppm", PrimaryMimeType = "image/x-portable-pixmap", SecondaryMimeTypes = "" } },
				{ ".pps", new MimeType { FileExtension = ".pps", PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".ppsm", new MimeType { FileExtension = ".ppsm", PrimaryMimeType = "application/vnd.ms-powerpoint.slideshow.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".ppsx", new MimeType { FileExtension = ".ppsx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.slideshow", SecondaryMimeTypes = "zip" } },
				{ ".ppt", new MimeType { FileExtension = ".ppt", PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".pptm", new MimeType { FileExtension = ".pptm", PrimaryMimeType = "application/vnd.ms-powerpoint.presentation.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".pptx", new MimeType { FileExtension = ".pptx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation", SecondaryMimeTypes = "zip" } },
				{ ".prf", new MimeType { FileExtension = ".prf", PrimaryMimeType = "application/pics-rules", SecondaryMimeTypes = "" } },
				{ ".prm", new MimeType { FileExtension = ".prm", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".prx", new MimeType { FileExtension = ".prx", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".ps", new MimeType { FileExtension = ".ps", PrimaryMimeType = "application/postscript", SecondaryMimeTypes = "" } },
				{ ".psc1", new MimeType { FileExtension = ".psc1", PrimaryMimeType = "application/PowerShell", SecondaryMimeTypes = "" } },
				{ ".psd", new MimeType { FileExtension = ".psd", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".psess", new MimeType { FileExtension = ".psess", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".psm", new MimeType { FileExtension = ".psm", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".psp", new MimeType { FileExtension = ".psp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".pub", new MimeType { FileExtension = ".pub", PrimaryMimeType = "application/x-mspublisher", SecondaryMimeTypes = "" } },
				{ ".pwz", new MimeType { FileExtension = ".pwz", PrimaryMimeType = "application/vnd.ms-powerpoint", SecondaryMimeTypes = "" } },
				{ ".qht", new MimeType { FileExtension = ".qht", PrimaryMimeType = "text/x-html-insertion", SecondaryMimeTypes = "" } },
				{ ".qhtm", new MimeType { FileExtension = ".qhtm", PrimaryMimeType = "text/x-html-insertion", SecondaryMimeTypes = "" } },
				{ ".qt", new MimeType { FileExtension = ".qt", PrimaryMimeType = "video/quicktime", SecondaryMimeTypes = "" } },
				{ ".qti", new MimeType { FileExtension = ".qti", PrimaryMimeType = "image/x-quicktime", SecondaryMimeTypes = "" } },
				{ ".qtif", new MimeType { FileExtension = ".qtif", PrimaryMimeType = "image/x-quicktime", SecondaryMimeTypes = "" } },
				{ ".qtl", new MimeType { FileExtension = ".qtl", PrimaryMimeType = "application/x-quicktimeplayer", SecondaryMimeTypes = "" } },
				{ ".qxd", new MimeType { FileExtension = ".qxd", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".ra", new MimeType { FileExtension = ".ra", PrimaryMimeType = "audio/x-pn-realaudio", SecondaryMimeTypes = "" } },
				{ ".ram", new MimeType { FileExtension = ".ram", PrimaryMimeType = "audio/x-pn-realaudio", SecondaryMimeTypes = "" } },
				{ ".rar", new MimeType { FileExtension = ".rar", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".ras", new MimeType { FileExtension = ".ras", PrimaryMimeType = "image/x-cmu-raster", SecondaryMimeTypes = "" } },
				{ ".rat", new MimeType { FileExtension = ".rat", PrimaryMimeType = "application/rat-file", SecondaryMimeTypes = "" } },
				{ ".rc", new MimeType { FileExtension = ".rc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".rc2", new MimeType { FileExtension = ".rc2", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".rct", new MimeType { FileExtension = ".rct", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".rdlc", new MimeType { FileExtension = ".rdlc", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".resx", new MimeType { FileExtension = ".resx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".rf", new MimeType { FileExtension = ".rf", PrimaryMimeType = "image/vnd.rn-realflash", SecondaryMimeTypes = "" } },
				{ ".rgb", new MimeType { FileExtension = ".rgb", PrimaryMimeType = "image/x-rgb", SecondaryMimeTypes = "" } },
				{ ".rgs", new MimeType { FileExtension = ".rgs", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".rm", new MimeType { FileExtension = ".rm", PrimaryMimeType = "application/vnd.rn-realmedia", SecondaryMimeTypes = "" } },
				{ ".rmi", new MimeType { FileExtension = ".rmi", PrimaryMimeType = "audio/mid", SecondaryMimeTypes = "" } },
				{ ".rmp", new MimeType { FileExtension = ".rmp", PrimaryMimeType = "application/vnd.rn-rn_music_package", SecondaryMimeTypes = "" } },
				{ ".roff", new MimeType { FileExtension = ".roff", PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".rpm", new MimeType { FileExtension = ".rpm", PrimaryMimeType = "audio/x-pn-realaudio-plugin", SecondaryMimeTypes = "" } },
				{ ".rqy", new MimeType { FileExtension = ".rqy", PrimaryMimeType = "text/x-ms-rqy", SecondaryMimeTypes = "" } },
				{ ".rtf", new MimeType { FileExtension = ".rtf", PrimaryMimeType = "application/rtf", SecondaryMimeTypes = "rtf" } },
				{ ".rtx", new MimeType { FileExtension = ".rtx", PrimaryMimeType = "text/richtext", SecondaryMimeTypes = "rtf" } },
				{ ".ruleset", new MimeType { FileExtension = ".ruleset", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".s", new MimeType { FileExtension = ".s", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".safariextz", new MimeType { FileExtension = ".safariextz", PrimaryMimeType = "application/x-safari-safariextz", SecondaryMimeTypes = "" } },
				{ ".scd", new MimeType { FileExtension = ".scd", PrimaryMimeType = "application/x-msschedule", SecondaryMimeTypes = "" } },
				{ ".sct", new MimeType { FileExtension = ".sct", PrimaryMimeType = "text/scriptlet", SecondaryMimeTypes = "" } },
				{ ".sd2", new MimeType { FileExtension = ".sd2", PrimaryMimeType = "audio/x-sd2", SecondaryMimeTypes = "" } },
				{ ".sdp", new MimeType { FileExtension = ".sdp", PrimaryMimeType = "application/sdp", SecondaryMimeTypes = "" } },
				{ ".sea", new MimeType { FileExtension = ".sea", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".searchConnector-ms", new MimeType { FileExtension = ".searchConnector-ms", PrimaryMimeType = "application/windows-search-connector+xml", SecondaryMimeTypes = "" } },
				{ ".setpay", new MimeType { FileExtension = ".setpay", PrimaryMimeType = "application/set-payment-initiation", SecondaryMimeTypes = "" } },
				{ ".setreg", new MimeType { FileExtension = ".setreg", PrimaryMimeType = "application/set-registration-initiation", SecondaryMimeTypes = "" } },
				{ ".settings", new MimeType { FileExtension = ".settings", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".sgimb", new MimeType { FileExtension = ".sgimb", PrimaryMimeType = "application/x-sgimb", SecondaryMimeTypes = "" } },
				{ ".sgml", new MimeType { FileExtension = ".sgml", PrimaryMimeType = "text/sgml", SecondaryMimeTypes = "" } },
				{ ".sh", new MimeType { FileExtension = ".sh", PrimaryMimeType = "application/x-sh", SecondaryMimeTypes = "" } },
				{ ".shar", new MimeType { FileExtension = ".shar", PrimaryMimeType = "application/x-shar", SecondaryMimeTypes = "" } },
				{ ".shtml", new MimeType { FileExtension = ".shtml", PrimaryMimeType = "text/html", SecondaryMimeTypes = "" } },
				{ ".sit", new MimeType { FileExtension = ".sit", PrimaryMimeType = "application/x-stuffit", SecondaryMimeTypes = "" } },
				{ ".sitemap", new MimeType { FileExtension = ".sitemap", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".skin", new MimeType { FileExtension = ".skin", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".sldm", new MimeType { FileExtension = ".sldm", PrimaryMimeType = "application/vnd.ms-powerpoint.slide.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".sldx", new MimeType { FileExtension = ".sldx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.presentationml.slide", SecondaryMimeTypes = "" } },
				{ ".slk", new MimeType { FileExtension = ".slk", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".sln", new MimeType { FileExtension = ".sln", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".slupkg-ms", new MimeType { FileExtension = ".slupkg-ms", PrimaryMimeType = "application/x-ms-license", SecondaryMimeTypes = "" } },
				{ ".smd", new MimeType { FileExtension = ".smd", PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".smi", new MimeType { FileExtension = ".smi", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".smx", new MimeType { FileExtension = ".smx", PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".smz", new MimeType { FileExtension = ".smz", PrimaryMimeType = "audio/x-smd", SecondaryMimeTypes = "" } },
				{ ".snd", new MimeType { FileExtension = ".snd", PrimaryMimeType = "audio/basic", SecondaryMimeTypes = "" } },
				{ ".snippet", new MimeType { FileExtension = ".snippet", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".snp", new MimeType { FileExtension = ".snp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".sol", new MimeType { FileExtension = ".sol", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".sor", new MimeType { FileExtension = ".sor", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".spc", new MimeType { FileExtension = ".spc", PrimaryMimeType = "application/x-pkcs7-certificates", SecondaryMimeTypes = "" } },
				{ ".spl", new MimeType { FileExtension = ".spl", PrimaryMimeType = "application/futuresplash", SecondaryMimeTypes = "" } },
				{ ".src", new MimeType { FileExtension = ".src", PrimaryMimeType = "application/x-wais-source", SecondaryMimeTypes = "" } },
				{ ".srf", new MimeType { FileExtension = ".srf", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".SSISDeploymentManifest", new MimeType { FileExtension = ".SSISDeploymentManifest", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".ssm", new MimeType { FileExtension = ".ssm", PrimaryMimeType = "application/streamingmedia", SecondaryMimeTypes = "" } },
				{ ".sst", new MimeType { FileExtension = ".sst", PrimaryMimeType = "application/vnd.ms-pki.certstore", SecondaryMimeTypes = "" } },
				{ ".stl", new MimeType { FileExtension = ".stl", PrimaryMimeType = "application/vnd.ms-pki.stl", SecondaryMimeTypes = "" } },
				{ ".sv4cpio", new MimeType { FileExtension = ".sv4cpio", PrimaryMimeType = "application/x-sv4cpio", SecondaryMimeTypes = "" } },
				{ ".sv4crc", new MimeType { FileExtension = ".sv4crc", PrimaryMimeType = "application/x-sv4crc", SecondaryMimeTypes = "" } },
				{ ".svc", new MimeType { FileExtension = ".svc", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".swf", new MimeType { FileExtension = ".swf", PrimaryMimeType = "application/x-shockwave-flash", SecondaryMimeTypes = "" } },
				{ ".t", new MimeType { FileExtension = ".t", PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".tar", new MimeType { FileExtension = ".tar", PrimaryMimeType = "application/x-tar", SecondaryMimeTypes = "" } },
				{ ".tcl", new MimeType { FileExtension = ".tcl", PrimaryMimeType = "application/x-tcl", SecondaryMimeTypes = "" } },
				{ ".testrunconfig", new MimeType { FileExtension = ".testrunconfig", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".testsettings", new MimeType { FileExtension = ".testsettings", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".tex", new MimeType { FileExtension = ".tex", PrimaryMimeType = "application/x-tex", SecondaryMimeTypes = "" } },
				{ ".texi", new MimeType { FileExtension = ".texi", PrimaryMimeType = "application/x-texinfo", SecondaryMimeTypes = "" } },
				{ ".texinfo", new MimeType { FileExtension = ".texinfo", PrimaryMimeType = "application/x-texinfo", SecondaryMimeTypes = "" } },
				{ ".tgz", new MimeType { FileExtension = ".tgz", PrimaryMimeType = "application/x-compressed", SecondaryMimeTypes = "" } },
				{ ".thmx", new MimeType { FileExtension = ".thmx", PrimaryMimeType = "application/vnd.ms-officetheme", SecondaryMimeTypes = "" } },
				{ ".thn", new MimeType { FileExtension = ".thn", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".tif", new MimeType { FileExtension = ".tif", PrimaryMimeType = "image/tiff", SecondaryMimeTypes = "" } },
				{ ".tiff", new MimeType { FileExtension = ".tiff", PrimaryMimeType = "image/tiff", SecondaryMimeTypes = "" } },
				{ ".tlh", new MimeType { FileExtension = ".tlh", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".tli", new MimeType { FileExtension = ".tli", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".toc", new MimeType { FileExtension = ".toc", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".tr", new MimeType { FileExtension = ".tr", PrimaryMimeType = "application/x-troff", SecondaryMimeTypes = "" } },
				{ ".trm", new MimeType { FileExtension = ".trm", PrimaryMimeType = "application/x-msterminal", SecondaryMimeTypes = "" } },
				{ ".trx", new MimeType { FileExtension = ".trx", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".ts", new MimeType { FileExtension = ".ts", PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".tsv", new MimeType { FileExtension = ".tsv", PrimaryMimeType = "text/tab-separated-values", SecondaryMimeTypes = "" } },
				{ ".ttf", new MimeType { FileExtension = ".ttf", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".tts", new MimeType { FileExtension = ".tts", PrimaryMimeType = "video/vnd.dlna.mpeg-tts", SecondaryMimeTypes = "" } },
				{ ".txt", new MimeType { FileExtension = ".txt", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".u32", new MimeType { FileExtension = ".u32", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".uls", new MimeType { FileExtension = ".uls", PrimaryMimeType = "text/iuls", SecondaryMimeTypes = "" } },
				{ ".user", new MimeType { FileExtension = ".user", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".ustar", new MimeType { FileExtension = ".ustar", PrimaryMimeType = "application/x-ustar", SecondaryMimeTypes = "" } },
				{ ".vb", new MimeType { FileExtension = ".vb", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vbdproj", new MimeType { FileExtension = ".vbdproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vbk", new MimeType { FileExtension = ".vbk", PrimaryMimeType = "video/mpeg", SecondaryMimeTypes = "" } },
				{ ".vbproj", new MimeType { FileExtension = ".vbproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vbs", new MimeType { FileExtension = ".vbs", PrimaryMimeType = "text/vbscript", SecondaryMimeTypes = "" } },
				{ ".vcf", new MimeType { FileExtension = ".vcf", PrimaryMimeType = "text/x-vcard", SecondaryMimeTypes = "" } },
				{ ".vcproj", new MimeType { FileExtension = ".vcproj", PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".vcs", new MimeType { FileExtension = ".vcs", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vcxproj", new MimeType { FileExtension = ".vcxproj", PrimaryMimeType = "Application/xml", SecondaryMimeTypes = "" } },
				{ ".vddproj", new MimeType { FileExtension = ".vddproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vdp", new MimeType { FileExtension = ".vdp", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vdproj", new MimeType { FileExtension = ".vdproj", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vdx", new MimeType { FileExtension = ".vdx", PrimaryMimeType = "application/vnd.ms-visio.viewer", SecondaryMimeTypes = "" } },
				{ ".vml", new MimeType { FileExtension = ".vml", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vscontent", new MimeType { FileExtension = ".vscontent", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".vsct", new MimeType { FileExtension = ".vsct", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsd", new MimeType { FileExtension = ".vsd", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsi", new MimeType { FileExtension = ".vsi", PrimaryMimeType = "application/ms-vsi", SecondaryMimeTypes = "" } },
				{ ".vsix", new MimeType { FileExtension = ".vsix", PrimaryMimeType = "application/vsix", SecondaryMimeTypes = "" } },
				{ ".vsixlangpack", new MimeType { FileExtension = ".vsixlangpack", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsixmanifest", new MimeType { FileExtension = ".vsixmanifest", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsmdi", new MimeType { FileExtension = ".vsmdi", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".vspscc", new MimeType { FileExtension = ".vspscc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vss", new MimeType { FileExtension = ".vss", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsscc", new MimeType { FileExtension = ".vsscc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vssettings", new MimeType { FileExtension = ".vssettings", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vssscc", new MimeType { FileExtension = ".vssscc", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".vst", new MimeType { FileExtension = ".vst", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vstemplate", new MimeType { FileExtension = ".vstemplate", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".vsto", new MimeType { FileExtension = ".vsto", PrimaryMimeType = "application/x-ms-vsto", SecondaryMimeTypes = "" } },
				{ ".vsw", new MimeType { FileExtension = ".vsw", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vsx", new MimeType { FileExtension = ".vsx", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".vtx", new MimeType { FileExtension = ".vtx", PrimaryMimeType = "application/vnd.visio", SecondaryMimeTypes = "" } },
				{ ".wav", new MimeType { FileExtension = ".wav", PrimaryMimeType = "audio/wav", SecondaryMimeTypes = "" } },
				{ ".wave", new MimeType { FileExtension = ".wave", PrimaryMimeType = "audio/wav", SecondaryMimeTypes = "" } },
				{ ".wax", new MimeType { FileExtension = ".wax", PrimaryMimeType = "audio/x-ms-wax", SecondaryMimeTypes = "" } },
				{ ".wbk", new MimeType { FileExtension = ".wbk", PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".wbmp", new MimeType { FileExtension = ".wbmp", PrimaryMimeType = "image/vnd.wap.wbmp", SecondaryMimeTypes = "" } },
				{ ".wcm", new MimeType { FileExtension = ".wcm", PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wdb", new MimeType { FileExtension = ".wdb", PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wdp", new MimeType { FileExtension = ".wdp", PrimaryMimeType = "image/vnd.ms-photo", SecondaryMimeTypes = "" } },
				{ ".webarchive", new MimeType { FileExtension = ".webarchive", PrimaryMimeType = "application/x-safari-webarchive", SecondaryMimeTypes = "" } },
				{ ".webtest", new MimeType { FileExtension = ".webtest", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".wiq", new MimeType { FileExtension = ".wiq", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".wiz", new MimeType { FileExtension = ".wiz", PrimaryMimeType = "application/msword", SecondaryMimeTypes = "" } },
				{ ".wks", new MimeType { FileExtension = ".wks", PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".WLMP", new MimeType { FileExtension = ".WLMP", PrimaryMimeType = "application/wlmoviemaker", SecondaryMimeTypes = "" } },
				{ ".wlpginstall", new MimeType { FileExtension = ".wlpginstall", PrimaryMimeType = "application/x-wlpg-detect", SecondaryMimeTypes = "" } },
				{ ".wlpginstall3", new MimeType { FileExtension = ".wlpginstall3", PrimaryMimeType = "application/x-wlpg3-detect", SecondaryMimeTypes = "" } },
				{ ".wm", new MimeType { FileExtension = ".wm", PrimaryMimeType = "video/x-ms-wm", SecondaryMimeTypes = "" } },
				{ ".wma", new MimeType { FileExtension = ".wma", PrimaryMimeType = "audio/x-ms-wma", SecondaryMimeTypes = "" } },
				{ ".wmd", new MimeType { FileExtension = ".wmd", PrimaryMimeType = "application/x-ms-wmd", SecondaryMimeTypes = "" } },
				{ ".wmf", new MimeType { FileExtension = ".wmf", PrimaryMimeType = "application/x-msmetafile", SecondaryMimeTypes = "" } },
				{ ".wml", new MimeType { FileExtension = ".wml", PrimaryMimeType = "text/vnd.wap.wml", SecondaryMimeTypes = "" } },
				{ ".wmlc", new MimeType { FileExtension = ".wmlc", PrimaryMimeType = "application/vnd.wap.wmlc", SecondaryMimeTypes = "" } },
				{ ".wmls", new MimeType { FileExtension = ".wmls", PrimaryMimeType = "text/vnd.wap.wmlscript", SecondaryMimeTypes = "" } },
				{ ".wmlsc", new MimeType { FileExtension = ".wmlsc", PrimaryMimeType = "application/vnd.wap.wmlscriptc", SecondaryMimeTypes = "" } },
				{ ".wmp", new MimeType { FileExtension = ".wmp", PrimaryMimeType = "video/x-ms-wmp", SecondaryMimeTypes = "" } },
				{ ".wmv", new MimeType { FileExtension = ".wmv", PrimaryMimeType = "video/x-ms-wmv", SecondaryMimeTypes = "" } },
				{ ".wmx", new MimeType { FileExtension = ".wmx", PrimaryMimeType = "video/x-ms-wmx", SecondaryMimeTypes = "" } },
				{ ".wmz", new MimeType { FileExtension = ".wmz", PrimaryMimeType = "application/x-ms-wmz", SecondaryMimeTypes = "" } },
				{ ".wpl", new MimeType { FileExtension = ".wpl", PrimaryMimeType = "application/vnd.ms-wpl", SecondaryMimeTypes = "" } },
				{ ".wps", new MimeType { FileExtension = ".wps", PrimaryMimeType = "application/vnd.ms-works", SecondaryMimeTypes = "" } },
				{ ".wri", new MimeType { FileExtension = ".wri", PrimaryMimeType = "application/x-mswrite", SecondaryMimeTypes = "" } },
				{ ".wrl", new MimeType { FileExtension = ".wrl", PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".wrz", new MimeType { FileExtension = ".wrz", PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".wsc", new MimeType { FileExtension = ".wsc", PrimaryMimeType = "text/scriptlet", SecondaryMimeTypes = "" } },
				{ ".wsdl", new MimeType { FileExtension = ".wsdl", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".wvx", new MimeType { FileExtension = ".wvx", PrimaryMimeType = "video/x-ms-wvx", SecondaryMimeTypes = "" } },
				{ ".x", new MimeType { FileExtension = ".x", PrimaryMimeType = "application/directx", SecondaryMimeTypes = "" } },
				{ ".xaf", new MimeType { FileExtension = ".xaf", PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".xaml", new MimeType { FileExtension = ".xaml", PrimaryMimeType = "application/xaml+xml", SecondaryMimeTypes = "" } },
				{ ".xap", new MimeType { FileExtension = ".xap", PrimaryMimeType = "application/x-silverlight-app", SecondaryMimeTypes = "" } },
				{ ".xbap", new MimeType { FileExtension = ".xbap", PrimaryMimeType = "application/x-ms-xbap", SecondaryMimeTypes = "" } },
				{ ".xbm", new MimeType { FileExtension = ".xbm", PrimaryMimeType = "image/x-xbitmap", SecondaryMimeTypes = "" } },
				{ ".xdr", new MimeType { FileExtension = ".xdr", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".xht", new MimeType { FileExtension = ".xht", PrimaryMimeType = "application/xhtml+xml", SecondaryMimeTypes = "" } },
				{ ".xhtml", new MimeType { FileExtension = ".xhtml", PrimaryMimeType = "application/xhtml+xml", SecondaryMimeTypes = "" } },
				{ ".xla", new MimeType { FileExtension = ".xla", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlam", new MimeType { FileExtension = ".xlam", PrimaryMimeType = "application/vnd.ms-excel.addin.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlc", new MimeType { FileExtension = ".xlc", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xld", new MimeType { FileExtension = ".xld", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlk", new MimeType { FileExtension = ".xlk", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xll", new MimeType { FileExtension = ".xll", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlm", new MimeType { FileExtension = ".xlm", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xls", new MimeType { FileExtension = ".xls", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xlsb", new MimeType { FileExtension = ".xlsb", PrimaryMimeType = "application/vnd.ms-excel.sheet.binary.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlsm", new MimeType { FileExtension = ".xlsm", PrimaryMimeType = "application/vnd.ms-excel.sheet.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xlsx", new MimeType { FileExtension = ".xlsx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", SecondaryMimeTypes = "zip" } },
				{ ".xlt", new MimeType { FileExtension = ".xlt", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xltm", new MimeType { FileExtension = ".xltm", PrimaryMimeType = "application/vnd.ms-excel.template.macroEnabled.12", SecondaryMimeTypes = "" } },
				{ ".xltx", new MimeType { FileExtension = ".xltx", PrimaryMimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.template", SecondaryMimeTypes = "zip" } },
				{ ".xlw", new MimeType { FileExtension = ".xlw", PrimaryMimeType = "application/vnd.ms-excel", SecondaryMimeTypes = "" } },
				{ ".xml", new MimeType { FileExtension = ".xml", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xmta", new MimeType { FileExtension = ".xmta", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xof", new MimeType { FileExtension = ".xof", PrimaryMimeType = "x-world/x-vrml", SecondaryMimeTypes = "" } },
				{ ".XOML", new MimeType { FileExtension = ".XOML", PrimaryMimeType = "text/plain", SecondaryMimeTypes = "" } },
				{ ".xpm", new MimeType { FileExtension = ".xpm", PrimaryMimeType = "image/x-xpixmap", SecondaryMimeTypes = "" } },
				{ ".xps", new MimeType { FileExtension = ".xps", PrimaryMimeType = "application/vnd.ms-xpsdocument", SecondaryMimeTypes = "" } },
				{ ".xrm-ms", new MimeType { FileExtension = ".xrm-ms", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsc", new MimeType { FileExtension = ".xsc", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xsd", new MimeType { FileExtension = ".xsd", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsf", new MimeType { FileExtension = ".xsf", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsl", new MimeType { FileExtension = ".xsl", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xslt", new MimeType { FileExtension = ".xslt", PrimaryMimeType = "text/xml", SecondaryMimeTypes = "" } },
				{ ".xsn", new MimeType { FileExtension = ".xsn", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".xss", new MimeType { FileExtension = ".xss", PrimaryMimeType = "application/xml", SecondaryMimeTypes = "" } },
				{ ".xtp", new MimeType { FileExtension = ".xtp", PrimaryMimeType = "application/octet-stream", SecondaryMimeTypes = "" } },
				{ ".xwd", new MimeType { FileExtension = ".xwd", PrimaryMimeType = "image/x-xwindowdump", SecondaryMimeTypes = "" } },
				{ ".z", new MimeType { FileExtension = ".z", PrimaryMimeType = "application/x-compress", SecondaryMimeTypes = "" } },
				{ ".zip", new MimeType { FileExtension = ".zip", PrimaryMimeType = "application/x-zip-compressed", SecondaryMimeTypes = "zip" } },
			};

			#endregion init file extension map

			ms_oMimeTypeMap = new SortedDictionary<string, MimeType>();

			foreach (KeyValuePair<string, MimeType> pair in ms_oFileExtMap) {
				string sMimeType = pair.Value.PrimaryMimeType;

				if (ms_oMimeTypeMap.ContainsKey(sMimeType))
					ms_oMimeTypeMap[sMimeType].AddSecondary(pair.Value);
				else
					ms_oMimeTypeMap[sMimeType] = pair.Value.CloneSecondary();
			} // for each
		} // static constructor

		#endregion static constructor

		#region public

		public const string DefaultMimeType = "application/octet-stream";
		public const string TextMimeType = "text/plain";

		#region method Find

		public MimeType Find(string sMimeType) {
			MimeType oType = null;
			ms_oMimeTypeMap.TryGetValue(sMimeType, out oType);
			return oType;
		} // Find

		#endregion method Find

		#region method Get

		public MimeType Get(string sFileName) {
			string sExtension = null;

			if (!string.IsNullOrWhiteSpace(sFileName)) {
				int nPos = sFileName.LastIndexOf('.');

				if (nPos >= 0)
					sExtension = sFileName.Substring(nPos);
			} // if

			sExtension = (sExtension ?? string.Empty).Trim();

			if (!sExtension.StartsWith("."))
				sExtension = "." + sExtension;

			MimeType oMimeType;

			if (ms_oFileExtMap.TryGetValue(sExtension.ToLowerInvariant(), out oMimeType))
				return oMimeType;

			return null;
		} // Get

		#endregion method Get

		#region indexer

		public string this[string sExtension] {
			get {
				sExtension = (sExtension ?? string.Empty).Trim();

				if (!sExtension.StartsWith("."))
					sExtension = "." + sExtension;

				MimeType oMimeType;

				return ms_oFileExtMap.TryGetValue(sExtension.ToLowerInvariant(), out oMimeType) ? oMimeType.PrimaryMimeType : DefaultMimeType;
			} // get
		} // indexer

		#endregion indexer

		#region method GetFromFile

		public string GetFromFile(byte[] oBuffer, int? nBufferLength = 256) {
			try {
				System.UInt32 oMimeType;

				int nBufLen = nBufferLength ?? oBuffer.Length;

				if ((nBufLen <= 0) || (nBufLen > oBuffer.Length))
					nBufLen = oBuffer.Length;

				FindMimeFromData(0, null, oBuffer, (uint)nBufLen, null, 0, out oMimeType, 0);

				System.IntPtr pMimeType = new IntPtr(oMimeType);

				string sMimeType = Marshal.PtrToStringUni(pMimeType);

				Marshal.FreeCoTaskMem(pMimeType);

				return sMimeType;
			}
			catch (Exception) {
				return null;
			} // try
		} // GetFromFile

		#endregion method GetFromFile

		#endregion public

		#region private

		private static readonly SortedDictionary<string, MimeType> ms_oFileExtMap;
		private static readonly SortedDictionary<string, MimeType> ms_oMimeTypeMap;

		[DllImport(@"urlmon.dll", CharSet = CharSet.Auto)]
		private extern static System.UInt32 FindMimeFromData(
			System.UInt32 pBC,
			[MarshalAs(UnmanagedType.LPStr)] System.String pwzUrl,
			[MarshalAs(UnmanagedType.LPArray)] byte[] pBuffer,
			System.UInt32 cbSize,
			[MarshalAs(UnmanagedType.LPStr)] System.String pwzMimeProposed,
			System.UInt32 dwMimeFlags,
			out System.UInt32 ppwzMimeOut,
			System.UInt32 dwReserverd
		);

		#endregion private
	} // class MimeTypeResolver
} // namespace
