IF OBJECT_ID('RptLeads') IS NULL
	EXECUTE('CREATE PROCEDURE RptLeads AS SELECT 1')
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE RptLeads
@DateStart DATETIME,
@DateEnd DATETIME
AS
BEGIN
	SET NOCOUNT ON;

	EXECUTE RptLeadsAll @DateStart, @DateEnd, 0
END
GO