IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DataSource_StrategyRel]') AND type in (N'U'))
DROP TABLE [dbo].[DataSource_StrategyRel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DataSource_StrategyRel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DataSourceName] [nvarchar](1024) NOT NULL,
	[StrategyId] [int] NOT NULL,
 CONSTRAINT [PK_DATASOURCE_STRATEGYREL] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
