IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MP_YodleeOrderItemBankTransaction]') AND type in (N'U'))
DROP TABLE [dbo].[MP_YodleeOrderItemBankTransaction]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MP_YodleeOrderItemBankTransaction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderItemId] [int] NOT NULL,
	[isSeidFromDataSource] [int] NULL,
	[isSeidFromDataSourceSpecified] [bit] NULL,
	[isSeidMod] [int] NULL,
	[isSeidModSpecified] [bit] NULL,
	[srcElementId] [nvarchar](300) NULL,
	[transactionTypeId] [int] NULL,
	[transactionTypeIdSpecified] [bit] NULL,
	[transactionType] [nvarchar](300) NULL,
	[localizedTransactionType] [nvarchar](300) NULL,
	[transactionStatusId] [int] NULL,
	[transactionStatusIdSpecified] [bit] NULL,
	[transactionStatus] [nvarchar](300) NULL,
	[localizedTransactionStatus] [nvarchar](300) NULL,
	[transactionBaseTypeId] [int] NULL,
	[transactionBaseTypeIdSpecified] [bit] NULL,
	[transactionBaseType] [nvarchar](300) NULL,
	[localizedTransactionBaseType] [nvarchar](300) NULL,
	[categoryId] [int] NULL,
	[categoryIdSpecified] [bit] NULL,
	[bankTransactionId] [int] NULL,
	[bankTransactionIdSpecified] [bit] NULL,
	[bankAccountId] [int] NULL,
	[bankAccountIdSpecified] [bit] NULL,
	[bankStatementId] [int] NULL,
	[bankStatementIdSpecified] [bit] NULL,
	[isDeleted] [int] NULL,
	[isDeletedSpecified] [bit] NULL,
	[lastUpdated] [int] NULL,
	[lastUpdatedSpecified] [bit] NULL,
	[hasDetails] [int] NULL,
	[hasDetailsSpecified] [bit] NULL,
	[transactionId] [nvarchar](300) NULL,
	[transactionCategoryId] [nvarchar](300) NULL,
	[siteCategoryType] [nvarchar](300) NULL,
	[siteCategory] [nvarchar](300) NULL,
	[classUpdationSource] [nvarchar](300) NULL,
	[lastCategorised] [nvarchar](300) NULL,
	[transactionDate] [datetime] NULL,
	[isReimbursable] [int] NULL,
	[isReimbursableSpecified] [bit] NULL,
	[mcCode] [nvarchar](300) NULL,
	[prevLastCategorised] [int] NULL,
	[prevLastCategorisedSpecified] [bit] NULL,
	[naicsCode] [nvarchar](300) NULL,
	[runningBalance] [float] NULL,
	[runningBalanceCurrency] [nvarchar](3) NULL,
	[userDescription] [nvarchar](300) NULL,
	[customCategoryId] [int] NULL,
	[customCategoryIdSpecified] [bit] NULL,
	[memo] [nvarchar](300) NULL,
	[parentId] [int] NULL,
	[parentIdSpecified] [bit] NULL,
	[isOlbUserDesc] [int] NULL,
	[isOlbUserDescSpecified] [bit] NULL,
	[categorisationSourceId] [nvarchar](300) NULL,
	[plainTextDescription] [nvarchar](300) NULL,
	[splitType] [nvarchar](300) NULL,
	[categoryLevelId] [int] NULL,
	[categoryLevelIdSpecified] [bit] NULL,
	[calcRunningBalance] [float] NULL,
	[calcRunningBalanceCurrency] [nvarchar](3) NULL,
	[category] [nvarchar](300) NULL,
	[link] [nvarchar](300) NULL,
	[postDate] [datetime] NULL,
	[prevTransactionCategoryId] [int] NULL,
	[prevTransactionCategoryIdSpecified] [bit] NULL,
	[isBusinessExpense] [int] NULL,
	[isBusinessExpenseSpecified] [bit] NULL,
	[descriptionViewPref] [int] NULL,
	[descriptionViewPrefSpecified] [bit] NULL,
	[prevCategorisationSourceId] [int] NULL,
	[prevCategorisationSourceIdSpecified] [bit] NULL,
	[transactionAmount] [float] NULL,
	[transactionAmountCurrency] [nvarchar](3) NULL,
	[transactionPostingOrder] [int] NULL,
	[transactionPostingOrderSpecified] [bit] NULL,
	[checkNumber] [nvarchar](300) NULL,
	[description] [nvarchar](300) NULL,
	[isTaxDeductible] [int] NULL,
	[isTaxDeductibleSpecified] [bit] NULL,
	[isMedicalExpense] [int] NULL,
	[isMedicalExpenseSpecified] [bit] NULL,
	[categorizationKeyword] [nvarchar](300) NULL,
	[sourceTransactionType] [nvarchar](300) NULL,
 CONSTRAINT [PK_MP_YodleeOrderItemBankTransaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MP_YodleeOrderItemBankTransactionOrderItemId] ON [dbo].[MP_YodleeOrderItemBankTransaction] 
(
	[OrderItemId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
