UPDATE CollectionSmsTemplate SET Template = '{0} This is to remind you that payment of {1} is overdue with Everline. Please call the collections team on 02036677522 ASAP.' WHERE Type = 'CollectionDay0' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0} Your outstanding balance of {1} with Everline has not been settled. To avoid additional late payment fees call collections on 02036677522' WHERE Type = 'CollectionDay1to6' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0}, the {1}, balance including £20 late payment on your Everline account is overdue. To avoid debt collection proceedings call 02036677522' WHERE Type = 'CollectionDay7' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = 'Warning - {0} late fees and daily interest have been added to your account. Act now to avoid further action call collections on 02036677522' WHERE Type = 'CollectionDay8to14' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0} Final reminder: Payment of {1} was due on {2}. If we do not receive payment we will submit your account to our legal department. 02036677516' WHERE Type = 'CollectionDay15' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0} you have failed to settle your payment. Everline has submitted your account for legal proceedings. Please call collections on 02036677516' WHERE Type = 'CollectionDay21' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0} You have failed to settle your payment. Everline has submitted your account for legal proceedings. Call collections on 02036677516' WHERE Type = 'CollectionDay31' AND OriginID =	2
UPDATE CollectionSmsTemplate SET Template = '{0} This is to remind you that payment of {1} is overdue with ezbob. Please call the collections team on 02036677522 ASAP.' WHERE Type = 'CollectionDay0' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = '{0} Your outstanding balance of {1} with ezbob has not been settled. To avoid additional late payment fees call collections on 02036677522' WHERE Type = 'CollectionDay1to6' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = '{0}, the {1}, balance including £20 late payment on your ezbob account is overdue. To avoid debt collection proceedings call 02036677522' WHERE Type = 'CollectionDay7' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = 'Warning - {0} late fees and daily interest have been added to your account. Act now to avoid further action call collections on 02036677522' WHERE Type = 'CollectionDay8to14' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = '{0} Final reminder: Payment of {1} was due on {2}. If we do not receive payment we will submit your account to our legal department. 02036677516' WHERE Type = 'CollectionDay15' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = '{0} you have failed to settle your payment. ezbob has submitted your account for legal proceedings. Please call collections on 02036677516' WHERE Type = 'CollectionDay21' AND OriginID =	1
UPDATE CollectionSmsTemplate SET Template = '{0} You have failed to settle your payment. ezbob has submitted your account for legal proceedings. Call collections on 02036677516' WHERE Type = 'CollectionDay31' AND OriginID =	1
GO
